# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Test shapes for sym_size operator - returns tensor shape as a list
SHAPES_FOR_SYMSIZE = [
    (2, 3),
    (128, 256),
    (512, 512),
    (1, 2, 3),
    (4, 8, 16, 32),
    (10,),
    (1,),  # Single element tensor
]


@pytest.mark.sym_size
@pytest.mark.parametrize("shape", SHAPES_FOR_SYMSIZE)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_sym_size(shape, dtype):
    # sym_size is a metadata operation that returns a Python list, not a tensor,
    # so we use plain assert instead of gems_assert_close/gems_assert_equal.
    x = torch.randn(*shape, dtype=dtype, device=flag_gems.device)
    ref_x = utils.to_reference(x)

    # Get sym_size result from reference (PyTorch default)
    ref_out = torch.ops.aten.sym_size(ref_x)
    # Get sym_size result from FlagGems
    act_out = flag_gems.sym_size(x)

    # Compare the returned lists
    assert act_out == ref_out, f"sym_size mismatch: got {act_out}, expected {ref_out}"
