# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Matrix shapes for linalg_cond tests
LINALG_COND_SHAPES = [(2, 2), (4, 4), (8, 8), (16, 16), (32, 32)]
LINALG_COND_SHAPES_SVD = [(2, 3), (4, 4), (4, 6), (8, 8), (16, 16)]

# Only float32 supported: Triton Jacobi SVD implementation uses float32
LINALG_COND_DTYPES = [torch.float32]

# Condition number is sensitive to numerical differences between GPU/CPU
# inverse implementations. Use relative tolerance based on matrix condition.
LINALG_COND_RTOL = 0.15


def _make_moderate_cond_matrix(shape, dtype, device):
    """Generate a matrix with moderate, bounded condition number.

    Adds a large diagonal to ensure the condition number stays
    in a predictable range, avoiding flaky test failures from ill-conditioned
    random matrices where GPU/CPU inverse differences get amplified.
    """
    n = shape[-1]
    batch_shape = shape[:-2]
    A = torch.randn(shape, dtype=dtype, device=device)
    # Add n*I to keep condition number bounded at ~O(n)
    eye = torch.eye(n, dtype=dtype, device=device)
    for _ in batch_shape:
        eye = eye.unsqueeze(0)
    eye = eye.expand_as(A)
    A = A + n * eye
    return A


@pytest.mark.linalg_cond
@pytest.mark.parametrize("shape", LINALG_COND_SHAPES)
@pytest.mark.parametrize("dtype", LINALG_COND_DTYPES)
def test_linalg_cond(shape, dtype):
    # Test with p=None (2-norm via Jacobi SVD)
    A = _make_moderate_cond_matrix(shape, dtype, flag_gems.device)
    ref_A = utils.to_reference(A)

    ref_out = torch.linalg.cond(ref_A)
    res_out = torch.linalg.cond(A)

    # Use relative comparison for condition numbers
    utils.gems_assert_close(res_out, ref_out, dtype, atol=1.0)


@pytest.mark.linalg_cond
@pytest.mark.parametrize("shape", LINALG_COND_SHAPES)
@pytest.mark.parametrize("dtype", LINALG_COND_DTYPES)
@pytest.mark.parametrize("p", ["fro", "nuc", float("inf"), 1, -1])
def test_linalg_cond_with_p(shape, dtype, p):
    # Test with various p values that require square matrices
    A = _make_moderate_cond_matrix(shape, dtype, flag_gems.device)
    ref_A = utils.to_reference(A)

    ref_out = torch.linalg.cond(ref_A, p=p)
    res_out = torch.linalg.cond(A, p=p)

    # Use relative comparison for condition numbers
    utils.gems_assert_close(res_out, ref_out, dtype, atol=1.0)


@pytest.mark.linalg_cond
@pytest.mark.parametrize("shape", LINALG_COND_SHAPES_SVD)
@pytest.mark.parametrize("dtype", LINALG_COND_DTYPES)
@pytest.mark.parametrize("p", [2, -2])
def test_linalg_cond_svd(shape, dtype, p):
    # Test with p=2 or p=-2 which can work with non-square matrices
    m, n = shape[-2], shape[-1]
    A = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    # Make well-conditioned by adding scaled identity to square part
    k = min(m, n)
    eye_k = torch.eye(k, dtype=dtype, device=flag_gems.device)
    A[..., :k, :k] = A[..., :k, :k] + k * eye_k
    ref_A = utils.to_reference(A)

    ref_out = torch.linalg.cond(ref_A, p=p)
    res_out = torch.linalg.cond(A, p=p)

    # Use relative comparison for condition numbers
    utils.gems_assert_close(res_out, ref_out, dtype, atol=1.0)
