# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from .conftest import TO_CPU

# Shapes for per-tensor quantization observer+fakequant testing
SHAPES = [(1024,), (4096,), (16384,), (65536,), (262144,), (1048576,)]


def ref_fused_moving_avg_obs_fake_quant(
    input,
    observer_on,
    fake_quant_on,
    running_min,
    running_max,
    scale,
    zero_point,
    averaging_const,
    quant_min,
    quant_max,
    ch_axis,
    per_row_fake_quant=False,
    symmetric_quant=False,
):
    """Reference implementation in pure PyTorch."""
    x = input.float()

    if observer_on:
        cur_min = x.min()
        cur_max = x.max()
        running_min.lerp_(cur_min, averaging_const)
        running_max.lerp_(cur_max, averaging_const)

    rmin = min(running_min.item(), 0.0)
    rmax = max(running_max.item(), 0.0)
    qmin_f = float(quant_min)
    qmax_f = float(quant_max)

    sc = (rmax - rmin) / (qmax_f - qmin_f)
    if sc == 0.0:
        sc = 0.1
    zp = round(qmin_f - rmin / sc)
    zp = min(max(zp, qmin_f), qmax_f)

    if symmetric_quant and rmin < 0.0 and rmax > 0.0:
        sc = max(-rmin / (-qmin_f), rmax / qmax_f)
        if sc == 0.0:
            sc = 0.1
        zp = round((qmin_f + qmax_f) / 2.0)

    scale.fill_(sc)
    zero_point.fill_(int(zp))

    if fake_quant_on:
        sc_t = torch.tensor(sc, dtype=torch.float32, device=input.device)
        zp_t = torch.tensor(zp, dtype=torch.float32, device=input.device)
        q = torch.round(x / sc_t) + zp_t
        q = q.clamp(qmin_f, qmax_f)
        out = (q - zp_t) * sc_t
        return out.to(input.dtype)
    else:
        return input.clone()


@pytest.mark.fused_moving_avg_obs_fake_quant
@pytest.mark.parametrize("shape", SHAPES)
@pytest.mark.parametrize("observer_on", [True, False])
@pytest.mark.parametrize("fake_quant_on", [True, False])
@pytest.mark.parametrize("symmetric_quant", [False])
def test_accuracy_fused_moving_avg_obs_fake_quant(
    shape, observer_on, fake_quant_on, symmetric_quant
):
    torch.manual_seed(42)
    quant_min = 0
    quant_max = 255
    averaging_const = 0.01

    input_tensor = torch.randn(shape, device=flag_gems.device, dtype=torch.float32)

    # Reference — run on CPU when --ref=cpu (quick-cpu mode)
    ref_device = "cpu" if TO_CPU else flag_gems.device
    input_ref = input_tensor.to(ref_device)
    running_min_ref = torch.tensor([-1.0], device=ref_device, dtype=torch.float32)
    running_max_ref = torch.tensor([1.0], device=ref_device, dtype=torch.float32)
    scale_ref = torch.tensor([1.0], device=ref_device, dtype=torch.float32)
    zp_ref = torch.zeros(1, device=ref_device, dtype=torch.int32)

    ref_out = ref_fused_moving_avg_obs_fake_quant(
        input_ref,
        observer_on,
        fake_quant_on,
        running_min_ref,
        running_max_ref,
        scale_ref,
        zp_ref,
        averaging_const,
        quant_min,
        quant_max,
        -1,
        symmetric_quant=symmetric_quant,
    )

    # Triton via flag_gems
    running_min_tri = torch.tensor([-1.0], device=flag_gems.device, dtype=torch.float32)
    running_max_tri = torch.tensor([1.0], device=flag_gems.device, dtype=torch.float32)
    scale_tri = torch.tensor([1.0], device=flag_gems.device, dtype=torch.float32)
    zp_tri = torch.zeros(1, device=flag_gems.device, dtype=torch.int32)

    res_out = flag_gems.ops.fused_moving_avg_obs_fake_quant(
        input_tensor,
        torch.tensor([observer_on], dtype=torch.int32),
        torch.tensor([fake_quant_on], dtype=torch.int32),
        running_min_tri,
        running_max_tri,
        scale_tri,
        zp_tri,
        averaging_const,
        quant_min,
        quant_max,
        -1,
        symmetric_quant=symmetric_quant,
    )

    utils.gems_assert_close(res_out, ref_out, dtype=torch.float32, atol=1e-2)

    if observer_on:
        utils.gems_assert_close(
            running_min_tri, running_min_ref, dtype=torch.float32, atol=1e-4
        )
        utils.gems_assert_close(
            running_max_tri, running_max_ref, dtype=torch.float32, atol=1e-4
        )
