# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Per-channel fake-quant shapes: (shape, axis). Scale/zero-point live along axis.
PER_CHANNEL_SHAPES = (
    [((2, 19, 7), 1)]
    if utils.QUICK_MODE
    else [
        ((8,), 0),
        ((4, 8), 0),
        ((4, 8), 1),
        ((2, 19, 7), 1),
        ((2, 19, 7), 2),
        ((16, 128, 64, 60), 1),
        ((16, 128, 64, 60), 3),
    ]
)

# Typical quantization ranges: unsigned 8-bit and signed 8-bit.
QUANT_RANGES = [(0, 255), (-128, 127)]


@pytest.mark.fake_quantize_learnable_per_channel_affine
@pytest.mark.parametrize("shape, axis", PER_CHANNEL_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
@pytest.mark.parametrize("quant_min, quant_max", QUANT_RANGES)
def test_fake_quantize_learnable_per_channel_affine(
    shape, axis, dtype, quant_min, quant_max
):
    res_inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    channels = shape[axis]
    scale = (
        torch.rand(channels, dtype=torch.float32, device=flag_gems.device) * 0.5 + 0.01
    )
    zero_point = torch.randn(channels, dtype=torch.float32, device=flag_gems.device)
    ref_inp = utils.to_reference(res_inp)
    ref_scale = utils.to_reference(scale)
    ref_zp = utils.to_reference(zero_point)

    grad_factor = 1.0
    ref_out = torch.ops.aten._fake_quantize_learnable_per_channel_affine(
        ref_inp, ref_scale, ref_zp, axis, quant_min, quant_max, grad_factor
    )
    res_out = flag_gems._fake_quantize_learnable_per_channel_affine(
        res_inp, scale, zero_point, axis, quant_min, quant_max, grad_factor
    )

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.fake_quantize_learnable_per_channel_affine
@pytest.mark.parametrize("shape, axis", PER_CHANNEL_SHAPES)
# grad_factor test runs on fp32 only.
@pytest.mark.parametrize("dtype", [torch.float32])
def test_fake_quantize_learnable_per_channel_affine_grad_factor(shape, axis, dtype):
    # grad_factor only affects the backward pass; the forward output must be
    # identical to the standard per-channel fake quantize regardless of its value.
    res_inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    channels = shape[axis]
    scale = (
        torch.rand(channels, dtype=torch.float32, device=flag_gems.device) * 0.5 + 0.01
    )
    zero_point = torch.randn(channels, dtype=torch.float32, device=flag_gems.device)
    ref_inp = utils.to_reference(res_inp)
    ref_scale = utils.to_reference(scale)
    ref_zp = utils.to_reference(zero_point)

    ref_out = torch.ops.aten._fake_quantize_learnable_per_channel_affine(
        ref_inp, ref_scale, ref_zp, axis, 0, 255, 2.5
    )
    res_out = flag_gems._fake_quantize_learnable_per_channel_affine(
        res_inp, scale, zero_point, axis, 0, 255, 2.5
    )

    utils.gems_assert_close(res_out, ref_out, dtype)
