# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.t_
@pytest.mark.parametrize("shape", [(2, 3), (128, 256), (512, 512)])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_t_(shape, dtype):
    x = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_x = utils.to_reference(x)
    ref_out = torch.ops.aten.t_(ref_x)
    act_out = flag_gems.t_(x)
    utils.gems_assert_close(act_out, ref_out, dtype)


@pytest.mark.t_
@pytest.mark.parametrize("shape", [(5,), (1024,), (8192,)])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_t_1d(shape, dtype):
    # For 1D tensors, t_ should be a no-op
    x = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_x = utils.to_reference(x)
    ref_out = torch.ops.aten.t_(ref_x)
    act_out = flag_gems.t_(x)
    utils.gems_assert_close(act_out, ref_out, dtype)
