# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch
from torch.nested._internal.nested_tensor import _nt_view_dummy, _store_val_in_tensor

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

pytestmark = pytest.mark.skipif(
    cfg.TO_CPU, reason="CUDA-only op; no CPU reference implementation"
)


def _assert_nested_equal(res, ref):
    """Assert that two nested tensors are structurally identical."""
    assert res.is_nested
    assert ref.is_nested
    assert res.shape == ref.shape
    assert res._ragged_idx == ref._ragged_idx
    utils.gems_assert_close(res.values(), ref.values(), ref.values().dtype)
    assert torch.equal(res.offsets(), ref.offsets())

    res_lengths = res.lengths()
    ref_lengths = ref.lengths()
    if res_lengths is None or ref_lengths is None:
        assert res_lengths is None and ref_lengths is None
    else:
        assert torch.equal(res_lengths, ref_lengths)

    assert set(res._metadata_cache.keys()) == set(ref._metadata_cache.keys())
    for key in ref._metadata_cache:
        assert res._metadata_cache[key].shape == ref._metadata_cache[key].shape


def _make_offsets(batch_lengths):
    offsets = [0]
    for length in batch_lengths:
        offsets.append(offsets[-1] + length)
    return torch.tensor(offsets, dtype=torch.int64, device=flag_gems.device)


def _make_inputs(dtype, batch_lengths, inner_dims):
    offsets = _make_offsets(batch_lengths)
    total = sum(batch_lengths)
    values = torch.randn(
        (total,) + tuple(inner_dims), dtype=dtype, device=flag_gems.device
    )
    return values, offsets


def _run(values, offsets, lengths=None, ragged_idx=1, min_seqlen=None, max_seqlen=None):
    dummy = _nt_view_dummy()
    ref_out = torch.ops.aten._nested_view_from_jagged(
        utils.to_reference(values),
        offsets,
        dummy,
        lengths,
        ragged_idx,
        min_seqlen,
        max_seqlen,
    )
    res_out = flag_gems._nested_view_from_jagged(
        values, offsets, dummy, lengths, ragged_idx, min_seqlen, max_seqlen
    )
    return res_out, ref_out


@pytest.mark.nested_view_from_jagged
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_nested_view_from_jagged_basic(dtype):
    batch_lengths = [2, 1, 3, 2, 4]
    values, offsets = _make_inputs(dtype, batch_lengths, inner_dims=(5,))
    res_out, ref_out = _run(values, offsets)
    _assert_nested_equal(res_out, ref_out)


@pytest.mark.nested_view_from_jagged
@pytest.mark.parametrize("batch_lengths", [[1], [1, 1, 1], [2, 3, 1, 5, 2, 6]])
def test_nested_view_from_jagged_batch_sizes(batch_lengths):
    values, offsets = _make_inputs(torch.float32, batch_lengths, inner_dims=(4,))
    res_out, ref_out = _run(values, offsets)
    _assert_nested_equal(res_out, ref_out)


@pytest.mark.nested_view_from_jagged
def test_nested_view_from_jagged_with_lengths():
    batch_lengths = [3, 2, 1, 4, 2]
    values, offsets = _make_inputs(torch.float32, batch_lengths, inner_dims=(5,))
    lengths = torch.tensor(batch_lengths, dtype=torch.int64, device=flag_gems.device)
    res_out, ref_out = _run(values, offsets, lengths=lengths)
    _assert_nested_equal(res_out, ref_out)


@pytest.mark.nested_view_from_jagged
def test_nested_view_from_jagged_minmax_seqlen():
    batch_lengths = [3, 2, 1, 4, 2]
    values, offsets = _make_inputs(torch.float32, batch_lengths, inner_dims=(5,))
    min_seqlen = _store_val_in_tensor(1)
    max_seqlen = _store_val_in_tensor(4)
    res_out, ref_out = _run(
        values, offsets, min_seqlen=min_seqlen, max_seqlen=max_seqlen
    )
    _assert_nested_equal(res_out, ref_out)


@pytest.mark.nested_view_from_jagged
def test_nested_view_from_jagged_ragged_idx():
    batch_lengths = [2, 1, 3]
    # values buffer of shape (D0, total, D2) with ragged dim at index 1
    offsets = _make_offsets(batch_lengths)
    total = sum(batch_lengths)
    values = torch.randn(4, total, 6, dtype=torch.float32, device=flag_gems.device)
    res_out, ref_out = _run(values, offsets, ragged_idx=2)
    _assert_nested_equal(res_out, ref_out)


@pytest.mark.nested_view_from_jagged
def test_nested_view_from_jagged_int32_offsets():
    batch_lengths = [2, 1, 3, 2]
    values, offsets = _make_inputs(torch.float32, batch_lengths, inner_dims=(5,))
    offsets = offsets.to(torch.int32)
    res_out, ref_out = _run(values, offsets)
    _assert_nested_equal(res_out, ref_out)
