# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Kunlunxin (XPU) specialization of ``aten::flip``.

The generic implementation feeds a negative-stride ``StridedBuffer`` into the
vendor ``pointwise_dynamic`` codegen.  On TritonXPU that generated kernel is
unsafe for two independent reasons:

1. It relies on ``mask=tid < num_tasks`` to discard the surplus lanes of its
   ``12 x next_power_of_2(ceil(n/12))`` lane grid.  That masked memory path is
   itself mis-lowered at one specific lane count: with ``tile_size == 32768`` a
   reversed (stride -1) gather raises ``KL_XID_KERNEL_EXCEPTION`` /
   ``status=700`` **6 times out of 6**, even when the task space is covered
   exactly and not one lane is out of range, while the identical kernel at
   4096 / 8192 / 16384 / 65536 / 131072 lanes is clean in every
   mask x dtype x direction combination.  ``tile_size`` is
   ``next_power_of_2(ceil(n/12))``, so *every* shape with
   ``196608 < numel <= 393216`` lands on 32768 and dies -- which is why
   ``A.flip(-1)`` on a 512x512 fp32 tensor kills the CUDA context.
2. The surplus lanes of that grid also compute addresses outside the input
   allocation.  Measured here they neither fault nor leak data, but they are
   unnecessary, and the mask meant to suppress them is exactly the construct
   that is mis-lowered.

This implementation keeps the vendor tile width and grid (both matter: a
narrower tile costs up to 6.5x, an exactly-covering grid costs 1.6x on a
reversed gather) but

* never emits the 32768 lane tile;
* clamps the linear task index into range before decomposing it, so every lane
  -- surplus or not -- computes a legal input address and the gather needs no
  mask at all (the clamp is compiled out when the grid covers the task space
  exactly, where it would cost up to 146x on a block copy);
* keeps only the store masked, plus one vector burst of slack in the output
  allocation, and hands back a prefix view.
"""

import importlib.util
import logging
import os
from typing import Dict, List, Sequence, Tuple

import torch
import triton

from flag_gems.utils.code_cache import code_cache_dir
from flag_gems.utils.shape_utils import heuristics_for_num_warps

logger = logging.getLogger(__name__)

# Number of clusters the vendor pointwise codegen targets on XPU.  The tile width
# is kept identical to that codegen (`next_power_of_2(ceil(n / 12))`): narrower
# tiles cost up to 6.5x on every large shape.
_XPU_BLOCK_NUM = 12
# The one lane count the backend mis-lowers for a reversed unit-stride gather --
# see `_partition`.  Never emitted.
_BAD_TILE = 32768
# Widest tile that is safe when the innermost gather stride is neither +1 nor -1.
# A non-unit-stride gather (what a non-dense input produces) faults at 16384 and
# 32768 lanes; 8192 and below is clean over the whole sweep.
_MAX_STRIDED_TILE = 8192
# Never emit a tile narrower than one vector store: a vector store is lowered to
# a fixed 64 element burst on this backend.
_MIN_TILE = 64
# The store is masked, so it must not write outside the task space; this slack
# only covers the 64 element granularity of that burst.  It is also what the
# canary uses to prove the store never runs past the task space.
_STORE_SLACK = 1024
# Shortest innermost contiguous run that still profits from the mask-free block
# path; 512 does (0.069 ms), 100 does not (it prefers the masked 12 CTA form).
_BLOCK_RUN = 256


_KERNEL_MODULE_TEMPLATE = """# Auto-generated by flag_gems/runtime/backend/_kunlunxin/ops/flip.py
import triton
from triton import language as tl

from flag_gems.utils import triton_lang_extension as ext
from flag_gems.utils.libentry import libentry


@libentry()
@triton.jit
def {kernel_name}(
    in_ptr,
    out_ptr,
{params}    in_offset: tl.constexpr,
    num_tasks: tl.constexpr,
    tile_size: tl.constexpr,
    clamp: tl.constexpr,
):
    pid = ext.program_id(0)
    offs = pid * tile_size + tl.arange(0, tile_size)
{body}
"""


def _gen_body(rank: int, indent: str, mask_load: bool, mask_store: bool) -> str:
    lines = [
        "if clamp:",
        # the surplus lanes of the last tile are folded onto the last real task,
        # so the gather stays in range without a mask
        "    task = tl.minimum(offs, num_tasks - 1)",
        "else:",
        "    task = offs",
    ]
    if mask_load or mask_store:
        lines.append("keep = offs < num_tasks")
    for i in range(rank - 1, 0, -1):
        lines.append(f"i{i} = task % s{i}")
        lines.append(f"task = task // s{i}")
    lines.append("i0 = task")
    terms = " + ".join(f"i{i} * t{i}" for i in range(rank))
    lines.append(f"src = in_offset + {terms}")
    load_mask = ", mask=keep" if mask_load else ""
    lines.append(f"val = tl.load(in_ptr + src{load_mask}).to(in_ptr.type.element_ty)")
    store_mask = ", mask=keep" if mask_store else ""
    lines.append(f"tl.store(out_ptr + offs, val{store_mask})")
    return "\n".join(indent + ln for ln in lines)


_KERNEL_CACHE: Dict[Tuple[int, bool, bool], object] = {}


def _get_kernel(rank: int, mask_load: bool = True, mask_store: bool = True):
    key = (rank, mask_load, mask_store)
    kernel = _KERNEL_CACHE.get(key)
    if kernel is not None:
        return kernel
    suffix = f"{'ml' if mask_load else ''}{'ms' if mask_store else ''}" or "raw"
    kernel_name = f"_flip_kernel_rank_{rank}_{suffix}"
    params = "".join(
        f"    s{i}: tl.constexpr,\n    t{i}: tl.constexpr,\n" for i in range(rank)
    )
    source = _KERNEL_MODULE_TEMPLATE.format(
        kernel_name=kernel_name,
        params=params,
        body=_gen_body(rank, " " * 4, mask_load, mask_store),
    )
    module_name = f"_kunlunxin_flip_rank_{rank}_{suffix}_pid_{os.getpid()}"
    path = code_cache_dir() / f"{module_name}.py"
    with open(path, "wt", encoding="utf-8") as f:
        f.write(source)
    spec = importlib.util.spec_from_file_location(module_name, str(path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    kernel = getattr(module, kernel_name)
    _KERNEL_CACHE[key] = kernel
    return kernel


def _contiguous_strides(shape: Sequence[int]) -> Tuple[int, ...]:
    strides: List[int] = [1] * len(shape)
    acc = 1
    for i in range(len(shape) - 1, -1, -1):
        strides[i] = acc
        acc *= shape[i]
    return tuple(strides)


def _out_layout(inp: torch.Tensor) -> Tuple[Tuple[int, ...], Tuple[int, ...]]:
    """Strides of ``torch.empty_like(inp)`` plus the permutation that makes them
    contiguous, so the kernel can walk the output linearly."""
    ndim = inp.dim()
    shape = tuple(inp.shape)
    identity = tuple(range(ndim))
    contiguous = _contiguous_strides(shape)
    if inp.is_contiguous():
        return contiguous, identity
    strides = tuple(inp.stride())
    perm = tuple(sorted(identity, key=lambda i: (-strides[i], i)))
    if tuple(strides[i] for i in perm) == _contiguous_strides(
        tuple(shape[i] for i in perm)
    ):
        return strides, perm
    return contiguous, identity


def _simplify(
    sizes: Sequence[int], in_strides: Sequence[int]
) -> Tuple[List[int], List[int]]:
    """Drop size-1 dims and merge adjacent dims.

    The output is walked linearly in this very order, so its strides are
    contiguous by construction and only the input side has to be checked.
    """
    dims = [(s, st) for s, st in zip(sizes, in_strides) if s != 1]
    if not dims:
        return [1], [0]
    merged = [dims[0]]
    for size, stride in dims[1:]:
        prev_size, prev_stride = merged[-1]
        if prev_stride == stride * size:
            merged[-1] = (prev_size * size, stride)
        else:
            merged.append((size, stride))
    return [m[0] for m in merged], [m[1] for m in merged]


def _partition(
    num_tasks: int, inner_stride: int, exact_grid: bool = False
) -> Tuple[int, int, int]:
    """Tile width and grid.

    The tile width follows the vendor pointwise codegen
    (``next_power_of_2(ceil(n / 12))``); narrower tiles cost up to 6.5x on large
    shapes.  Three adjustments:

    * a non-unit innermost stride (what a non-dense input produces) is capped at
      ``_MAX_STRIDED_TILE``: ``x[..., ::2]`` faults at 16384 and 32768 lanes.
      Because that cap can ask for far more than 12 tiles, those launches fall
      back to a 12 CTA grid-stride loop -- one tile per CTA would mean e.g. 740
      CTAs for a 6 M element non-dense tensor, i.e. ~60 serialised waves.
    * ``tile_size == 32768`` is skipped for unit-stride gathers too.  That single
      lane count is mis-lowered for a reversed gather: 6/6 faults for fp32 with a
      masked gather, 3/3 for fp16 with a masked store, while
      4096/8192/16384/65536/131072 are clean in every mask x dtype x direction
      combination.  Only ``196608 < n <= 393216`` reaches it.
    * the grid is kept at >= 12 CTAs, matching the vendor codegen, except on the
      mask-free block path (``exact_grid``).  An exactly covering grid is 1.6x
      slower for a *masked* gather (13.14 ms vs 8.60 ms on ``(64,512,512)``
      fp16) but 125x faster for the mask-free block copy (0.069 ms).
    """
    tile_size = triton.next_power_of_2(triton.cdiv(num_tasks, _XPU_BLOCK_NUM))
    tile_size = max(_MIN_TILE, tile_size)
    if abs(inner_stride) != 1:
        tile_size = min(tile_size, _MAX_STRIDED_TILE)
    elif tile_size == _BAD_TILE:
        tile_size = _BAD_TILE // 2
    num_ctas = triton.cdiv(num_tasks, tile_size)
    if not exact_grid:
        num_ctas = max(_XPU_BLOCK_NUM, num_ctas)
    return tile_size, num_ctas, num_ctas * tile_size


def flip(A: torch.Tensor, dims) -> torch.Tensor:
    logger.debug("GEMS_KUNLUNXIN FLIP")
    strides = list(A.stride())
    flip_dims_b = [False for _ in A.stride()]
    for dim in dims:
        assert (
            dim >= -A.dim() and dim < A.dim()
        ), "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
            -A.dim(), A.dim() - 1, dim
        )
        assert not flip_dims_b[
            dim
        ], "dim {} appears multiple times in the list of dims".format(dim)
        flip_dims_b[dim] = True
    n = 0
    in_offset = 0
    for i in range(len(flip_dims_b)):
        if flip_dims_b[i] and A.size(i) > 1 and A.stride(i) != 0:
            in_offset += strides[i] * (A.shape[i] - 1)
            strides[i] = -strides[i]
            n += 1
    if n == 0 or A.numel() <= 1:
        return A.clone()

    shape = tuple(A.shape)
    num_tasks = A.numel()
    out_strides, perm = _out_layout(A)
    sizes, in_strides = _simplify([shape[i] for i in perm], [strides[i] for i in perm])
    rank = len(sizes)

    # Mask-free block path: a rank-2 task space whose innermost dim is a long
    # contiguous run lowers to a block DMA and is then 125x faster without the
    # gather mask (0.069 ms vs 8.63 ms on (64,512,512) fp16).  Everywhere else the
    # mask is kept: an unmasked gather is both slower here AND makes LLVM explode
    # (882 s vs 22 s to lower a rank-4 1048576 lane launch).
    block_path = rank == 2 and in_strides[-1] == 1 and sizes[-1] >= _BLOCK_RUN
    tile_size, num_ctas, num_lanes = _partition(
        num_tasks, in_strides[-1], exact_grid=block_path
    )
    # Both memory ops keep their mask: an UNMASKED gather is what makes LLVM
    # explode (882 s vs 22 s to lower this same rank-4 / 1048576 lane launch), so
    # the surplus lanes are neutralised by the index clamp instead, and the tile
    # width guard in `_partition` is what actually keeps us off the fault.  The
    # output still carries one vector burst of slack.
    buffer = torch.empty(num_tasks + _STORE_SLACK, dtype=A.dtype, device=A.device)
    out = torch.as_strided(buffer, shape, out_strides)

    kernel_args: List[int] = []
    for size, stride in zip(sizes, in_strides):
        kernel_args.append(size)
        kernel_args.append(stride)
    _get_kernel(rank, mask_load=not block_path)[(num_ctas, 1, 1)](
        A,
        buffer,
        *kernel_args,
        in_offset=in_offset,
        num_tasks=num_tasks,
        tile_size=tile_size,
        clamp=num_lanes > num_tasks,
        num_warps=heuristics_for_num_warps(tile_size),
        buffer_size_limit=2048,
    )
    return out
