# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

from flag_gems.ops.cummax import scan_then_fan, scan_then_fan_col, scan_then_fan_loop

logger = logging.getLogger(__name__)


def _cummax_helper(input, values, indices, dim):
    """Helper for ``cummax`` that writes the cumulative maximum and the
    index of each maximum value into the pre-allocated ``values`` and
    ``indices`` tensors along the given ``dim``.

    This is the out-of-place kernel used by ``aten::cummax`` /
    ``aten::cummax.out``.  When the caller-provided ``values`` / ``indices``
    buffers are contiguous (the common case), the scan kernels write directly
    into them; otherwise a contiguous staging buffer is used and copied back.
    """
    logger.debug("GEMS CUMMAX_HELPER")
    assert dim >= -input.ndim and dim < input.ndim, "Invalid dim"
    shape = input.shape
    dim = dim % input.ndim
    M = 1
    N = shape[dim]
    for i in range(dim):
        M *= shape[i]
    # bool inputs are promoted to int64 (consistent with aten::cummax and to
    # avoid the shared scan kernels, which do not support int1 directly).
    is_bool = input.dtype is torch.bool
    if is_bool:
        input = input.to(torch.int64)
    input = input.contiguous()
    K = input.numel() // M // N

    compute_dtype = input.dtype
    if input.dtype == torch.float16 or input.dtype == torch.bfloat16:
        compute_dtype = torch.float32

    # Fast path: write the scan result directly into the caller-provided
    # contiguous buffers to avoid an extra allocation + copy. bool inputs
    # take the general path because their values are computed in the
    # promoted int64 dtype.
    if (
        not is_bool
        and values.is_contiguous()
        and indices.is_contiguous()
        and values.dtype == input.dtype
    ):
        out = values
        out_indices = indices
        if M == 1 and K == 1:
            scan_then_fan_col(input, out, out_indices, N, compute_dtype)
        elif M * K <= 16:
            scan_then_fan(input, out, out_indices, M, N, K, compute_dtype)
        else:
            scan_then_fan_loop(input, out, out_indices, M, N, K, compute_dtype)
        return None

    # General path: compute into freshly allocated contiguous tensors (so the
    # scan kernels, which assume contiguous storage, work for any caller-provided
    # out layout/dtype), then copy the results back into the caller-provided
    # tensors, which may be non-contiguous or use the original (un-promoted)
    # value dtype.
    out = torch.empty_like(input)
    out_indices = torch.empty_like(input, dtype=torch.int64)

    if M == 1 and K == 1:
        scan_then_fan_col(input, out, out_indices, N, compute_dtype)
    elif M * K <= 16:
        scan_then_fan(input, out, out_indices, M, N, K, compute_dtype)
    else:
        scan_then_fan_loop(input, out, out_indices, M, N, K, compute_dtype)

    values.copy_(out)
    indices.copy_(out_indices)
