# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def _fake_quantize_learnable_per_tensor_affine_backward_kernel(
    grad_ptr,
    self_ptr,
    scale_ptr,
    zero_point_ptr,
    grad_self_ptr,
    grad_scale_ptr,
    grad_zero_point_ptr,
    n_elements,
    quant_min,
    quant_max,
    grad_factor,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Inputs are loaded in their original dtype and promoted to float32 for
    # computation, matching the behavior of the ATen reference implementation
    # (which requires float32 internally for the rounding/clamping math).
    grad = tl.load(grad_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
    x = tl.load(self_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
    scale = tl.load(scale_ptr).to(tl.float32)
    zero_point = tl.load(zero_point_ptr).to(tl.float32)

    # Forward: y = (clamp(round(x / scale + zero_point), qmin, qmax) - zero_point) * scale
    # The quantized integer value before rescaling.
    q = tl_extra_shim.nearbyint(x / scale + zero_point)
    # Straight-through estimator mask: gradient flows where the rounded
    # quantized value lies inside [quant_min, quant_max] (i.e. clamping did not
    # change the rounded value). Comparing the *rounded* value rather than the
    # raw pre-quantization value matches the ATen reference, which allows a
    # small neighborhood beyond the range that rounds back into range.
    in_range = (q >= quant_min) & (q <= quant_max)
    q = tl.clamp(q, quant_min, quant_max)
    in_range_f = in_range.to(tl.float32)

    # grad w.r.t self: grad * mask (STE gradient, gradient is zeroed for clamped elements)
    grad_self = grad * in_range_f
    tl.store(grad_self_ptr + offsets, grad_self, mask=mask)

    # grad w.r.t scale: sum over elements of grad * ((q - zero_point) - (x / scale) * mask) * grad_factor
    grad_scale_contrib = (
        grad * ((q - zero_point) - (x / scale) * in_range_f) * grad_factor
    )
    # grad w.r.t zero_point: sum over elements of grad * scale * (mask - 1) * grad_factor
    grad_zero_point_contrib = grad * scale * (in_range_f - 1.0) * grad_factor

    block_sum_scale = tl.sum(grad_scale_contrib, axis=0)
    block_sum_zp = tl.sum(grad_zero_point_contrib, axis=0)

    tl.atomic_add(grad_scale_ptr, block_sum_scale)
    tl.atomic_add(grad_zero_point_ptr, block_sum_zp)


def _fake_quantize_learnable_per_tensor_affine_backward(
    grad, self, scale, zero_point, quant_min, quant_max, grad_factor=1.0
):
    logger.debug("GEMS FAKE_QUANTIZE_LEARNABLE_PER_TENSOR_AFFINE_BACKWARD")

    if grad.device.type != "cuda" or self.device.type != "cuda":
        raise ValueError("Inputs must be on a CUDA device.")

    if not (
        grad.is_floating_point()
        and self.is_floating_point()
        and scale.is_floating_point()
        and zero_point.is_floating_point()
    ):
        raise ValueError("All inputs must be floating-point tensors.")

    # The ATen reference rejects float16 gradients ("Expected dY_.scalar_type() ==
    # Float"); only float32 and bfloat16 inputs are supported.
    if self.dtype not in (torch.float32, torch.bfloat16):
        raise ValueError(
            f"Unsupported dtype {self.dtype}; expected float32 or bfloat16."
        )

    # The ATen reference implementation always returns float32 gradients
    # (it rejects float16 grads and promotes bfloat16 grads to float32), so we
    # match that contract: all three output gradients are float32.
    grad_self = torch.empty(self.shape, dtype=torch.float32, device=self.device)
    # grad_scale / grad_zero_point have the same shape as scale / zero_point
    # (per-tensor: a 1-element tensor).
    grad_scale = torch.zeros(scale.shape, dtype=torch.float32, device=scale.device)
    grad_zero_point = torch.zeros(
        zero_point.shape, dtype=torch.float32, device=zero_point.device
    )

    n_elements = self.numel()
    if n_elements == 0:
        return grad_self, grad_scale, grad_zero_point

    # Tile size for the per-element backward kernel; 1024 elements per block.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)

    _fake_quantize_learnable_per_tensor_affine_backward_kernel[grid](
        grad,
        self,
        scale,
        zero_point,
        grad_self,
        grad_scale,
        grad_zero_point,
        n_elements,
        quant_min,
        quant_max,
        float(grad_factor),
        BLOCK_SIZE=BLOCK_SIZE,
    )

    # All three gradients are float32, matching the ATen reference output dtype.
    return grad_self, grad_scale, grad_zero_point
