# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(
    is_tensor=[True, True, True, False, False], promotion_methods=[(0, "DEFAULT")]
)
@triton.jit
def fake_quantize_learnable_per_channel_affine_forward_kernel(
    x, scale, zero_point, quant_min, quant_max
):
    # Mirror the PyTorch native (CPU/CUDA) fake-quantise arithmetic bit-for-bit.
    # The reference computes, in fp32, ``qval = nearbyint(x * (1.0f / scale)) +
    # zero_point`` where ``1.0f / scale`` is the *fp32* reciprocal.  Writing
    # ``1.0 / scale`` in Triton widens the literal to fp64 and the compiler
    # folds the reciprocal + multiply back into a (more precise) true division,
    # which flips round-half-to-even at exact half-way quotients (e.g. 17.5 ->
    # 18 instead of 17) and diverges from the native output by one quant level.
    # ``rcp_rn`` emits a correctly-rounded fp32 reciprocal that matches C's
    # ``1.0f / scale`` exactly, so the subsequent fp32 multiply reproduces the
    # native ``x * inv_scale`` behaviour.
    x_fp32 = x.to(tl.float32)
    scale_fp32 = scale.to(tl.float32)
    zp_int = zero_point.to(tl.int32)
    inv_scale = tl_extra_shim.rcp_rn(scale_fp32)
    qval = tl_extra_shim.nearbyint(x_fp32 * inv_scale) + zp_int.to(tl.float32)
    # quant_min / quant_max are passed as scalar tensors; promote to fp32.
    qmin = quant_min.to(tl.float32)
    qmax = quant_max.to(tl.float32)
    bounded_qval = tl.minimum(qmax, tl.maximum(qmin, qval))
    out = (bounded_qval - zp_int.to(tl.float32)) * scale_fp32
    return out.to(x.dtype)


def _reshape_per_channel_params(param, axis, ndim):
    """Reshape a 1-D per-channel tensor of shape ``(C,)`` to ``(1, ..., C, ..., 1)``
    with ``C`` placed at ``axis`` so that it broadcasts against ``self``."""
    shape = [1] * ndim
    shape[axis] = param.shape[0]
    return param.reshape(shape)


def _prepare_zero_point(zero_point, quant_min, quant_max):
    """Round, clamp and cast the learnable zero point to int, mirroring the
    behaviour of ``_get_rounded_zero_point`` followed by ``.to(kInt)`` in the
    PyTorch native implementation."""
    return zero_point.round().clamp_(quant_min, quant_max).to(torch.int32)


def _fake_quantize_learnable_per_channel_affine_inner(
    self, scale, zero_point, axis, quant_min, quant_max, out=None
):
    if axis < 0:
        axis = self.dim() + axis
    ndim = self.dim()
    scale_v = _reshape_per_channel_params(scale, axis, ndim)
    zero_point_v = _reshape_per_channel_params(zero_point, axis, ndim)
    if out is None:
        return fake_quantize_learnable_per_channel_affine_forward_kernel(
            self, scale_v, zero_point_v, quant_min, quant_max
        )
    fake_quantize_learnable_per_channel_affine_forward_kernel(
        self, scale_v, zero_point_v, quant_min, quant_max, out0=out
    )
    return out


def _fake_quantize_learnable_per_channel_affine(
    self, scale, zero_point, axis, quant_min, quant_max, grad_factor=1.0
):
    logger.debug("GEMS FAKE_QUANTIZE_LEARNABLE_PER_CHANNEL_AFFINE")
    if self.dtype not in (torch.float16, torch.bfloat16, torch.float32, torch.float64):
        raise TypeError(
            f"unsupported dtype {self.dtype}; only floating-point dtypes are supported"
        )
    zero_point_rounded = _prepare_zero_point(zero_point, quant_min, quant_max)
    return _fake_quantize_learnable_per_channel_affine_inner(
        self, scale, zero_point_rounded, axis, quant_min, quant_max
    )


def _fake_quantize_learnable_per_channel_affine_out_impl(
    self,
    scale,
    zero_point,
    axis,
    quant_min,
    quant_max,
    grad_factor=1.0,
    *,
    out=None,
):
    logger.debug("GEMS FAKE_QUANTIZE_LEARNABLE_PER_CHANNEL_AFFINE_OUT")
    zero_point_rounded = _prepare_zero_point(zero_point, quant_min, quant_max)
    return _fake_quantize_learnable_per_channel_affine_inner(
        self, scale, zero_point_rounded, axis, quant_min, quant_max, out=out
    )
