# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import math

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def _next_power_of_2(n: int) -> int:
    p = 1
    while p < n:
        p *= 2
    return p


@libentry()
@triton.jit
def _mha_attention_kernel(
    Q,
    K,
    V,
    Mask,
    Out,
    Weights,
    scale,
    T,
    D,
    DH,
    NH,
    NEED_WEIGHTS: tl.constexpr,
    HAS_MASK: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    # Each program handles a block of query positions for a single (batch, head)
    # pair. Q/K/V are stored in [B, T, D] contiguous layout; the head dimension
    # is split contiguously as head = d // DH, dim = d % DH.
    pid_bh = tl.program_id(0)
    pid_m = tl.program_id(1)

    b = pid_bh // NH
    h = pid_bh % NH
    head_offset = h * DH

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = tl.arange(0, BLOCK_N)
    offs_d = tl.arange(0, BLOCK_D)

    # Load the query block [BLOCK_M, BLOCK_D].
    q_ptrs = Q + b * (T * D) + offs_m[:, None] * D + head_offset + offs_d[None, :]
    q_mask = (offs_m[:, None] < T) & (offs_d[None, :] < DH)
    q = tl.load(q_ptrs, mask=q_mask, other=0.0)

    # Online softmax over the key dimension.
    m_i = tl.full([BLOCK_M], float("-inf"), dtype=tl.float32)
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc = tl.zeros([BLOCK_M, BLOCK_D], dtype=tl.float32)

    for start_n in range(0, T, BLOCK_N):
        n_offsets = start_n + offs_n

        # Key block [BLOCK_D, BLOCK_N].
        k_ptrs = (
            K + b * (T * D) + n_offsets[None, :] * D + head_offset + offs_d[:, None]
        )
        k_mask = (n_offsets[None, :] < T) & (offs_d[:, None] < DH)
        k = tl.load(k_ptrs, mask=k_mask, other=0.0)

        # Value block [BLOCK_N, BLOCK_D].
        v_ptrs = (
            V + b * (T * D) + n_offsets[:, None] * D + head_offset + offs_d[None, :]
        )
        v_mask = (n_offsets[:, None] < T) & (offs_d[None, :] < DH)
        v = tl.load(v_ptrs, mask=v_mask, other=0.0)

        qk = tl.dot(q, k, allow_tf32=False) * scale

        if HAS_MASK:
            mask_ptrs = (
                Mask + pid_bh * (T * T) + offs_m[:, None] * T + n_offsets[None, :]
            )
            mask_vals = tl.load(
                mask_ptrs,
                mask=(offs_m[:, None] < T) & (n_offsets[None, :] < T),
                other=0,
            )
            qk = tl.where(mask_vals == 1, float("-inf"), qk)

        # Mask out padding columns beyond T.
        qk = tl.where(n_offsets[None, :] < T, qk, float("-inf"))

        m_ij = tl.maximum(m_i, tl.max(qk, 1))
        p = tl.where(qk == float("-inf"), 0.0, tl.exp(qk - m_ij[:, None]))
        correction = tl.where(m_i == float("-inf"), 0.0, tl.exp(m_i - m_ij))
        l_i = l_i * correction + tl.sum(p, 1)
        acc = acc * correction[:, None] + tl.dot(p.to(v.dtype), v, allow_tf32=False)
        m_i = m_ij

    acc = acc / l_i[:, None]

    # Store attention context directly into the [B, T, D] output layout.
    o_ptrs = Out + b * (T * D) + offs_m[:, None] * D + head_offset + offs_d[None, :]
    tl.store(o_ptrs, acc.to(Out.dtype.element_ty), mask=q_mask)

    # Materialize the softmax weights if requested.
    if NEED_WEIGHTS:
        for start_n in range(0, T, BLOCK_N):
            n_offsets = start_n + offs_n
            k_ptrs = (
                K + b * (T * D) + n_offsets[None, :] * D + head_offset + offs_d[:, None]
            )
            k_mask = (n_offsets[None, :] < T) & (offs_d[:, None] < DH)
            k = tl.load(k_ptrs, mask=k_mask, other=0.0)

            qk = tl.dot(q, k, allow_tf32=False) * scale

            if HAS_MASK:
                mask_ptrs = (
                    Mask + pid_bh * (T * T) + offs_m[:, None] * T + n_offsets[None, :]
                )
                mask_vals = tl.load(
                    mask_ptrs,
                    mask=(offs_m[:, None] < T) & (n_offsets[None, :] < T),
                    other=0,
                )
                qk = tl.where(mask_vals == 1, float("-inf"), qk)

            qk = tl.where(n_offsets[None, :] < T, qk, float("-inf"))
            p = tl.where(
                qk == float("-inf"), 0.0, tl.exp(qk - m_i[:, None]) / l_i[:, None]
            )

            w_ptrs = (
                Weights + pid_bh * (T * T) + offs_m[:, None] * T + n_offsets[None, :]
            )
            w_mask = (offs_m[:, None] < T) & (n_offsets[None, :] < T)
            tl.store(w_ptrs, p.to(Weights.dtype.element_ty), mask=w_mask)


@libentry()
@triton.jit
def _mha_attention_materialized_kernel(
    Q,
    K,
    V,
    Mask,
    Out,
    Weights,
    scale,
    T,
    D,
    DH,
    NH,
    HAS_MASK: tl.constexpr,
    TRANSPOSE_K: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    # Small/medium sequence specialization for need_weights=True. The complete
    # key dimension fits in one program, so QK is computed only once and the
    # normalized probabilities are both written to Weights and consumed
    # directly by P @ V, instead of recomputing QK in a second pass.
    pid_bh = tl.program_id(0)
    pid_m = tl.program_id(1)

    b = pid_bh // NH
    h = pid_bh % NH
    head_offset = h * DH

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = tl.arange(0, BLOCK_N)
    offs_d = tl.arange(0, BLOCK_D)

    m_mask = offs_m < T
    n_mask = offs_n < T
    d_mask = offs_d < DH

    q_ptrs = Q + b * (T * D) + offs_m[:, None] * D + head_offset + offs_d[None, :]
    q = tl.load(q_ptrs, mask=m_mask[:, None] & d_mask[None, :], other=0.0)

    if TRANSPOSE_K:
        # Coalesced [BLOCK_N, BLOCK_D] load, transposed in registers.
        k_t = tl.load(
            K + b * (T * D) + offs_n[:, None] * D + head_offset + offs_d[None, :],
            mask=n_mask[:, None] & d_mask[None, :],
            other=0.0,
        )
        k = tl.trans(k_t)
    else:
        # [BLOCK_D, BLOCK_N] load with stride-D columns.
        k_ptrs = K + b * (T * D) + offs_n[None, :] * D + head_offset + offs_d[:, None]
        k = tl.load(k_ptrs, mask=d_mask[:, None] & n_mask[None, :], other=0.0)

    qk = tl.dot(q, k, allow_tf32=False) * scale

    if HAS_MASK:
        mask_ptrs = Mask + pid_bh * (T * T) + offs_m[:, None] * T + offs_n[None, :]
        mask_vals = tl.load(
            mask_ptrs,
            mask=m_mask[:, None] & n_mask[None, :],
            other=0,
        )
        qk = tl.where(mask_vals == 1, float("-inf"), qk)

    # Mask out padding columns beyond T.
    qk = tl.where(n_mask[None, :], qk, float("-inf"))

    # Full-row softmax: no online/recompute pass required.
    m_i = tl.max(qk, 1)
    p = tl.where(qk == float("-inf"), 0.0, tl.exp(qk - m_i[:, None]))
    l_i = tl.sum(p, 1)
    p = p / l_i[:, None]

    # Store the attention weights immediately.
    w_ptrs = Weights + pid_bh * (T * T) + offs_m[:, None] * T + offs_n[None, :]
    tl.store(
        w_ptrs,
        p.to(Weights.dtype.element_ty),
        mask=m_mask[:, None] & n_mask[None, :],
    )

    # Value block [BLOCK_N, BLOCK_D].
    v_ptrs = V + b * (T * D) + offs_n[:, None] * D + head_offset + offs_d[None, :]
    v = tl.load(v_ptrs, mask=n_mask[:, None] & d_mask[None, :], other=0.0)

    acc = tl.dot(p.to(v.dtype), v, allow_tf32=False)

    o_ptrs = Out + b * (T * D) + offs_m[:, None] * D + head_offset + offs_d[None, :]
    tl.store(
        o_ptrs, acc.to(Out.dtype.element_ty), mask=m_mask[:, None] & d_mask[None, :]
    )


@libentry()
@triton.jit
def _mha_average_weights_kernel(
    Weights,
    Out,
    NH: tl.constexpr,
    T,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    # Reduce per-head attention weights [B * NH, T, T] down to the
    # head-averaged [B, T, T] layout (sum over heads followed by division by
    # NH). The grid tiles the full [T, T] output so enough programs are
    # launched to keep the device busy even for small batch sizes; each
    # program loops over the NH heads for its own tile.
    pid_b = tl.program_id(0)
    pid_mn = tl.program_id(1)
    num_n = tl.cdiv(T, BLOCK_N)
    pid_m = pid_mn // num_n
    pid_n = pid_mn % num_n
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)

    acc = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
    mask = (offs_m[:, None] < T) & (offs_n[None, :] < T)
    for h in range(NH):
        w_ptrs = (
            Weights + (pid_b * NH + h) * (T * T) + offs_m[:, None] * T + offs_n[None, :]
        )
        w = tl.load(w_ptrs, mask=mask, other=0.0)
        acc += w.to(tl.float32)
    acc = acc * (1.0 / NH)
    o_ptrs = Out + pid_b * (T * T) + offs_m[:, None] * T + offs_n[None, :]
    tl.store(o_ptrs, acc.to(Out.dtype.element_ty), mask=mask)


@libentry()
@triton.jit
def _qkv_projection_kernel(
    Q,
    K,
    V,
    W,
    Bias,
    Out,
    M,
    D,
    SELF_ATTENTION: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    # Fused query/key/value input projection, parallelized over program_id(2).
    # Each program computes one [BLOCK_M, BLOCK_N] tile of one of the three
    # [M, D] @ [D, D] GEMMs, writing the results to three contiguous [M, D]
    # slabs of Out ([3 * M, D]). This replaces the previous per-CTA serial
    # loop over Q/K/V, which starved occupancy on small projections.
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    pid_qkv = tl.program_id(2)
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)
    mask_m = offs_m < M
    mask_n = offs_n < D

    if SELF_ATTENTION:
        inp = Q
    else:
        if pid_qkv == 0:
            inp = Q
        elif pid_qkv == 1:
            inp = K
        else:
            inp = V

    acc = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
    for k in range(0, D, BLOCK_K):
        k_offsets = k + offs_k
        in_ptrs = inp + offs_m[:, None] * D + k_offsets[None, :]
        in_mask = mask_m[:, None] & (k_offsets[None, :] < D)
        a = tl.load(in_ptrs, mask=in_mask, other=0.0)
        w_ptrs = W + pid_qkv * (D * D) + offs_n[None, :] * D + k_offsets[:, None]
        w_mask = (k_offsets[:, None] < D) & mask_n[None, :]
        b = tl.load(w_ptrs, mask=w_mask, other=0.0)
        acc += tl.dot(a, b, allow_tf32=False)
    bias_ptrs = Bias + pid_qkv * D + offs_n
    bias = tl.load(bias_ptrs, mask=mask_n, other=0.0)
    acc = acc + bias[None, :]
    out_ptrs = Out + pid_qkv * (M * D) + offs_m[:, None] * D + offs_n[None, :]
    out_mask = mask_m[:, None] & mask_n[None, :]
    tl.store(out_ptrs, acc.to(Out.dtype.element_ty), mask=out_mask)


@libentry()
@triton.jit
def _out_projection_kernel(
    Input,
    W,
    Bias,
    Out,
    M,
    D,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    # Output projection y = x @ W^T + b with x in [M, D], W in [D, D].
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)
    mask_m = offs_m < M
    mask_n = offs_n < D

    acc = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
    for k in range(0, D, BLOCK_K):
        k_offsets = k + offs_k
        in_ptrs = Input + offs_m[:, None] * D + k_offsets[None, :]
        in_mask = mask_m[:, None] & (k_offsets[None, :] < D)
        a = tl.load(in_ptrs, mask=in_mask, other=0.0)
        w_ptrs = W + offs_n[None, :] * D + k_offsets[:, None]
        w_mask = (k_offsets[:, None] < D) & mask_n[None, :]
        b = tl.load(w_ptrs, mask=w_mask, other=0.0)
        acc += tl.dot(a, b, allow_tf32=False)
    bias_ptrs = Bias + offs_n
    bias = tl.load(bias_ptrs, mask=mask_n, other=0.0)
    acc = acc + bias[None, :]
    out_ptrs = Out + offs_m[:, None] * D + offs_n[None, :]
    out_mask = mask_m[:, None] & mask_n[None, :]
    tl.store(out_ptrs, acc.to(Out.dtype.element_ty), mask=out_mask)


def _native_multi_head_attention(
    query: Tensor,
    key: Tensor,
    value: Tensor,
    embed_dim: int,
    num_head: int,
    qkv_weight: Tensor,
    qkv_bias: Tensor,
    proj_weight: Tensor,
    proj_bias: Tensor,
    mask: Tensor = None,
    need_weights: bool = True,
    average_attn_weights: bool = True,
    mask_type=None,
):
    """Native multi-head attention forward.

    Args:
        query, key, value: tensors of shape [B, T, D] where B is the batch-like
            leading dimension, T is the sequence length and D == embed_dim.
        embed_dim: total embedding dimension (D).
        num_head: number of attention heads.
        qkv_weight: combined input projection weight of shape [3 * D, D].
        qkv_bias: combined input projection bias of shape [3 * D].
        proj_weight: output projection weight of shape [D, D].
        proj_bias: output projection bias of shape [D].
        mask: optional boolean attention mask.
        need_weights: whether to return attention weights.
        average_attn_weights: average attention weights over heads if True.
        mask_type: 0 (src mask, [T, T]), 1 (key padding mask, [B, T]) or
            2 (generic mask broadcastable to [B, num_head, T, T]).

    Returns:
        A tuple (attn_output, attn_output_weights). ``attn_output`` has shape
        [B, T, D]; ``attn_output_weights`` has shape [B, T, T] when averaged,
        [B, num_head, T, T] otherwise, or ``None`` when ``need_weights`` is False.
    """
    logger.debug("GEMS _NATIVE_MULTI_HEAD_ATTENTION")

    B, T, D = query.shape
    head_dim = D // num_head

    if query.numel() == 0:
        out = torch.empty_like(query)
        if need_weights:
            weights = torch.empty((B, T, T), dtype=query.dtype, device=query.device)
        else:
            weights = None
        return out, weights

    scale = 1.0 / math.sqrt(head_dim)

    M = B * T
    BLOCK_M = 64
    BLOCK_N = 64
    BLOCK_K = 64
    BLOCK_D = max(16, _next_power_of_2(head_dim))

    # qkv projection with bias: a single fused GEMM producing [3*B*T, D] with the
    # three projections laid out as contiguous [B*T, D] slabs. The Q/K/V groups
    # are parallelized over the third grid dimension; for self-attention all
    # three groups share the same input (the native MHA fast-path call pattern).
    qkv_out = torch.empty((3 * M, D), dtype=query.dtype, device=query.device)
    is_self_attention = query is key and key is value
    grid = (triton.cdiv(M, BLOCK_M), triton.cdiv(D, BLOCK_N), 3)
    with torch_device_fn.device(query.device):
        _qkv_projection_kernel[grid](
            query,
            key,
            value,
            qkv_weight.contiguous(),
            qkv_bias,
            qkv_out,
            M,
            D,
            SELF_ATTENTION=is_self_attention,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            BLOCK_K=BLOCK_K,
            num_warps=4,
        )
    q = qkv_out[0:M].view(B, T, D)
    k = qkv_out[M : 2 * M].view(B, T, D)
    v = qkv_out[2 * M : 3 * M].view(B, T, D)

    # Expand the boolean mask to [B, num_head, T, T] and flatten to [B*num_head, T, T].
    has_mask = mask is not None
    if has_mask:
        if mask_type == 0:
            mask4d = mask.unsqueeze(0).unsqueeze(0)
        elif mask_type == 1:
            mask4d = mask.unsqueeze(1).unsqueeze(1)
        else:
            mask4d = mask
            if mask4d.dim() == 2:
                mask4d = mask4d.unsqueeze(0).unsqueeze(0)
            elif mask4d.dim() == 3:
                mask4d = mask4d.unsqueeze(0)
        mask_bool = (
            mask4d.expand(B, num_head, T, T)
            .contiguous()
            .to(torch.bool)
            .reshape(B * num_head, T, T)
        )
        mask_int8 = mask_bool.to(torch.int8)
    else:
        mask_int8 = q

    out = torch.empty((B, T, D), dtype=query.dtype, device=query.device)
    if need_weights:
        weights = torch.empty(
            (B * num_head, T, T), dtype=query.dtype, device=query.device
        )
    else:
        weights = torch.empty((1,), dtype=query.dtype, device=query.device)

    # Materializing P is unavoidable when need_weights=True. For short/medium
    # sequences it is cheaper to keep the complete key dimension in one program
    # and compute QK only once; longer sequences use the streaming kernel.
    # For FP32 the full-key block is capped at T <= 128: with BLOCK_N=256 the
    # FMA-path dot blows up register usage and spills, which is slower than
    # the streaming two-pass kernel.
    if query.dtype in (torch.float16, torch.bfloat16):
        use_materialized_kernel = need_weights and T <= 256 and head_dim <= 64
    else:
        use_materialized_kernel = need_weights and T <= 128 and head_dim <= 64

    with torch_device_fn.device(query.device):
        if use_materialized_kernel:
            # Block/warp heuristic swept on H20 (78 SMs). Larger BLOCK_M
            # amortizes the full-key BLOCK_N load; TRANSPOSE_K only wins when
            # the head slice is wide enough for the coalesced load to pay off
            # for the QK dot.
            if head_dim <= 8:
                ATTN_BLOCK_M, ATTN_WARPS, TRANSPOSE_K = 64, 8, False
            elif head_dim <= 16:
                if T <= 128:
                    ATTN_BLOCK_M, ATTN_WARPS, TRANSPOSE_K = 64, 4, True
                else:
                    ATTN_BLOCK_M, ATTN_WARPS, TRANSPOSE_K = 32, 8, True
            else:
                ATTN_BLOCK_M, ATTN_WARPS, TRANSPOSE_K = 64, 8, False
            ATTN_BLOCK_N = max(16, _next_power_of_2(T))
            grid = (B * num_head, triton.cdiv(T, ATTN_BLOCK_M))
            _mha_attention_materialized_kernel[grid](
                q,
                k,
                v,
                mask_int8,
                out,
                weights,
                scale,
                T,
                D,
                head_dim,
                num_head,
                HAS_MASK=has_mask,
                TRANSPOSE_K=TRANSPOSE_K,
                BLOCK_M=ATTN_BLOCK_M,
                BLOCK_N=ATTN_BLOCK_N,
                BLOCK_D=BLOCK_D,
                num_warps=ATTN_WARPS,
            )
        else:
            grid = (B * num_head, triton.cdiv(T, BLOCK_M))
            _mha_attention_kernel[grid](
                q,
                k,
                v,
                mask_int8,
                out,
                weights,
                scale,
                T,
                D,
                head_dim,
                num_head,
                NEED_WEIGHTS=need_weights,
                HAS_MASK=has_mask,
                BLOCK_M=BLOCK_M,
                BLOCK_N=BLOCK_N,
                BLOCK_D=BLOCK_D,
                num_warps=4,
            )

    # Output projection.
    proj_out = torch.empty((M, D), dtype=query.dtype, device=query.device)
    grid = (triton.cdiv(M, BLOCK_M), triton.cdiv(D, BLOCK_N))
    with torch_device_fn.device(query.device):
        _out_projection_kernel[grid](
            out,
            proj_weight.contiguous(),
            proj_bias,
            proj_out,
            M,
            D,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            BLOCK_K=BLOCK_K,
            num_warps=4,
        )
    out = proj_out.view(B, T, D)

    if need_weights:
        if average_attn_weights:
            avg_weights = torch.empty((B, T, T), dtype=query.dtype, device=query.device)
            AVG_BLOCK_M = 16
            AVG_BLOCK_N = 64
            grid = (B, triton.cdiv(T, AVG_BLOCK_M) * triton.cdiv(T, AVG_BLOCK_N))
            with torch_device_fn.device(query.device):
                _mha_average_weights_kernel[grid](
                    weights,
                    avg_weights,
                    num_head,
                    T,
                    BLOCK_M=AVG_BLOCK_M,
                    BLOCK_N=AVG_BLOCK_N,
                    num_warps=4,
                )
            return out, avg_weights
        else:
            weights = weights.reshape(B, num_head, T, T)
            return out, weights
    else:
        return out, None
