# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


# _nested_tensor_from_mask_left_aligned: checks whether a 3D tensor `t` (N * L * D)
# combined with a 2D boolean padding mask (N * L) is left-aligned, i.e. the valid
# (True) elements of every row appear at the beginning with no gaps. This mirrors the
# PyTorch native implementation: for each row, the number of True elements must equal
# the index of the first False element (or L when the row is entirely True).
# Returns a plain Python bool.


@triton.jit
def reduce_all(a, b):
    return a and b


@libentry()
@triton.jit
def left_aligned_kernel(
    mask,
    mid,
    N,
    L,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    pid = ext.program_id(0)
    rows = pid * BLOCK_M + tl.arange(0, BLOCK_M)

    num_true = tl.zeros([BLOCK_M], dtype=tl.int32)
    first_false = tl.full([BLOCK_M], L, dtype=tl.int32)

    for off in range(0, L, BLOCK_N):
        cols = off + tl.arange(0, BLOCK_N)
        ptrs = mask + rows[:, None] * L + cols[None, :]
        mask_cond = (rows[:, None] < N) & (cols[None, :] < L)
        vals = tl.load(ptrs, mask=mask_cond, other=0).to(tl.int32)

        # Count True elements in each row.
        num_true += tl.sum(vals, axis=1)

        # Index of the first False element in each row (L if the row is all True).
        candidate = tl.where(vals == 0, cols[None, :], L)
        first_false = tl.minimum(first_false, tl.min(candidate, axis=1))

    left_aligned = (num_true == first_false).to(tl.int1)
    # Masked (out-of-range) rows are treated as True, the identity for logical AND.
    left_aligned = tl.where(rows < N, left_aligned, 1).to(tl.int1)

    all_val = tl.reduce(left_aligned, axis=0, combine_fn=reduce_all)
    tl.store(mid + pid, all_val)


@libentry()
@triton.jit
def reduce_all_kernel(mid, out, MID_SIZE, BLOCK_MID: tl.constexpr):
    offset = tl.arange(0, BLOCK_MID)
    ptrs = mid + offset
    mask_cond = offset < MID_SIZE
    vals = tl.load(ptrs, mask=mask_cond, other=1).to(tl.int1)
    all_val = tl.reduce(vals, axis=0, combine_fn=reduce_all)
    tl.store(out, all_val)


def _nested_tensor_from_mask_left_aligned(t, mask):
    logger.debug("GEMS _NESTED_TENSOR_FROM_MASK_LEFT_ALIGNED")

    if mask.dtype != torch.bool:
        raise RuntimeError(
            f"Expected mask to be of ScalarType Bool, but got {mask.dtype} instead."
        )
    if mask.dim() != 2:
        raise RuntimeError("Padding mask should be 2D")
    if t.dim() != 3:
        raise RuntimeError("Input should be a 3D tensor, N * L * D")

    N, L = t.size(0), t.size(1)
    NN, LL = mask.size(0), mask.size(1)
    if N != NN or L != LL:
        raise RuntimeError("Mask size should match input size")

    if N == 0 or L == 0:
        return True

    mask = mask.contiguous()
    BLOCK_M = 32
    BLOCK_N = 128
    mid_size = triton.cdiv(N, BLOCK_M)
    block_mid = triton.next_power_of_2(mid_size)

    mid = torch.empty((mid_size,), dtype=torch.bool, device=mask.device)
    out = torch.empty([], dtype=torch.bool, device=mask.device)

    with torch_device_fn.device(mask.device):
        left_aligned_kernel[(mid_size, 1)](
            mask, mid, N, L, BLOCK_M=BLOCK_M, BLOCK_N=BLOCK_N
        )
        reduce_all_kernel[(1, 1)](mid, out, mid_size, BLOCK_MID=block_mid)

    return bool(out.item())
