# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _nested_view_from_jagged(
    self: torch.Tensor,
    offsets: torch.Tensor,
    dummy: torch.Tensor,
    lengths: torch.Tensor | None = None,
    ragged_idx: int = 1,
    min_seqlen: torch.Tensor | None = None,
    max_seqlen: torch.Tensor | None = None,
):
    """Construct a jagged-layout nested tensor from a flat values buffer.

    ``self`` is the packed values buffer of shape ``(sum(lengths), D1, ..., DN)``,
    ``offsets`` describes how the packed jagged dimension is split into batch
    elements, and the optional ``lengths``/``min_seqlen``/``max_seqlen`` provide
    additional cached metadata.

    This is a pure view operation: it wraps ``self`` (and ``offsets``) into a
    :class:`torch.nested._internal.nested_tensor.NestedTensor` without copying
    any data. ``dummy`` is unused and only exists to match the ATen signature
    (it triggers nested-tensor dispatch in the eager path).

    Args:
        self (torch.Tensor): Packed values buffer of shape ``(sum_B(*), ...)``.
        offsets (torch.Tensor): 1-D tensor of shape ``(batch_size + 1,)`` with
            the start/end indices of each batch element along the jagged dim.
        dummy (torch.Tensor): Unused; kept for ATen signature compatibility.
        lengths (torch.Tensor | None): Optional per-batch lengths of shape
            ``(batch_size,)``. Defaults to ``None``.
        ragged_idx (int): Position of the ragged dimension in the returned
            nested tensor (must be >= 1). Defaults to 1.
        min_seqlen (torch.Tensor | None): Optional cached minimum sequence
            length (stored as a ``(val, 0)`` shaped tensor).
        max_seqlen (torch.Tensor | None): Optional cached maximum sequence
            length (stored as a ``(val, 0)`` shaped tensor).

    Returns:
        torch.Tensor: A jagged-layout nested tensor that is a view of ``self``.
    """
    logger.debug("GEMS _NESTED_VIEW_FROM_JAGGED")

    from torch.nested._internal.nested_tensor import NestedTensor

    metadata_cache = {}
    if min_seqlen is not None:
        metadata_cache["min_seqlen"] = min_seqlen
    if max_seqlen is not None:
        metadata_cache["max_seqlen"] = max_seqlen

    return NestedTensor(
        self,
        offsets,
        lengths=lengths,
        _ragged_idx=ragged_idx,
        _metadata_cache=metadata_cache,
    )
