# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from torch.utils.weak import WeakTensorKeyDictionary

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)

# ``offsets`` is nested-tensor metadata that is commonly reused across many
# ``_nested_from_padded_tensor`` calls (e.g. the same ragged layout across
# iterations). Reading ``offsets[-1]`` to size the packed output forces a
# device -> host sync the first time we see a given offsets tensor; cache the
# resolved total length ``S`` keyed by the offsets tensor so repeated calls on
# an unchanged offsets avoid the sync. The cache is invalidated via the
# tensor's version counter -- any in-place mutation of ``offsets`` bumps
# ``_version`` and the next call re-syncs. Inference tensors do not expose a
# version counter, so they fall back to the always-correct synced path.
_SUM_S_CACHE: WeakTensorKeyDictionary = WeakTensorKeyDictionary()


def _resolve_sum_s(offsets):
    """Return the total packed length ``S = offsets[-1]`` with cache reuse."""
    try:
        version = offsets._version
    except RuntimeError:
        # Inference tensors do not track a version counter.
        return int(offsets[-1].item())

    cached = _SUM_S_CACHE.get(offsets)
    if cached is not None and cached[0] == version:
        return cached[1]

    S = int(offsets[-1].item())
    _SUM_S_CACHE[offsets] = (version, S)
    return S


@libentry()
@triton.jit
def _nested_from_padded_tensor_kernel(
    padded,
    offsets,
    output,
    T: tl.constexpr,
    IB: tl.constexpr,
    IN: tl.constexpr,
    S,
    BLOCK_SIZE: tl.constexpr,
):
    """Pack a padded tensor into the flat `values` of a nested tensor.

    The padded tensor is viewed as ``[B, IB, T, IN]`` where ``B`` is the
    outermost batch dimension, ``T`` is the padded ragged dimension, ``IB`` is
    the product of the intermediate batch dimensions (between the outer batch
    dim and the ragged dim) and ``IN`` is the product of the inner dimensions
    following the ragged dim.  One program handles a single ``(b, ib)`` pair and
    copies the ``length * IN`` contiguous real elements from
    ``padded[b, ib, 0:length]`` to ``output[ib, offsets[b] + 0:length]``.
    """
    pid = tle.program_id(axis=0)
    b = pid // IB
    ib = pid % IB

    start = tl.load(offsets + b)
    end = tl.load(offsets + b + 1)
    length = end - start

    total = length * IN
    src_base = pid * T * IN
    dst_base = (ib * S + start) * IN

    for i in tl.range(0, total, BLOCK_SIZE):
        offs = i + tl.arange(0, BLOCK_SIZE)
        mask = offs < total
        val = tl.load(padded + src_base + offs, mask=mask)
        tl.store(output + dst_base + offs, val, mask=mask)


def _nested_from_padded_tensor(
    padded,
    offsets,
    dummy,
    ragged_idx=1,
    min_seqlen=None,
    max_seqlen=None,
    sum_S=None,
):
    """Construct a nested tensor from a padded tensor and offsets.

    The data movement (packing the non-padding elements of ``padded`` into a
    flat values buffer) is performed by a Triton kernel, then the resulting
    values buffer is wrapped into a nested tensor view together with ``offsets``.
    """
    logger.debug("GEMS _NESTED_FROM_PADDED_TENSOR")

    padded = padded.contiguous()
    shape = padded.shape

    B = shape[0]
    T = shape[ragged_idx]

    # Product of intermediate batch dims (between the outer batch dim and the
    # ragged dim) and product of the inner dims following the ragged dim.
    IB = 1
    for d in shape[1:ragged_idx]:
        IB *= d
    IN = 1
    for d in shape[ragged_idx + 1 :]:
        IN *= d

    # Total number of real (non-padding) elements along the ragged dimension.
    # Prefer the caller-provided sum_S to avoid a device -> host sync; otherwise
    # resolve S from offsets with a version-aware cache so repeated calls on an
    # unchanged offsets reuse the previously synced value.
    if sum_S is not None:
        S = int(sum_S)
    else:
        S = _resolve_sum_s(offsets)

    # The packed values keep every padded dim except the outermost one, with the
    # ragged dim replaced by the total number of real elements S.
    values_shape = list(shape[1:])
    values_shape[ragged_idx - 1] = S
    values = torch.empty(values_shape, dtype=padded.dtype, device=padded.device)

    grid = lambda meta: (B * IB,)
    _nested_from_padded_tensor_kernel[grid](
        padded,
        offsets,
        values,
        T,
        IB,
        IN,
        S,
        # BLOCK_SIZE is the per-program vectorization width (elements per
        # loop iteration), not the thread count; warp count comes from the
        # kernel launch (num_warps). 1024 elements per iteration saturates
        # memory bandwidth for this elementwise un-padding copy, so no
        # autotune is needed.
        BLOCK_SIZE=1024,
    )

    return torch._nested_view_from_jagged(
        values, offsets, dummy, None, ragged_idx, min_seqlen, max_seqlen
    )


__all__ = ["_nested_from_padded_tensor"]
