# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops._nested_view_from_jagged import _nested_view_from_jagged
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

_BLOCK_SIZE = 1024


@libentry()
@triton.jit
def _nested_view_from_jagged_copy_kernel(
    src_ptr,
    dst_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    vals = tl.load(src_ptr + offsets, mask=mask)
    tl.store(dst_ptr + offsets, vals, mask=mask)


def _nested_view_from_jagged_copy(
    self: torch.Tensor,
    offsets: torch.Tensor,
    dummy: torch.Tensor,
    lengths=None,
    ragged_idx=1,
    min_seqlen=None,
    max_seqlen=None,
):
    """Constructs a jagged-layout nested tensor from a flat buffer `self`,
    splitting the packed jagged dimension into batch elements according to
    `offsets` / `lengths`. The `_copy` variant owns a fresh copy of the buffer,
    which is produced here by a Triton kernel before building the nested view."""
    logger.debug("GEMS _NESTED_VIEW_FROM_JAGGED_COPY")

    src = self.contiguous() if not self.is_contiguous() else self
    values_copy = torch.empty_like(src)
    n_elements = values_copy.numel()

    if n_elements > 0:
        grid = (triton.cdiv(n_elements, _BLOCK_SIZE),)
        _nested_view_from_jagged_copy_kernel[grid](
            src,
            values_copy,
            n_elements,
            BLOCK_SIZE=_BLOCK_SIZE,
        )

    return _nested_view_from_jagged(
        values_copy,
        offsets,
        dummy,
        lengths,
        ragged_idx,
        min_seqlen,
        max_seqlen,
    )
