# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("sparse_semi_structured_addmm"),
    key=["M", "N", "K4"],
)
@triton.jit
def sparse_semi_structured_addmm_kernel(
    input_tensor,  # input: (M, N)
    mat1,  # mat1: (M, 4*K4)
    Meta,  # Meta: (M, K4)
    mat2,  # mat2: (4*K4, N)
    output,  # output: (M, N)
    M,
    N,
    K4,
    alpha,
    beta,
    stride_im,
    stride_in,
    stride_am,
    stride_ak,
    stride_mm,
    stride_mn,
    stride_bk,
    stride_bn,
    stride_om,
    stride_on,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
):
    """
    Kernel for sparse semi-structured addmm operation.

    Computes: output = alpha * (mat1 @ sparse(Meta) @ mat2) + beta * input

    input_tensor: (M, N) - input matrix
    mat1: (M, 4*K4) - dense matrix with 2:4 sparsity pattern
    Meta: (M, K4) - boolean mask indicating which 2 elements in each group of 4 are valid
    mat2: (4*K4, N) - dense matrix
    output: (M, N) - output matrix

    For each group of 4 elements in mat1's K dimension:
    - Meta[i, k] = True: use mat1[i, 4k] and mat1[i, 4k+1]
    - Meta[i, k] = False: use mat1[i, 4k+2] and mat1[i, 4k+3]
    """
    pid = tl.program_id(0)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)

    # Combine pid_m and pid_n into a single pid
    pid_m = pid // num_pid_n
    pid_n = pid % num_pid_n

    offs_am = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_bn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    # Calculate the actual K dimension
    K = K4 * 4

    # Initialize accumulator for sparse mm
    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)

    num_iters = tl.cdiv(K4, BLOCK_SIZE_K)

    # Loop over K dimension in blocks
    for k in range(num_iters):
        k_offset = k * BLOCK_SIZE_K

        # Load meta for this K block
        meta_ptrs = Meta + (
            offs_am[:, None] * stride_mm + (offs_k + k_offset)[None, :] * stride_mn
        )
        # Create a 2D mask: (BLOCK_SIZE_M, BLOCK_SIZE_K)
        mask_2d = offs_am[:, None] < M
        mask_2d = mask_2d & ((offs_k + k_offset)[None, :] < K4)

        meta = tl.load(meta_ptrs, mask=mask_2d, other=0)

        # Load all 4 mat1 elements for each K position
        # A0: elements at positions 4k
        a0_ptrs = mat1 + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 0)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 0)[None, :] < K)
        a0 = tl.load(a0_ptrs, mask=mask_a, other=0.0)

        # A1: elements at positions 4k+1
        a1_ptrs = mat1 + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 1)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 1)[None, :] < K)
        a1 = tl.load(a1_ptrs, mask=mask_a, other=0.0)

        # A2: elements at positions 4k+2
        a2_ptrs = mat1 + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 2)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 2)[None, :] < K)
        a2 = tl.load(a2_ptrs, mask=mask_a, other=0.0)

        # A3: elements at positions 4k+3
        a3_ptrs = mat1 + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 3)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 3)[None, :] < K)
        a3 = tl.load(a3_ptrs, mask=mask_a, other=0.0)

        # Load mat2 elements similarly
        # B0: elements at positions 4k
        b0_ptrs = mat2 + (
            (offs_k * 4 + k_offset * 4 + 0)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 0)[:, None] < K) & (offs_bn[None, :] < N)
        b0 = tl.load(b0_ptrs, mask=mask_b, other=0.0)

        b1_ptrs = mat2 + (
            (offs_k * 4 + k_offset * 4 + 1)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 1)[:, None] < K) & (offs_bn[None, :] < N)
        b1 = tl.load(b1_ptrs, mask=mask_b, other=0.0)

        b2_ptrs = mat2 + (
            (offs_k * 4 + k_offset * 4 + 2)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 2)[:, None] < K) & (offs_bn[None, :] < N)
        b2 = tl.load(b2_ptrs, mask=mask_b, other=0.0)

        b3_ptrs = mat2 + (
            (offs_k * 4 + k_offset * 4 + 3)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 3)[:, None] < K) & (offs_bn[None, :] < N)
        b3 = tl.load(b3_ptrs, mask=mask_b, other=0.0)

        # Expand meta for computation
        meta_exp = meta[:, :, None]  # (BM, BK, 1)

        # Compute products per K position
        prod00_exp = a0[:, :, None] * b0[None, :, :]
        prod01_exp = a1[:, :, None] * b1[None, :, :]
        prod02_exp = a2[:, :, None] * b2[None, :, :]
        prod03_exp = a3[:, :, None] * b3[None, :, :]

        # Apply meta mask and sum over K
        selected = (prod00_exp + prod01_exp) * meta_exp + (prod02_exp + prod03_exp) * (
            1 - meta_exp
        )
        accumulator += tl.sum(selected, axis=1)

    # Load input tensor and apply alpha/beta
    input_ptrs = (
        input_tensor + stride_im * offs_am[:, None] + stride_in * offs_bn[None, :]
    )
    input_mask = (offs_am[:, None] < M) & (offs_bn[None, :] < N)
    input_vals = tl.load(input_ptrs, mask=input_mask, other=0.0)

    # Apply alpha and beta scaling
    accumulator = accumulator * alpha
    result = accumulator + input_vals * beta

    # Store result
    c_ptrs = output + stride_om * offs_am[:, None] + stride_on * offs_bn[None, :]
    c_mask = (offs_am[:, None] < M) & (offs_bn[None, :] < N)
    tl.store(c_ptrs, result, mask=c_mask)


def _sparse_semi_structured_addmm(
    input_tensor: torch.Tensor,
    mat1: torch.Tensor,
    mat1_meta: torch.Tensor,
    mat2: torch.Tensor,
    *,
    alpha: float = 1.0,
    beta: float = 1.0,
    out_dtype: Optional[torch.dtype] = None,
) -> torch.Tensor:
    """
    Performs a sparse semi-structured addmm operation.

    Computes: result = alpha * (mat1 @ sparse(mat1_meta) @ mat2) + beta * input_tensor

    Args:
        input_tensor: Input tensor of shape (M, N)
        mat1: Dense matrix of shape (M, 4*K) with 2:4 sparsity pattern
        mat1_meta: Boolean mask of shape (M, K) indicating which elements are valid
        mat2: Dense matrix of shape (4*K, N)
        alpha: Scaling factor for the matmul result
        beta: Scaling factor for the input tensor
        out_dtype: Optional output dtype

    Returns:
        Matrix of shape (M, N)
    """
    logger.debug("GEMS SPARSE_SEMI_STRUCTURED_ADDMM")

    M = mat1.shape[0]
    K4 = mat1_meta.shape[1]
    N = mat2.shape[1]

    # Validate shapes
    assert mat1.shape == (
        M,
        4 * K4,
    ), f"Expected mat1 shape ({M}, {4 * K4}), got {mat1.shape}"
    assert mat2.shape == (
        4 * K4,
        N,
    ), f"Expected mat2 shape ({4 * K4}, {N}), got {mat2.shape}"
    assert mat1_meta.shape == (
        M,
        K4,
    ), f"Expected mat1_meta shape ({M}, {K4}), got {mat1_meta.shape}"
    assert input_tensor.shape == (
        M,
        N,
    ), f"Expected input_tensor shape ({M}, {N}), got {input_tensor.shape}"

    # Determine output dtype
    if out_dtype is not None:
        output_dtype = out_dtype
    else:
        output_dtype = mat1.dtype

    out = torch.empty((M, N), device=mat1.device, dtype=output_dtype)

    grid = lambda META: (
        triton.cdiv(M, META["BLOCK_SIZE_M"]) * triton.cdiv(N, META["BLOCK_SIZE_N"]),
    )

    with torch_device_fn.device(mat1.device):
        sparse_semi_structured_addmm_kernel[grid](
            input_tensor,
            mat1,
            mat1_meta,
            mat2,
            out,
            M,
            N,
            K4,
            alpha,
            beta,
            input_tensor.stride(0),
            input_tensor.stride(1),
            mat1.stride(0),
            mat1.stride(1),
            mat1_meta.stride(0),
            mat1_meta.stride(1),
            mat2.stride(0),
            mat2.stride(1),
            out.stride(0),
            out.stride(1),
        )

    return out
