# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def conv_transpose3d_output_size(
    in_size: int,
    kernel_size: int,
    stride: int,
    padding: int,
    output_padding: int,
    dilation: int,
) -> int:
    """
    Determines the output size along one spatial dimension of a 3D transposed
    convolution operation.
    """
    return (
        (in_size - 1) * stride
        - 2 * padding
        + dilation * (kernel_size - 1)
        + output_padding
        + 1
    )


@libentry()
@triton.autotune(
    configs=[
        triton.Config(
            {"BLOCK_N_ODHW": block_n_odhw, "BLOCK_OC": block_oc, "BLOCK_IC": 32},
            num_warps=4,
            num_stages=2,
        )
        for block_n_odhw, block_oc in (
            (32, 32),
            (64, 32),
            (64, 64),
            (128, 32),
            (128, 64),
            (128, 128),
        )
    ],
    key=[
        "batch_size",
        "in_channels",
        "input_depth",
        "input_height",
        "input_width",
        "out_channels",
        "out_depth",
        "out_height",
        "out_width",
        "kernel_depth",
        "kernel_height",
        "kernel_width",
        "stride_depth",
        "stride_height",
        "stride_width",
        "groups",
    ],
)
@triton.jit
def conv_transpose3d_forward_kernel(
    input_pointer,
    weight_pointer,
    output_pointer,
    bias_pointer,
    batch_size,
    out_channels,
    out_depth,
    out_height,
    out_width,
    input_n_stride,
    input_c_stride,
    input_d_stride,
    input_h_stride,
    input_w_stride,
    weight_ic_stride,
    weight_oc_stride,
    weight_d_stride,
    weight_h_stride,
    weight_w_stride,
    output_n_stride,
    output_c_stride,
    output_d_stride,
    output_h_stride,
    output_w_stride,
    input_depth: tl.constexpr,
    input_height: tl.constexpr,
    input_width: tl.constexpr,
    in_channels: tl.constexpr,
    kernel_depth: tl.constexpr,
    kernel_height: tl.constexpr,
    kernel_width: tl.constexpr,
    stride_depth: tl.constexpr,
    stride_height: tl.constexpr,
    stride_width: tl.constexpr,
    padding_depth: tl.constexpr,
    padding_height: tl.constexpr,
    padding_width: tl.constexpr,
    dilation_depth: tl.constexpr,
    dilation_height: tl.constexpr,
    dilation_width: tl.constexpr,
    groups: tl.constexpr,
    BLOCK_N_ODHW: tl.constexpr,
    BLOCK_IC: tl.constexpr,
    BLOCK_OC: tl.constexpr,
):
    """
    Triton kernel for 3D transposed convolution forward pass.

    - input has shape (N, in_channels, iD, iH, iW)
    - weight has shape (in_channels, out_channels/groups, kD, kH, kW)
    - output has shape (N, out_channels, oD, oH, oW)

    For transposed convolution the relation between an output spatial position
    and the input position that contributes to it through kernel offset k is:
        o = i * stride - padding + k * dilation
    => i = (o + padding - k * dilation) / stride  (must be an integer index)
    """
    pid_n_odhw = tl.program_id(0)
    pid_oc = tl.program_id(1)
    pid_group = tl.program_id(2)

    # Decompose the flattened (batch, out_depth, out_height, out_width) index.
    n_odhw_offset = pid_n_odhw * BLOCK_N_ODHW + tl.arange(0, BLOCK_N_ODHW)
    ow_size = out_width
    oh_size = out_height
    od_size = out_depth
    out_w_idx = n_odhw_offset % ow_size
    tmp = n_odhw_offset // ow_size
    out_h_idx = tmp % oh_size
    tmp = tmp // oh_size
    out_d_idx = tmp % od_size
    batch_idx = tmp // od_size

    out_channels_per_group = out_channels // groups
    in_channels_per_group = in_channels
    oc_offset = pid_oc * BLOCK_OC + tl.arange(0, BLOCK_OC)

    accum = tl.zeros((BLOCK_N_ODHW, BLOCK_OC), dtype=tl.float32)

    input_base = (
        input_pointer
        + (input_n_stride * batch_idx)[:, None]
        + (input_c_stride * pid_group * in_channels_per_group)
    )
    weight_base = (
        weight_pointer
        + (weight_ic_stride * pid_group * in_channels_per_group)
        + (weight_oc_stride * oc_offset)[None, :]
    )

    BLOCK_IC_COUNT = (in_channels_per_group + BLOCK_IC - 1) // BLOCK_IC
    kernel_volume = kernel_depth * kernel_height * kernel_width
    for ic_kdhw in range(BLOCK_IC_COUNT * kernel_volume):
        ic_block = (ic_kdhw // kernel_volume) * BLOCK_IC
        k_flat = ic_kdhw % kernel_volume
        kw = k_flat % kernel_width
        kh = (k_flat // kernel_width) % kernel_height
        kd = k_flat // (kernel_width * kernel_height)

        ic_offset = ic_block + tl.arange(0, BLOCK_IC)

        # Map output positions back to input positions for this kernel offset.
        num_d = out_d_idx + padding_depth - kd * dilation_depth
        num_h = out_h_idx + padding_height - kh * dilation_height
        num_w = out_w_idx + padding_width - kw * dilation_width

        div_d = (num_d % stride_depth) == 0
        div_h = (num_h % stride_height) == 0
        div_w = (num_w % stride_width) == 0

        in_d_idx = num_d // stride_depth
        in_h_idx = num_h // stride_height
        in_w_idx = num_w // stride_width

        curr_input_pointer = (
            input_base
            + (input_c_stride * ic_offset)[None, :]
            + (input_d_stride * in_d_idx)[:, None]
            + (input_h_stride * in_h_idx)[:, None]
            + (input_w_stride * in_w_idx)[:, None]
        )
        input_mask = (
            (batch_idx < batch_size)[:, None]
            & (ic_offset < in_channels_per_group)[None, :]
            & (div_d & div_h & div_w)[:, None]
            & (in_d_idx >= 0)[:, None]
            & (in_d_idx < input_depth)[:, None]
            & (in_h_idx >= 0)[:, None]
            & (in_h_idx < input_height)[:, None]
            & (in_w_idx >= 0)[:, None]
            & (in_w_idx < input_width)[:, None]
        )
        input_block = tl.load(curr_input_pointer, mask=input_mask, other=0.0)

        curr_weight_pointer = (
            weight_base
            + (weight_ic_stride * ic_offset)[:, None]
            + (weight_d_stride * kd)
            + (weight_h_stride * kh)
            + (weight_w_stride * kw)
        )
        weight_mask = (ic_offset < in_channels_per_group)[:, None] & (
            oc_offset < out_channels_per_group
        )[None, :]
        weight_block = tl.load(curr_weight_pointer, mask=weight_mask, other=0.0)

        accum += tl.dot(
            input_block.to(tl.float32), weight_block.to(tl.float32), allow_tf32=False
        )

    bias_ptr = bias_pointer + pid_group * out_channels_per_group + oc_offset
    bias_mask = oc_offset < out_channels_per_group
    bias = tl.load(bias_ptr, mask=bias_mask, other=0.0).to(tl.float32)
    accum += bias[None, :]

    output_ptr = (
        output_pointer
        + (output_n_stride * batch_idx)[:, None]
        + (output_c_stride * (pid_group * out_channels_per_group + oc_offset))[None, :]
        + (output_d_stride * out_d_idx)[:, None]
        + (output_h_stride * out_h_idx)[:, None]
        + (output_w_stride * out_w_idx)[:, None]
    )
    output_mask = (
        (batch_idx < batch_size)[:, None]
        & (oc_offset < out_channels_per_group)[None, :]
        & (out_d_idx < out_depth)[:, None]
        & (out_h_idx < out_height)[:, None]
        & (out_w_idx < out_width)[:, None]
    )
    tl.store(output_ptr, accum, mask=output_mask)


def _triple(value):
    if isinstance(value, (list, tuple)):
        assert len(value) == 3, "expected a single int or a tuple of three ints"
        return int(value[0]), int(value[1]), int(value[2])
    return int(value), int(value), int(value)


def conv_transpose3d(
    input,
    weight,
    bias=None,
    stride=1,
    padding=0,
    output_padding=0,
    groups=1,
    dilation=1,
):
    """
    Applies a 3D transposed convolution operator over an input volume.

    Args:
        input: Input tensor of shape (N, in_channels, iD, iH, iW)
        weight: Filters of shape (in_channels, out_channels/groups, kD, kH, kW)
        bias: Optional bias of shape (out_channels). Default: None
        stride: Stride of the convolution. Default: 1
        padding: Zero-padding added to both sides. Default: 0
        output_padding: Additional size added to output shape. Default: 0
        groups: Number of blocked connections. Default: 1
        dilation: Spacing between kernel elements. Default: 1

    Returns:
        Output tensor of shape (N, out_channels, oD, oH, oW)
    """
    logger.debug("GEMS CONV_TRANSPOSE3D")

    assert input.ndim == 5, f"Input must be 5D, received shape {input.shape}"
    assert weight.ndim == 5, f"Weights must be 5D, received shape {weight.shape}"
    assert (
        bias is None or bias.ndim == 1
    ), f"Bias must be 1D, received shape {bias.shape}"

    stride_depth, stride_height, stride_width = _triple(stride)
    padding_depth, padding_height, padding_width = _triple(padding)
    (
        output_padding_depth,
        output_padding_height,
        output_padding_width,
    ) = _triple(output_padding)
    dilation_depth, dilation_height, dilation_width = _triple(dilation)

    batch_size, in_channels, input_depth, input_height, input_width = input.shape
    (
        in_channels_weight,
        out_channels_per_group,
        kernel_depth,
        kernel_height,
        kernel_width,
    ) = weight.shape

    assert (
        in_channels == in_channels_weight
    ), f"Input channels ({in_channels}) must match weight in_channels ({in_channels_weight})"
    assert (
        in_channels % groups == 0
    ), f"in_channels ({in_channels}) must be divisible by groups ({groups})"

    out_channels = out_channels_per_group * groups

    assert (
        bias is None or bias.shape[0] == out_channels
    ), f"Bias shape ({bias.shape}) doesn't match out_channels ({out_channels})"

    out_depth = conv_transpose3d_output_size(
        input_depth,
        kernel_depth,
        stride_depth,
        padding_depth,
        output_padding_depth,
        dilation_depth,
    )
    out_height = conv_transpose3d_output_size(
        input_height,
        kernel_height,
        stride_height,
        padding_height,
        output_padding_height,
        dilation_height,
    )
    out_width = conv_transpose3d_output_size(
        input_width,
        kernel_width,
        stride_width,
        padding_width,
        output_padding_width,
        dilation_width,
    )

    output_dtype = input.dtype
    output = torch.empty(
        (batch_size, out_channels, out_depth, out_height, out_width),
        device=input.device,
        dtype=output_dtype,
    )

    grid = lambda META: (
        triton.cdiv(
            batch_size * out_depth * out_height * out_width, META["BLOCK_N_ODHW"]
        ),
        triton.cdiv(out_channels_per_group, META["BLOCK_OC"]),
        groups,
    )

    if bias is None:
        bias_pointer = torch.zeros(
            out_channels, device=input.device, dtype=output_dtype
        )
    else:
        bias_pointer = bias

    input_contig = input.contiguous()
    weight_contig = weight.contiguous()

    in_channels_per_group = in_channels // groups

    conv_transpose3d_forward_kernel[grid](
        input_contig,
        weight_contig,
        output,
        bias_pointer,
        batch_size,
        out_channels,
        out_depth,
        out_height,
        out_width,
        *input_contig.stride(),
        *weight_contig.stride(),
        *output.stride(),
        input_depth,
        input_height,
        input_width,
        in_channels_per_group,
        kernel_depth,
        kernel_height,
        kernel_width,
        stride_depth,
        stride_height,
        stride_width,
        padding_depth,
        padding_height,
        padding_width,
        dilation_depth,
        dilation_height,
        dilation_width,
        groups=groups,
    )

    return output
