# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=[
        triton.Config(
            {"BLOCK_M": bm, "BLOCK_N": bn, "BLOCK_K": bk},
            num_stages=s,
            num_warps=w,
        )
        for bm, bn, bk, s, w in [
            (32, 32, 32, 2, 4),
            (64, 64, 32, 2, 4),
            (64, 64, 32, 3, 8),
            (128, 64, 32, 3, 8),
            (64, 128, 32, 3, 8),
            (128, 128, 32, 3, 8),
            (128, 128, 64, 3, 8),
        ]
    ],
    key=["M", "N", "K"],
)
@triton.jit
def _matmul_kernel(
    A,
    B,
    C,
    M,
    N,
    K,
    stride_am,
    stride_ak,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    a_ptrs = A + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak
    b_ptrs = B + offs_k[:, None] * stride_bk + offs_n[None, :] * stride_bn

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for k in range(0, K, BLOCK_K):
        k_mask = offs_k[None, :] < K - k
        # Keep operands in their native dtype so fp16/bf16 inputs use tensor
        # cores (fp32 accumulation) while fp32 inputs stay IEEE-accurate.
        a = tl.load(
            a_ptrs,
            mask=(offs_m[:, None] < M) & k_mask,
            other=0.0,
        )
        b = tl.load(
            b_ptrs,
            mask=(offs_k[:, None] < K - k) & (offs_n[None, :] < N),
            other=0.0,
        )
        acc += tl.dot(a, b, allow_tf32=False)
        a_ptrs += BLOCK_K * stride_ak
        b_ptrs += BLOCK_K * stride_bk

    c_ptrs = C + offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn
    c_mask = (offs_m[:, None] < M) & (offs_n[None, :] < N)
    tl.store(c_ptrs, acc.to(C.dtype.element_ty), mask=c_mask)


@libentry()
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_N": bn, "BLOCK_M": bm}, num_warps=w)
        for bn, bm, w in [
            (32, 128, 4),
            (64, 128, 4),
            (128, 256, 8),
        ]
    ],
    key=["M", "N"],
)
@triton.jit
def _col_sum_kernel(
    inp,
    out,
    M,
    N,
    stride_m,
    stride_n,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    pid_n = tl.program_id(0)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    acc = tl.zeros((BLOCK_N,), dtype=tl.float32)
    for m in range(0, M, BLOCK_M):
        offs_m = m + tl.arange(0, BLOCK_M)
        ptrs = inp + offs_m[:, None] * stride_m + offs_n[None, :] * stride_n
        mask = (offs_m[:, None] < M) & (offs_n[None, :] < N)
        acc += tl.sum(tl.load(ptrs, mask=mask, other=0.0).to(tl.float32), axis=0)
    tl.store(out + offs_n, acc.to(out.dtype.element_ty), mask=offs_n < N)


def _triton_mm(a, b):
    """Row-major matmul (M, K) x (K, N) -> (M, N) using the Triton kernel."""
    M, K = a.shape
    K2, N = b.shape
    assert K == K2
    c = torch.empty((M, N), device=a.device, dtype=a.dtype)
    if M == 0 or N == 0:
        return c
    grid = lambda meta: (  # noqa: E731
        triton.cdiv(M, meta["BLOCK_M"]),
        triton.cdiv(N, meta["BLOCK_N"]),
    )
    with torch_device_fn.device(a.device):
        _matmul_kernel[grid](
            a,
            b,
            c,
            M,
            N,
            K,
            a.stride(0),
            a.stride(1),
            b.stride(0),
            b.stride(1),
            c.stride(0),
            c.stride(1),
        )
    return c


def _triton_col_sum(x):
    """Sum a 2D tensor (M, N) over dim 0 -> (N,) using the Triton kernel."""
    M, N = x.shape
    out = torch.empty((N,), device=x.device, dtype=x.dtype)
    if N == 0:
        return out
    grid = lambda meta: (triton.cdiv(N, meta["BLOCK_N"]),)  # noqa: E731
    with torch_device_fn.device(x.device):
        _col_sum_kernel[grid](x, out, M, N, x.stride(0), x.stride(1))
    return out


def conv_tbc_backward(grad_output, input, weight, bias, pad):
    logger.debug("GEMS CONV_TBC_BACKWARD")

    ilen, batch, in_c = input.shape
    kw, _, out_c = weight.shape
    olen = grad_output.shape[0]

    grad_output = grad_output.contiguous()
    input = input.contiguous()
    weight = weight.contiguous()

    # ---- grad_bias: sum grad_output over (time, batch) -> (out_c,) ----
    grad_bias = _triton_col_sum(grad_output.reshape(olen * batch, out_c))

    # ---- grad_weight: for each kernel tap, matmul windowed input with grad_output ----
    # lhs: (kw * in_c, olen * batch), rhs: (olen * batch, out_c)
    if pad > 0:
        input_pad = torch.nn.functional.pad(input, (0, 0, 0, 0, pad, pad))
    else:
        input_pad = input
    # windows over time: (kw, batch, in_c, olen)
    input_win = input_pad.unfold(0, olen, 1)
    lhs_w = input_win.permute(0, 2, 3, 1).reshape(kw * in_c, olen * batch).contiguous()
    rhs_w = grad_output.reshape(olen * batch, out_c)
    grad_weight = _triton_mm(lhs_w, rhs_w).reshape(kw, in_c, out_c)

    # ---- grad_input: full convolution of grad_output with flipped weight ----
    # lhs: (ilen * batch, kw * out_c), rhs: (kw * out_c, in_c)
    front = kw - 1 - pad
    grad_out_pad = torch.nn.functional.pad(grad_output, (0, 0, 0, 0, front, front))
    grad_out_win = grad_out_pad.unfold(0, ilen, 1)  # (kw, batch, out_c, ilen)
    lhs_i = (
        grad_out_win.permute(3, 1, 0, 2).reshape(ilen * batch, kw * out_c).contiguous()
    )
    weight_flip = weight.flip(0).permute(0, 2, 1).reshape(kw * out_c, in_c).contiguous()
    grad_input = _triton_mm(lhs_i, weight_flip).reshape(ilen, batch, in_c)

    return grad_input, grad_weight, grad_bias
