# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _corrcoef_mean_kernel(
    x_ptr, mean_ptr, n_rows, n_cols, stride_xn, stride_xm, BLOCK_M: tl.constexpr
):
    # Each program reduces one row to its mean over the observation axis.
    row = tl.program_id(0)
    acc = tl.zeros([BLOCK_M], dtype=tl.float32)
    for m_start in range(0, n_cols, BLOCK_M):
        offs = m_start + tl.arange(0, BLOCK_M)
        mask = offs < n_cols
        x = tl.load(x_ptr + row * stride_xn + offs * stride_xm, mask=mask, other=0.0)
        x = x.to(tl.float32)
        acc += x
    mean = tl.sum(acc) / n_cols
    tl.store(mean_ptr + row, mean)


@triton.jit
def _corrcoef_cov_kernel(
    x_ptr,
    mean_ptr,
    c_ptr,
    n_rows,
    n_cols,
    stride_xn,
    stride_xm,
    stride_cn,
    stride_cm,
    BLOCK_N: tl.constexpr,
    BLOCK_M: tl.constexpr,
):
    # 2D-tiled covariance: c[i, j] = sum_k (x[i, k] - mean[i]) * (x[j, k] - mean[j])
    # divided by (n_cols - 1). Centering is fused into the GEMM to avoid an
    # extra global-memory round trip over the centered matrix.
    pid_i = tl.program_id(0)
    pid_j = tl.program_id(1)

    offs_i = pid_i * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_j = pid_j * BLOCK_N + tl.arange(0, BLOCK_N)

    mi = tl.load(mean_ptr + offs_i, mask=offs_i < n_rows, other=0.0)
    mj = tl.load(mean_ptr + offs_j, mask=offs_j < n_rows, other=0.0)

    acc = tl.zeros([BLOCK_N, BLOCK_N], dtype=tl.float32)

    for m_start in range(0, n_cols, BLOCK_M):
        offs_m = m_start + tl.arange(0, BLOCK_M)
        mask_m = offs_m < n_cols

        mask_i = offs_i < n_rows
        mask_j = offs_j < n_rows

        xi = tl.load(
            x_ptr + offs_i[:, None] * stride_xn + offs_m[None, :] * stride_xm,
            mask=mask_i[:, None] & mask_m[None, :],
            other=0.0,
        ).to(tl.float32)
        xj = tl.load(
            x_ptr + offs_j[:, None] * stride_xn + offs_m[None, :] * stride_xm,
            mask=mask_j[:, None] & mask_m[None, :],
            other=0.0,
        ).to(tl.float32)

        xi_centered = xi - mi[:, None]
        xj_centered = xj - mj[:, None]

        # Re-mask padding lanes to 0 (not -mean) so the dot product stays exact
        # for observation counts that are not a multiple of BLOCK_M.
        xi_centered = tl.where(mask_m[None, :], xi_centered, 0.0)
        xj_centered = tl.where(mask_m[None, :], xj_centered, 0.0)

        acc += tl.dot(xi_centered, tl.trans(xj_centered))

    c = acc / (n_cols - 1)

    mask_ij = (offs_i[:, None] < n_rows) & (offs_j[None, :] < n_rows)
    tl.store(
        c_ptr + offs_i[:, None] * stride_cn + offs_j[None, :] * stride_cm,
        c,
        mask=mask_ij,
    )


@triton.jit
def _corrcoef_std_norm_kernel(
    c_ptr,
    out_ptr,
    n_rows,
    stride_cn,
    stride_cm,
    stride_on,
    stride_om,
    BLOCK_N: tl.constexpr,
):
    # Fused std + normalization: corr[i, j] = c[i, j] / (std[i] * std[j]) where
    # std comes from the covariance diagonal. Zero-variance rows divide by 0 and
    # yield NaN, matching torch.corrcoef semantics for degenerate variables.
    pid_i = tl.program_id(0)
    pid_j = tl.program_id(1)

    offs_i = pid_i * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_j = pid_j * BLOCK_N + tl.arange(0, BLOCK_N)
    mask_i = offs_i < n_rows
    mask_j = offs_j < n_rows
    mask_ij = mask_i[:, None] & mask_j[None, :]

    # Diagonal elements are the per-variable variances; sqrt gives std.
    si = tl.load(
        c_ptr + offs_i * stride_cn + offs_i * stride_cm, mask=mask_i, other=0.0
    )
    sj = tl.load(
        c_ptr + offs_j * stride_cn + offs_j * stride_cm, mask=mask_j, other=0.0
    )
    si = tl.sqrt(si)
    sj = tl.sqrt(sj)

    c = tl.load(
        c_ptr + offs_i[:, None] * stride_cn + offs_j[None, :] * stride_cm,
        mask=mask_ij,
        other=0.0,
    )

    denom = si[:, None] * sj[None, :]
    # Natural division matches torch.corrcoef exactly, including the diagonal
    # (~1.0 up to rounding) and the NaN produced by zero-variance variables
    # (0 / 0), rather than forcing the diagonal to a hard 1.0.
    corr = c / denom

    tl.store(
        out_ptr + offs_i[:, None] * stride_on + offs_j[None, :] * stride_om,
        corr,
        mask=mask_ij,
    )


def corrcoef(input: torch.Tensor) -> torch.Tensor:
    """Estimates the Pearson product-moment correlation coefficient matrix.

    Rows of ``input`` are the variables and columns are the observations. The
    output is an N x N correlation matrix where ``R[i, j] = C[i, j] /
    sqrt(C[i, i] * C[j, j])`` and ``C`` is the covariance matrix. The
    computation is carried out in float32 internally and the result is cast
    back to the input dtype, matching the precision behaviour expected from a
    stable Triton implementation.
    """
    logger.debug("GEMS CORRCOEF")

    # A single variable (1D/0D input, or a 2D input with one row) correlates
    # perfectly with itself, so torch.corrcoef returns the scalar 1.0.
    if input.dim() < 2 or input.shape[0] == 1:
        return torch.ones((), dtype=input.dtype, device=input.device)

    x = input.contiguous()
    n_rows, n_cols = x.shape
    device = x.device
    out_dtype = x.dtype

    # Per-variable means, kept in float32 for numerical stability across dtypes.
    mean = torch.empty(n_rows, device=device, dtype=torch.float32)
    # Column reduction tile: 128 balances vector width against loop trips for
    # the observation counts (<=4096) used in tests/benchmarks.
    BLOCK_M = 128
    _corrcoef_mean_kernel[(n_rows,)](
        x, mean, n_rows, n_cols, x.stride(0), x.stride(1), BLOCK_M=BLOCK_M
    )

    # Covariance accumulates in float32 for stability, then normalizes to dtype.
    cov = torch.empty(n_rows, n_rows, device=device, dtype=torch.float32)
    # Row tile for the 2D covariance grid: 32 keeps the GEMM K-dim valid and
    # gives good SM occupancy for the row counts (<=512) exercised here.
    BLOCK_N = 32
    grid_n = triton.cdiv(n_rows, BLOCK_N)
    _corrcoef_cov_kernel[(grid_n, grid_n)](
        x,
        mean,
        cov,
        n_rows,
        n_cols,
        x.stride(0),
        x.stride(1),
        cov.stride(0),
        cov.stride(1),
        BLOCK_N=BLOCK_N,
        BLOCK_M=BLOCK_M,
        # 4 pipeline stages overlap the column-reduction loads with the dot
        # product; critical for the wide-column (fp16) shapes.
        num_stages=4,
    )

    out = torch.empty(n_rows, n_rows, device=device, dtype=out_dtype)
    # Output tile for the normalization pass mirrors the covariance row tile.
    BLOCK_N_OUT = 32
    grid_out = triton.cdiv(n_rows, BLOCK_N_OUT)
    _corrcoef_std_norm_kernel[(grid_out, grid_out)](
        cov,
        out,
        n_rows,
        cov.stride(0),
        cov.stride(1),
        out.stride(0),
        out.stride(1),
        BLOCK_N=BLOCK_N_OUT,
    )

    return out
