# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _cov_mean_kernel(
    x_ptr,
    w_ptr,
    mean_ptr,
    n_rows,
    n_cols,
    w_sum,
    stride_xn,
    stride_xm,
    HAS_W: tl.constexpr,
    BLOCK_M: tl.constexpr,
):
    # Each program reduces one row (variable) to its weighted mean over the
    # observation axis: avg[i] = sum_k w[k] * x[i, k] / w_sum. With no weights
    # this is the plain mean and w_sum == n_cols.
    row = tl.program_id(0)
    acc = tl.zeros([BLOCK_M], dtype=tl.float32)
    for m_start in range(0, n_cols, BLOCK_M):
        offs = m_start + tl.arange(0, BLOCK_M)
        mask = offs < n_cols
        x = tl.load(x_ptr + row * stride_xn + offs * stride_xm, mask=mask, other=0.0)
        x = x.to(tl.float32)
        if HAS_W:
            w = tl.load(w_ptr + offs, mask=mask, other=0.0).to(tl.float32)
            x = x * w
        acc += x
    mean = tl.sum(acc) / w_sum
    tl.store(mean_ptr + row, mean)


@triton.jit
def _cov_weight_kernel(
    wf_ptr,
    wa_ptr,
    w_ptr,
    n_cols,
    HAS_WF: tl.constexpr,
    HAS_WA: tl.constexpr,
    BLOCK_M: tl.constexpr,
):
    # Builds the combined float32 observation weight w = fweights * aweights,
    # keeping whichever is provided. fweights arrives as an integer tensor, so
    # the int->float32 conversion happens here inside the kernel rather than via
    # a host-side ``.to(float32)``. That host cast would dispatch to FlagGems'
    # own _to_copy, which is unstable across the many shapes/dtypes exercised in
    # a full test run; keeping the conversion in-kernel sidesteps it entirely.
    pid = tl.program_id(0)
    offs = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    mask = offs < n_cols
    acc = tl.full([BLOCK_M], 1.0, dtype=tl.float32)
    if HAS_WF:
        wf = tl.load(wf_ptr + offs, mask=mask, other=0).to(tl.float32)
        acc = acc * wf
    if HAS_WA:
        wa = tl.load(wa_ptr + offs, mask=mask, other=0.0).to(tl.float32)
        acc = acc * wa
    tl.store(w_ptr + offs, acc, mask=mask)


@triton.jit
def _cov_kernel(
    x_ptr,
    w_ptr,
    mean_ptr,
    c_ptr,
    n_rows,
    n_cols,
    fact,
    stride_xn,
    stride_xm,
    stride_cn,
    stride_cm,
    HAS_W: tl.constexpr,
    HIGH_PRECISION: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_M: tl.constexpr,
):
    # 2D-tiled covariance:
    #   c[i, j] = sum_k w[k] * (x[i, k] - mean[i]) * (x[j, k] - mean[j]) / fact.
    # Centering (and the optional weighting) is fused into the GEMM to avoid an
    # extra global-memory round trip over a materialized centered matrix. The
    # accumulator stays in float32. The dot product uses tf32 (the default
    # tensor-core precision across FlagGems' matmul ops) for the common case,
    # falling back to the 3-pass tf32x3 emulation for short reductions where
    # tf32's relative error would otherwise exceed the accuracy tolerance (see
    # the HIGH_PRECISION selection in the wrapper). tf32x3 is essentially free
    # there because those reductions produce tiny GEMMs.
    pid_i = tl.program_id(0)
    pid_j = tl.program_id(1)

    offs_i = pid_i * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_j = pid_j * BLOCK_N + tl.arange(0, BLOCK_N)

    mask_i = offs_i < n_rows
    mask_j = offs_j < n_rows

    mi = tl.load(mean_ptr + offs_i, mask=mask_i, other=0.0)
    mj = tl.load(mean_ptr + offs_j, mask=mask_j, other=0.0)

    acc = tl.zeros([BLOCK_N, BLOCK_N], dtype=tl.float32)

    for m_start in range(0, n_cols, BLOCK_M):
        offs_m = m_start + tl.arange(0, BLOCK_M)
        mask_m = offs_m < n_cols

        xi = tl.load(
            x_ptr + offs_i[:, None] * stride_xn + offs_m[None, :] * stride_xm,
            mask=mask_i[:, None] & mask_m[None, :],
            other=0.0,
        ).to(tl.float32)
        xj = tl.load(
            x_ptr + offs_j[:, None] * stride_xn + offs_m[None, :] * stride_xm,
            mask=mask_j[:, None] & mask_m[None, :],
            other=0.0,
        ).to(tl.float32)

        xi_centered = xi - mi[:, None]
        xj_centered = xj - mj[:, None]

        # The weight is folded into one operand so the dot product yields the
        # weighted cross-products sum_k w[k] * xi_c[k] * xj_c[k].
        if HAS_W:
            w = tl.load(w_ptr + offs_m, mask=mask_m, other=0.0).to(tl.float32)
            xi_centered = xi_centered * w[None, :]

        # Re-mask padding lanes to 0 (not -mean) so the dot product stays exact
        # for observation counts that are not a multiple of BLOCK_M.
        xi_centered = tl.where(mask_m[None, :], xi_centered, 0.0)
        xj_centered = tl.where(mask_m[None, :], xj_centered, 0.0)

        if HIGH_PRECISION:
            acc += tl.dot(xi_centered, tl.trans(xj_centered), input_precision="tf32x3")
        else:
            acc += tl.dot(xi_centered, tl.trans(xj_centered), input_precision="tf32")

    c = acc / fact

    mask_ij = mask_i[:, None] & mask_j[None, :]
    tl.store(
        c_ptr + offs_i[:, None] * stride_cn + offs_j[None, :] * stride_cm,
        c,
        mask=mask_ij,
    )


def cov(
    input: torch.Tensor,
    *,
    correction: int = 1,
    fweights: torch.Tensor = None,
    aweights: torch.Tensor = None,
) -> torch.Tensor:
    """Estimates the covariance matrix of the variables given by ``input``.

    Rows of ``input`` are the variables and columns are the observations, so a
    (N, M) input yields an (N, N) covariance matrix where ``C[i, j]`` is the
    covariance of variables ``i`` and ``j``. ``correction`` is the difference
    between the number of observations and the divisor (Bessel's correction, 1
    by default). ``fweights`` and ``aweights`` are optional frequency and
    analytic weights over the observations. The computation runs in float32
    internally and the result is cast back to the input dtype, matching the
    precision behaviour expected from a stable Triton implementation.
    """
    logger.debug("GEMS COV")

    if input.dim() > 2:
        raise ValueError(
            f"cov(): expected input to have two or fewer dimensions but got {input.dim()}"
        )

    # torch.cov treats a 0D/1D input as a single variable observed across the
    # elements, returning a 0D scalar (the variance). A 2D input with a single
    # row is likewise one variable and also yields a scalar.
    x = input.view(1, -1) if input.dim() < 2 else input
    x = x.contiguous()
    n_rows, n_cols = x.shape
    device = x.device
    out_dtype = input.dtype
    single_variable = n_rows == 1

    # Build the combined observation weight vector w = fweights * aweights,
    # keeping whichever is provided. Weights live in float32 for stability. The
    # int->float32 conversion of fweights is done inside _cov_weight_kernel
    # rather than via a host-side ``.to(float32)``, which would dispatch to
    # FlagGems' unstable _to_copy (see the kernel's comment).
    has_wf = fweights is not None
    has_wa = aweights is not None
    has_w = has_wf or has_wa
    w = None
    if has_w:
        wf = fweights.contiguous() if has_wf else None
        wa = (
            aweights.to(device=device, dtype=torch.float32).contiguous()
            if has_wa
            else None
        )
        w = torch.empty(n_cols, device=device, dtype=torch.float32)
        WEIGHT_BLOCK = 1024
        grid_w = triton.cdiv(n_cols, WEIGHT_BLOCK)
        _cov_weight_kernel[(grid_w,)](
            wf,
            wa,
            w,
            n_cols,
            HAS_WF=has_wf,
            HAS_WA=has_wa,
            BLOCK_M=WEIGHT_BLOCK,
        )

    # w_sum and the divisor `fact` follow torch.cov exactly:
    #   no weights          -> fact = n_cols - correction
    #   fweights only        -> fact = w_sum - correction
    #   aweights (any)       -> fact = w_sum - correction * sum(w * aweights) / w_sum
    # `fact` is clamped at 0, matching torch's degenerate-weight handling.
    if has_w:
        w_sum = float(w.sum().item())
        if not has_wa:
            fact = w_sum - correction
        else:
            fact = w_sum - correction * float((w * wa).sum().item()) / w_sum
    else:
        w_sum = float(n_cols)
        fact = float(n_cols - correction)
    if fact < 0.0:
        fact = 0.0

    # Per-variable (weighted) means, kept in float32 for numerical stability.
    mean = torch.empty(n_rows, device=device, dtype=torch.float32)
    # Column reduction tile: 128 balances vector width against loop trips for
    # the observation counts exercised in tests/benchmarks.
    BLOCK_M = 128
    _cov_mean_kernel[(n_rows,)](
        x,
        w,
        mean,
        n_rows,
        n_cols,
        w_sum,
        x.stride(0),
        x.stride(1),
        HAS_W=has_w,
        BLOCK_M=BLOCK_M,
    )

    # Covariance accumulates in float32 inside the kernel for stability; the
    # output buffer is allocated in the target dtype so the final tl.store casts
    # directly, avoiding a separate .to() round trip (which also matches how
    # corrcoef writes its result).
    cov_mat = torch.empty(n_rows, n_rows, device=device, dtype=out_dtype)
    # Precision policy keyed on the reduction length n_cols, which is what
    # governs the relative error of the centered cross-products sum. tf32's
    # ~1e-3 relative error stays inside the accuracy tolerance once the sum runs
    # over enough observations, but for short reductions it would exceed the
    # tolerance, so those use the exact-fp32 tf32x3 emulation. Short reductions
    # produce tiny GEMMs, so the 3-pass cost there is negligible. The threshold
    # is independent of the row count, so it never trades accuracy for speed on
    # the larger matrices that dominate timing.
    HIGH_PRECISION = n_cols < 32
    # Row tile for the 2D covariance grid: 32 keeps the GEMM K-dim valid and
    # gives good SM occupancy for the row counts exercised here.
    BLOCK_N = 32
    grid_n = triton.cdiv(n_rows, BLOCK_N)
    _cov_kernel[(grid_n, grid_n)](
        x,
        w,
        mean,
        cov_mat,
        n_rows,
        n_cols,
        fact,
        x.stride(0),
        x.stride(1),
        cov_mat.stride(0),
        cov_mat.stride(1),
        HAS_W=has_w,
        HIGH_PRECISION=HIGH_PRECISION,
        BLOCK_N=BLOCK_N,
        BLOCK_M=BLOCK_M,
    )

    # A single variable (1D input, or a 2D input with one row) yields a 0D
    # scalar variance, matching torch.cov.
    if single_variable:
        return cov_mat.view(())
    return cov_mat
