# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _cumtrapz_kernel(
    y_ptr,
    out_ptr,
    N,
    inner,
    stride_row_in,
    stride_row_out,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    o = pid // inner
    i = pid % inner
    in_base = o * stride_row_in + i
    out_base = o * stride_row_out + i

    k = tl.arange(0, BLOCK)
    mask = k < (N - 1)

    a = tl.load(y_ptr + in_base + k * inner, mask=mask, other=0.0).to(tl.float32)
    b = tl.load(y_ptr + in_base + (k + 1) * inner, mask=mask, other=0.0).to(tl.float32)
    t = (a + b) * 0.5
    cs = tl.cumsum(t, axis=0)

    tl.store(out_ptr + out_base + k * inner, cs, mask=mask)


def cumulative_trapezoid(y, *, dx=1, dim=-1):
    logger.debug("GEMS CUMULATIVE_TRAPEZOID")

    assert y.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    ), f"cumulative_trapezoid: unsupported dtype {y.dtype}"

    ndim = y.dim()
    d = dim if dim >= 0 else dim + ndim

    sizes = list(y.shape)
    N = sizes[d]

    outer = 1
    for s in sizes[:d]:
        outer *= s
    inner = 1
    for s in sizes[d + 1 :]:
        inner *= s

    out_sizes = list(sizes)
    out_sizes[d] = max(N - 1, 0)
    output = torch.empty(out_sizes, dtype=y.dtype, device=y.device)

    if N <= 1 or outer * inner == 0:
        return output if dx == 1 else output * dx

    yc = y.contiguous()

    stride_row_in = N * inner
    stride_row_out = (N - 1) * inner

    BLOCK = triton.next_power_of_2(max(N - 1, 1))
    grid = (outer * inner,)

    _cumtrapz_kernel[grid](
        yc,
        output,
        N,
        inner,
        stride_row_in,
        stride_row_out,
        BLOCK=BLOCK,
    )

    if dx != 1:
        output = output * dx
    return output
