# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def _minmax_reduce_kernel(
    x_ptr,
    global_min_ptr,
    global_max_ptr,
    N,
    BLOCK_SIZE: tl.constexpr,
):
    """Parallel min/max reduction. Each block atomically merges."""
    pid = tl.program_id(0)
    off = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = off < N

    x = tl.load(x_ptr + off, mask=mask, other=0.0).to(tl.float32)

    x_for_min = tl.where(mask, x, float("inf"))
    x_for_max = tl.where(mask, x, float("-inf"))

    block_min = tl.min(x_for_min, axis=0)
    block_max = tl.max(x_for_max, axis=0)

    tl.atomic_min(global_min_ptr, block_min)
    tl.atomic_max(global_max_ptr, block_max)


@triton.jit
def _fake_quant_kernel(
    x_ptr,
    out_ptr,
    scale,
    zero_point,
    quant_min,
    quant_max,
    N,
    BLOCK_SIZE: tl.constexpr,
):
    """Parallel fake quantization using precomputed scale/zp."""
    pid = tl.program_id(0)
    off = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = off < N

    x = tl.load(x_ptr + off, mask=mask, other=0.0).to(tl.float32)

    inv_scale = 1.0 / scale
    qmin_f = quant_min + 0.0
    qmax_f = quant_max + 0.0

    q = tl_extra_shim.rint(x * inv_scale) + zero_point
    q = tl.where(q < qmin_f, qmin_f, q)
    q = tl.where(q > qmax_f, qmax_f, q)
    out = (q - zero_point) * scale

    tl.store(out_ptr + off, out, mask=mask)


def fused_moving_avg_obs_fake_quant(
    input,
    observer_on,
    fake_quant_on,
    running_min,
    running_max,
    scale,
    zero_point,
    averaging_const,
    quant_min,
    quant_max,
    ch_axis,
    per_row_fake_quant=False,
    symmetric_quant=False,
):
    """Fused moving average observer + fake quantization.

    Two-phase approach:
      Phase 1: Triton kernel for parallel min/max reduction
      Host: EMA update + scale/zp computation (scalar math)
      Phase 2: Triton kernel for parallel fake quantization
    """
    logger.debug("GEMS FUSED_MOVING_AVG_OBS_FAKE_QUANT")

    obs = (
        bool(observer_on.item()) if torch.is_tensor(observer_on) else bool(observer_on)
    )
    fq = (
        bool(fake_quant_on.item())
        if torch.is_tensor(fake_quant_on)
        else bool(fake_quant_on)
    )
    sym = bool(symmetric_quant)

    x = input.contiguous().view(-1).float()
    N = x.numel()
    dev = x.device

    out = torch.empty_like(x)

    BLOCK_SIZE = 1024
    num_blocks = triton.cdiv(N, BLOCK_SIZE)

    qmin_f = float(quant_min)
    qmax_f = float(quant_max)

    if obs:
        # Phase 1: parallel min/max reduction
        global_min = torch.tensor([float("inf")], dtype=torch.float32, device=dev)
        global_max = torch.tensor([float("-inf")], dtype=torch.float32, device=dev)

        with torch_device_fn.device(dev):
            _minmax_reduce_kernel[(num_blocks,)](
                x,
                global_min,
                global_max,
                N,
                BLOCK_SIZE=BLOCK_SIZE,
            )

        # Host: EMA update
        cur_min = global_min.item()
        cur_max = global_max.item()
        old_min = running_min.item()
        old_max = running_max.item()
        new_min = old_min + averaging_const * (cur_min - old_min)
        new_max = old_max + averaging_const * (cur_max - old_max)
        running_min.fill_(new_min)
        running_max.fill_(new_max)

    # Host: scale/zp computation (always uses running_min/max)
    rmin = min(running_min.item(), 0.0)
    rmax = max(running_max.item(), 0.0)
    sc = (rmax - rmin) / (qmax_f - qmin_f)
    if sc == 0.0:
        sc = 0.1
    zp = round(qmin_f - rmin / sc)
    zp = max(qmin_f, min(qmax_f, zp))

    if sym and rmin < 0.0 and rmax > 0.0:
        sc = max(-rmin / (-qmin_f), rmax / qmax_f)
        if sc == 0.0:
            sc = 0.1
        zp = round((qmin_f + qmax_f) / 2.0)

    scale.fill_(sc)
    zero_point.fill_(int(zp))

    sc_val = sc
    zp_val = float(zp)

    if fq:
        # Phase 2: parallel fake quantization
        with torch_device_fn.device(dev):
            _fake_quant_kernel[(num_blocks,)](
                x,
                out,
                sc_val,
                zp_val,
                quant_min,
                quant_max,
                N,
                BLOCK_SIZE=BLOCK_SIZE,
            )
    else:
        out.copy_(x)

    return out.view(input.shape).to(input.dtype)
