# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit(do_not_specialize=["min_val", "max_val"])
def hardtanh_kernel(
    x_ptr, out_ptr, n_elements, min_val, max_val, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    # hardtanh is a pure clamp with no precision-losing arithmetic, so operate in
    # the input dtype directly; upcasting fp16/bf16 to float32 only wastes
    # registers/bandwidth (cf. relu, which also stays native).
    y = tl.minimum(tl.maximum(x, min_val), max_val)
    # tl.minimum/tl.maximum drop NaN (IEEE minNum/maxNum), but PyTorch hardtanh
    # propagates NaN. Restore that: x != x is True only for NaN.
    y = tl.where(x != x, x, y)

    tl.store(out_ptr + offsets, y, mask=mask)


def hardtanh(A, min_val=-1.0, max_val=1.0):
    logger.debug("GEMS HARDTANH")
    if not A.is_contiguous():
        A = A.contiguous()
    out = torch.empty_like(A)
    n_elements = A.numel()
    if n_elements == 0:
        return out
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(A.device):
        hardtanh_kernel[grid](
            A, out, n_elements, float(min_val), float(max_val), BLOCK_SIZE=1024
        )
    return out


def hardtanh_out(A, min_val=-1.0, max_val=1.0, *, out=None):
    logger.debug("GEMS HARDTANH_OUT")
    if out is None:
        return hardtanh(A, min_val, max_val)
    if not A.is_contiguous():
        A = A.contiguous()
    n_elements = A.numel()
    if n_elements == 0:
        return out
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(A.device):
        hardtanh_kernel[grid](
            A, out, n_elements, float(min_val), float(max_val), BLOCK_SIZE=1024
        )
    return out
