# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _gram_matrix_kernel(
    A_ptr,
    G_ptr,
    M,
    N,
    stride_ab,
    stride_am,
    stride_an,
    stride_gb,
    stride_gn1,
    stride_gn2,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Compute G = A^T A for a single batch element."""
    batch_id = tl.program_id(0)
    A_batch = A_ptr + batch_id * stride_ab
    G_batch = G_ptr + batch_id * stride_gb

    m_idx = tl.arange(0, BLOCK_M)

    for i in range(BLOCK_N):
        for j in range(BLOCK_N):
            a_i = tl.load(
                A_batch + m_idx * stride_am + i * stride_an,
                mask=m_idx < M,
                other=0.0,
            )
            a_j = tl.load(
                A_batch + m_idx * stride_am + j * stride_an,
                mask=m_idx < M,
                other=0.0,
            )
            dot = tl.sum(a_i * a_j)
            tl.store(G_batch + i * stride_gn1 + j * stride_gn2, dot)


@triton.jit
def _jacobi_eigenvalues_kernel(
    G_ptr,
    eigvals_ptr,
    stride_gb,
    stride_gn1,
    stride_gn2,
    stride_eb,
    stride_en,
    N: tl.constexpr,
    MAX_ITER: tl.constexpr,
):
    """Jacobi eigenvalue algorithm for symmetric matrix.
    Computes eigenvalues of a symmetric NxN matrix in-place.
    """
    batch_id = tl.program_id(0)
    G_batch = G_ptr + batch_id * stride_gb
    E_batch = eigvals_ptr + batch_id * stride_eb

    # Load matrix into registers - use flat indexing
    # We work with a flattened NxN matrix
    for sweep in range(MAX_ITER):
        for p in range(N):
            for q in range(p + 1, N):
                # Load G[p,p], G[q,q], G[p,q]
                app = tl.load(G_batch + p * stride_gn1 + p * stride_gn2)
                aqq = tl.load(G_batch + q * stride_gn1 + q * stride_gn2)
                apq = tl.load(G_batch + p * stride_gn1 + q * stride_gn2)

                # Skip if already zero (use tighter threshold for better convergence)
                abs_apq = tl.abs(apq)
                if abs_apq > 1e-15:
                    # Compute rotation angle
                    tau = (aqq - app) / (2.0 * apq)
                    # t = sign(tau) / (|tau| + sqrt(1 + tau^2))
                    t = tl.where(
                        tau >= 0.0,
                        1.0 / (tau + tl.sqrt(1.0 + tau * tau)),
                        -1.0 / (-tau + tl.sqrt(1.0 + tau * tau)),
                    )
                    c = 1.0 / tl.sqrt(1.0 + t * t)
                    s = t * c

                    # Update matrix: apply rotation
                    # G[p,p] = c^2*app - 2*s*c*apq + s^2*aqq
                    # G[q,q] = s^2*app + 2*s*c*apq + c^2*aqq
                    # G[p,q] = G[q,p] = 0
                    new_app = c * c * app - 2.0 * s * c * apq + s * s * aqq
                    new_aqq = s * s * app + 2.0 * s * c * apq + c * c * aqq
                    tl.store(G_batch + p * stride_gn1 + p * stride_gn2, new_app)
                    tl.store(G_batch + q * stride_gn1 + q * stride_gn2, new_aqq)
                    tl.store(G_batch + p * stride_gn1 + q * stride_gn2, 0.0)
                    tl.store(G_batch + q * stride_gn1 + p * stride_gn2, 0.0)

                    # Update off-diagonal elements
                    for r in range(N):
                        if r != p and r != q:
                            arp = tl.load(G_batch + r * stride_gn1 + p * stride_gn2)
                            arq = tl.load(G_batch + r * stride_gn1 + q * stride_gn2)
                            new_rp = c * arp - s * arq
                            new_rq = s * arp + c * arq
                            tl.store(
                                G_batch + r * stride_gn1 + p * stride_gn2,
                                new_rp,
                            )
                            tl.store(
                                G_batch + p * stride_gn1 + r * stride_gn2,
                                new_rp,
                            )
                            tl.store(
                                G_batch + r * stride_gn1 + q * stride_gn2,
                                new_rq,
                            )
                            tl.store(
                                G_batch + q * stride_gn1 + r * stride_gn2,
                                new_rq,
                            )

    # Store diagonal as eigenvalues
    for i in range(N):
        val = tl.load(G_batch + i * stride_gn1 + i * stride_gn2)
        tl.store(E_batch + i * stride_en, val)


@triton.jit
def _cond_from_eigvals_kernel(
    eigvals_ptr,
    out_ptr,
    stride_eb,
    stride_en,
    stride_ob,
    N: tl.constexpr,
    p_mode: tl.constexpr,
):
    """Compute condition number from eigenvalues of A^T A.
    p_mode: 0 = p=None/2 (max/min), 1 = p=-2 (min/max), 2 = p='nuc'
    """
    batch_id = tl.program_id(0)
    E_batch = eigvals_ptr + batch_id * stride_eb

    # Find max and min eigenvalues, compute sqrt for singular values
    sigma_max = 0.0
    sigma_min = 1e30
    sigma_sum = 0.0

    for i in range(N):
        eig = tl.load(E_batch + i * stride_en)
        # eigenvalues of A^T A should be non-negative
        eig = tl.maximum(eig, 0.0)
        sigma = tl.sqrt(eig)
        sigma_max = tl.maximum(sigma_max, sigma)
        sigma_min = tl.minimum(sigma_min, sigma)
        sigma_sum += sigma

    if p_mode == 0:
        # p=None or p=2: max(sigma) / min(sigma)
        cond = tl.where(sigma_min > 1e-30, sigma_max / sigma_min, 1e30)
    elif p_mode == 1:
        # p=-2: min(sigma) / max(sigma)
        cond = tl.where(sigma_max > 1e-30, sigma_min / sigma_max, 0.0)
    else:
        # p='nuc': needs inv singular values too, handled differently
        cond = sigma_sum

    tl.store(out_ptr + batch_id * stride_ob, cond)


@triton.jit
def _matrix_norm_kernel(
    A_ptr,
    out_ptr,
    stride_ab,
    stride_an1,
    stride_an2,
    stride_ob,
    N: tl.constexpr,
    norm_mode: tl.constexpr,
):
    """Compute matrix norms.
    norm_mode:
        0 = frobenius norm
        1 = max col abs sum (1-norm)
        2 = min col abs sum (-1 norm)
        3 = max row abs sum (inf-norm)
        4 = min row abs sum (-inf norm)
    """
    batch_id = tl.program_id(0)
    A_batch = A_ptr + batch_id * stride_ab

    if norm_mode == 0:
        # Frobenius norm
        acc = 0.0
        for i in range(N):
            for j in range(N):
                val = tl.load(A_batch + i * stride_an1 + j * stride_an2)
                acc += val * val
        result = tl.sqrt(acc)
    elif norm_mode == 1:
        # Max column absolute sum (1-norm)
        result = 0.0
        for j in range(N):
            col_sum = 0.0
            for i in range(N):
                val = tl.load(A_batch + i * stride_an1 + j * stride_an2)
                col_sum += tl.abs(val)
            result = tl.maximum(result, col_sum)
    elif norm_mode == 2:
        # Min column absolute sum (-1 norm)
        result = 1e30
        for j in range(N):
            col_sum = 0.0
            for i in range(N):
                val = tl.load(A_batch + i * stride_an1 + j * stride_an2)
                col_sum += tl.abs(val)
            result = tl.minimum(result, col_sum)
    elif norm_mode == 3:
        # Max row absolute sum (inf-norm)
        result = 0.0
        for i in range(N):
            row_sum = 0.0
            for j in range(N):
                val = tl.load(A_batch + i * stride_an1 + j * stride_an2)
                row_sum += tl.abs(val)
            result = tl.maximum(result, row_sum)
    else:
        # Min row absolute sum (-inf norm)
        result = 1e30
        for i in range(N):
            row_sum = 0.0
            for j in range(N):
                val = tl.load(A_batch + i * stride_an1 + j * stride_an2)
                row_sum += tl.abs(val)
            result = tl.minimum(result, row_sum)

    tl.store(out_ptr + batch_id * stride_ob, result)


@triton.jit
def _cond_norm_kernel(
    norm_a_ptr,
    norm_inv_ptr,
    out_ptr,
    stride_b,
):
    """Compute cond = norm(A) * norm(inv(A))."""
    batch_id = tl.program_id(0)
    na = tl.load(norm_a_ptr + batch_id * stride_b)
    ni = tl.load(norm_inv_ptr + batch_id * stride_b)
    tl.store(out_ptr + batch_id * stride_b, na * ni)


@triton.jit
def _nuc_cond_kernel(
    eigvals_a_ptr,
    eigvals_inv_ptr,
    out_ptr,
    stride_eb,
    stride_en,
    stride_ob,
    N: tl.constexpr,
):
    """Compute nuclear norm condition number from eigenvalues.
    nuc_cond = sum(svdvals(A)) * sum(svdvals(inv(A)))
    svdvals(A) = sqrt(eigvals(A^T A))
    svdvals(inv(A)) = sqrt(eigvals(inv(A)^T inv(A)))
    """
    batch_id = tl.program_id(0)
    Ea_batch = eigvals_a_ptr + batch_id * stride_eb
    Ei_batch = eigvals_inv_ptr + batch_id * stride_eb

    sum_a = 0.0
    sum_inv = 0.0
    for i in range(N):
        eig_a = tl.load(Ea_batch + i * stride_en)
        eig_a = tl.maximum(eig_a, 0.0)
        sum_a += tl.sqrt(eig_a)

        eig_inv = tl.load(Ei_batch + i * stride_en)
        eig_inv = tl.maximum(eig_inv, 0.0)
        sum_inv += tl.sqrt(eig_inv)

    tl.store(out_ptr + batch_id * stride_ob, sum_a * sum_inv)


def _compute_svd_cond(A, batch_size, m, n, p_mode):
    """Compute condition number via SVD (Jacobi eigenvalue decomposition).
    p_mode: 0=p2, 1=p-2, 2=nuc
    """
    device = A.device

    # Compute Gram matrix G = A^T A (shape: batch x n x n)
    # or if m < n, use A A^T (shape: batch x m x m)
    if m >= n:
        gram_n = n
        # G = A^T A
        G = torch.zeros(batch_size, n, n, dtype=torch.float32, device=device)
        A_flat = A.reshape(batch_size, m, n).contiguous()
        BLOCK_M = triton.next_power_of_2(m)
        _gram_matrix_kernel[(batch_size,)](
            A_flat,
            G,
            m,
            n,
            A_flat.stride(0),
            A_flat.stride(1),
            A_flat.stride(2),
            G.stride(0),
            G.stride(1),
            G.stride(2),
            BLOCK_M=BLOCK_M,
            BLOCK_N=n,
        )
    else:
        gram_n = m
        # G = A A^T
        # Transpose: treat as (batch, n, m) with transposed strides
        G = torch.zeros(batch_size, m, m, dtype=torch.float32, device=device)
        A_flat = A.reshape(batch_size, m, n).contiguous()
        # For A A^T, we compute (A)(A^T) = sum over k of A[i,k]*A[j,k]
        # This is equivalent to computing gram of A treated row-wise
        # A A^T = gram of A^T viewed as (batch, n, m)
        AT = A_flat.transpose(1, 2).contiguous()
        BLOCK_M = triton.next_power_of_2(n)
        _gram_matrix_kernel[(batch_size,)](
            AT,
            G,
            n,
            m,
            AT.stride(0),
            AT.stride(1),
            AT.stride(2),
            G.stride(0),
            G.stride(1),
            G.stride(2),
            BLOCK_M=BLOCK_M,
            BLOCK_N=m,
        )

    # Jacobi eigenvalue decomposition
    # More iterations needed for convergence on larger/ill-conditioned matrices
    eigvals = torch.zeros(batch_size, gram_n, dtype=torch.float32, device=device)
    max_iter = max(100, gram_n * 15)
    _jacobi_eigenvalues_kernel[(batch_size,)](
        G,
        eigvals,
        G.stride(0),
        G.stride(1),
        G.stride(2),
        eigvals.stride(0),
        eigvals.stride(1),
        N=gram_n,
        MAX_ITER=max_iter,
    )

    # Compute condition number from eigenvalues
    out = torch.zeros(batch_size, dtype=torch.float32, device=device)
    _cond_from_eigvals_kernel[(batch_size,)](
        eigvals,
        out,
        eigvals.stride(0),
        eigvals.stride(1),
        out.stride(0),
        N=gram_n,
        p_mode=p_mode,
    )
    return out


def _compute_norm_cond(A, batch_size, n, norm_mode):
    """Compute condition number via norm(A) * norm(inv(A)).

    Uses torch.linalg.inv for the inverse (numerically stable via LU),
    and Triton kernels for the norm computations.
    """
    device = A.device
    A_flat = A.reshape(batch_size, n, n).contiguous()

    # Compute norm of A
    norm_a = torch.zeros(batch_size, dtype=torch.float32, device=device)
    _matrix_norm_kernel[(batch_size,)](
        A_flat,
        norm_a,
        A_flat.stride(0),
        A_flat.stride(1),
        A_flat.stride(2),
        norm_a.stride(0),
        N=n,
        norm_mode=norm_mode,
    )

    # Compute inverse of A on CPU to avoid FlagGems Triton LU kernel dispatch
    # which may have reduced accuracy for small matrices. The inverse is then
    # moved back to the original device for the Triton norm kernel.
    Inv_A = torch.linalg.inv(A_flat.cpu()).to(device=device)

    # Compute norm of inv(A)
    norm_inv = torch.zeros(batch_size, dtype=torch.float32, device=device)
    _matrix_norm_kernel[(batch_size,)](
        Inv_A,
        norm_inv,
        Inv_A.stride(0),
        Inv_A.stride(1),
        Inv_A.stride(2),
        norm_inv.stride(0),
        N=n,
        norm_mode=norm_mode,
    )

    # cond = norm(A) * norm(inv(A))
    out = torch.zeros(batch_size, dtype=torch.float32, device=device)
    _cond_norm_kernel[(batch_size,)](
        norm_a,
        norm_inv,
        out,
        1,
    )
    return out


def _compute_nuc_cond(A, batch_size, n):
    """Compute nuclear norm condition number.
    nuc_cond = sum(svdvals(A)) * sum(svdvals(inv(A)))

    Uses torch.linalg.inv for stability, Triton for eigenvalue decomposition.
    """
    device = A.device
    A_flat = A.reshape(batch_size, n, n).contiguous()

    # Compute Gram matrix of A: G_A = A^T A
    G_A = torch.zeros(batch_size, n, n, dtype=torch.float32, device=device)
    BLOCK_M = triton.next_power_of_2(n)
    _gram_matrix_kernel[(batch_size,)](
        A_flat,
        G_A,
        n,
        n,
        A_flat.stride(0),
        A_flat.stride(1),
        A_flat.stride(2),
        G_A.stride(0),
        G_A.stride(1),
        G_A.stride(2),
        BLOCK_M=BLOCK_M,
        BLOCK_N=n,
    )

    # Eigenvalues of G_A
    eigvals_a = torch.zeros(batch_size, n, dtype=torch.float32, device=device)
    max_iter = max(30, n * 3)
    _jacobi_eigenvalues_kernel[(batch_size,)](
        G_A,
        eigvals_a,
        G_A.stride(0),
        G_A.stride(1),
        G_A.stride(2),
        eigvals_a.stride(0),
        eigvals_a.stride(1),
        N=n,
        MAX_ITER=max_iter,
    )

    # Compute inverse on CPU to avoid FlagGems Triton LU kernel dispatch
    Inv_A = torch.linalg.inv(A_flat.cpu()).to(device=device)

    # Compute Gram matrix of inv(A): G_inv = inv(A)^T inv(A)
    G_inv = torch.zeros(batch_size, n, n, dtype=torch.float32, device=device)
    _gram_matrix_kernel[(batch_size,)](
        Inv_A,
        G_inv,
        n,
        n,
        Inv_A.stride(0),
        Inv_A.stride(1),
        Inv_A.stride(2),
        G_inv.stride(0),
        G_inv.stride(1),
        G_inv.stride(2),
        BLOCK_M=BLOCK_M,
        BLOCK_N=n,
    )

    # Eigenvalues of G_inv
    eigvals_inv = torch.zeros(batch_size, n, dtype=torch.float32, device=device)
    _jacobi_eigenvalues_kernel[(batch_size,)](
        G_inv,
        eigvals_inv,
        G_inv.stride(0),
        G_inv.stride(1),
        G_inv.stride(2),
        eigvals_inv.stride(0),
        eigvals_inv.stride(1),
        N=n,
        MAX_ITER=max_iter,
    )

    # Compute nuc cond = sum(svdvals(A)) * sum(svdvals(inv(A)))
    out = torch.zeros(batch_size, dtype=torch.float32, device=device)
    _nuc_cond_kernel[(batch_size,)](
        eigvals_a,
        eigvals_inv,
        out,
        eigvals_a.stride(0),
        eigvals_a.stride(1),
        out.stride(0),
        N=n,
    )
    return out


def linalg_cond(A, p=None):
    """Computes the condition number of a matrix using pure Triton kernels.

    Args:
        A: Input tensor of shape (*, m, n).
        p: The type of condition number. Supports None, 2, -2, 'fro',
           1, -1, float('inf'), float('-inf'), 'nuc'.

    Returns:
        Tensor containing the condition number(s).
    """
    logger.debug("GEMS LINALG_COND")

    assert A.dtype == torch.float32, f"linalg_cond only supports float32, got {A.dtype}"

    if A.numel() == 0:
        return torch.tensor(float("inf"), device=A.device, dtype=torch.float32)

    *batch_dims, m, n = A.shape

    # For p not in (2, -2, None), matrix must be square
    if p not in (2, -2, None) and m != n:
        raise ValueError(f"Matrix must be square for p={p}, got shape {A.shape}")

    batch_size = 1
    for d in batch_dims:
        batch_size *= d
    batch_size = max(batch_size, 1)

    A_contig = A.contiguous()

    if p is None or p == 2:
        out = _compute_svd_cond(A_contig, batch_size, m, n, p_mode=0)
    elif p == -2:
        out = _compute_svd_cond(A_contig, batch_size, m, n, p_mode=1)
    elif p == "fro":
        out = _compute_norm_cond(A_contig, batch_size, n, norm_mode=0)
    elif p == 1:
        out = _compute_norm_cond(A_contig, batch_size, n, norm_mode=1)
    elif p == -1:
        out = _compute_norm_cond(A_contig, batch_size, n, norm_mode=2)
    elif p == float("inf"):
        out = _compute_norm_cond(A_contig, batch_size, n, norm_mode=3)
    elif p == float("-inf"):
        out = _compute_norm_cond(A_contig, batch_size, n, norm_mode=4)
    elif p == "nuc":
        out = _compute_nuc_cond(A_contig, batch_size, n)
    else:
        raise ValueError(f"Unsupported p value: {p}")

    # Reshape output to match batch dimensions
    if batch_dims:
        out = out.reshape(batch_dims)
    else:
        out = out.squeeze()

    return out


def linalg_cond_p_str(A, p: str):
    """Dispatch wrapper for aten::linalg_cond.p_str (string p values like 'fro', 'nuc')."""
    return linalg_cond(A, p)
