# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def vander_kernel(
    x_ptr,
    out_ptr,
    N,
    total_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < total_elements

    # offsets map to flat output: out_flat[k*N + j] = x_flat[k] ** j
    col = offsets % N
    row = offsets // N

    x_val = tl.load(x_ptr + row, mask=mask)
    # Compute in the output dtype: fp64 for float64, fp32 otherwise (fp16/bf16
    # are upcast to fp32 since libdevice pow is not accurate at low precision).
    compute_dtype = tl.float64 if out_ptr.dtype.element_ty == tl.float64 else tl.float32
    result = tl_extra_shim.pow(x_val.to(compute_dtype), col.to(compute_dtype))

    tl.store(out_ptr + offsets, result, mask=mask)


@triton.jit
def vander_complex_kernel(
    x_ri_ptr,
    out_ri_ptr,
    N,
    total_elements,
    BLOCK_SIZE: tl.constexpr,
    STORE_FP64: tl.constexpr,
):
    """Complex vander: each output element is (a + b j)**p with integer p in [0, N).

    For p = 0 the result is 1 + 0 j. Otherwise we use the polar form
    (a + b j)**p = r**p * (cos(p*theta) + j sin(p*theta)) where
    r = sqrt(a*a + b*b) and theta = atan2(b, a). To preserve accuracy for
    large p (the test matrix has up to N=16 columns), the magnitude/angle
    arithmetic is carried out in fp64 regardless of the storage dtype, then
    truncated to complex64/complex128 at the store. Inputs/outputs are
    viewed as interleaved real/imag float arrays via torch.view_as_real so
    the kernel only ever handles real dtypes (Triton cannot specialise on
    complex tensors).
    """
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < total_elements

    # offsets index the flat *complex* output; each complex element occupies
    # two consecutive floats in the view_as_real layout.
    col = offsets % N  # exponent p
    row = offsets // N  # index into the flat complex input

    base = row * 2
    real = tl.load(x_ri_ptr + base, mask=mask, other=0.0)
    imag = tl.load(x_ri_ptr + base + 1, mask=mask, other=0.0)

    # Always compute in fp64 for accuracy; this matters for complex64 too
    # because r**p with p up to N-1 amplifies rounding error in fp32.
    real_compute = real.to(tl.float64)
    imag_compute = imag.to(tl.float64)

    # r = sqrt(a**2 + b**2), theta = atan2(b, a)
    mag = tl.sqrt(real_compute * real_compute + imag_compute * imag_compute)
    angle = tl_extra_shim.atan2(imag_compute, real_compute)

    # r**p via libdevice.pow (integer exponent cast to fp64); for p == 0
    # the result must be 1 + 0 j regardless of the input (matching torch).
    col_float = col.to(tl.float64)
    mag_pow = tl_extra_shim.pow(mag, col_float)
    angle_pow = angle * col_float

    out_real = tl.where(col == 0, 1.0, mag_pow * tl_extra_shim.cos(angle_pow))
    out_imag = tl.where(col == 0, 0.0, mag_pow * tl_extra_shim.sin(angle_pow))

    # Cast back to the storage dtype before storing.
    store_dtype = tl.float64 if STORE_FP64 else tl.float32
    out_real_store = out_real.to(store_dtype)
    out_imag_store = out_imag.to(store_dtype)

    out_base = offsets * 2
    tl.store(out_ri_ptr + out_base, out_real_store, mask=mask)
    tl.store(out_ri_ptr + out_base + 1, out_imag_store, mask=mask)


def linalg_vander(x, N=None):
    logger.debug("GEMS LINALG_VANDER")

    # fmt: off
    assert x.dtype.is_floating_point or x.dtype.is_complex, f"Unsupported dtype {x.dtype}"
    # fmt: on

    # Handle N parameter
    if N is None:
        N = x.shape[-1]

    # Get input shape info
    batch_dims = x.shape[:-1]
    n = x.shape[-1]

    # Flatten batch dims
    x_flat = x.reshape(-1)

    # Output shape: (*, n, N)
    final_shape = batch_dims + (n, N)

    # Run triton kernel
    total_elements = x_flat.numel() * N
    BLOCK_SIZE = 256
    grid = (triton.cdiv(total_elements, BLOCK_SIZE),)

    if x.is_complex():
        # Triton cannot specialise on complex tensor pointers, so we view the
        # complex input/output as interleaved real/imag float arrays and run
        # a kernel that operates purely on real dtypes. Allocate the complex
        # output via torch.empty_strided (not patched by flag_gems) since the
        # patched torch.empty kernel does not accept complex dtypes either.
        x_ri = torch.view_as_real(x_flat.contiguous()).reshape(-1)

        # Build contiguous strides for final_shape: strides[i] = prod(shape[i+1:]).
        strides = []
        stride = 1
        for dim in reversed(final_shape):
            strides.append(stride)
            stride *= dim
        strides.reverse()

        out = torch.empty_strided(
            final_shape, tuple(strides), dtype=x.dtype, device=x.device
        )
        out_flat = out.reshape(-1)
        out_ri = torch.view_as_real(out_flat).reshape(-1)

        store_fp64 = x.dtype == torch.complex128
        vander_complex_kernel[grid](
            x_ri,
            out_ri,
            N,
            total_elements,
            BLOCK_SIZE=BLOCK_SIZE,
            STORE_FP64=store_fp64,
        )
    else:
        out = torch.empty(final_shape, dtype=x.dtype, device=x.device)
        vander_kernel[grid](x_flat, out, N, total_elements, BLOCK_SIZE=BLOCK_SIZE)

    return out
