# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops._linalg_eigvals import _linalg_eigvals

logger = logging.getLogger(__name__)


def linalg_eigvals(A):
    """Canonical ``linalg_eigvals`` entry point.

    ``aten::linalg_eigvals`` is CompositeImplicitAutograd, so it already
    decomposes to ``aten::_linalg_eigvals`` and therefore already reaches
    FlagGems without this entry. Registering it makes the routing explicit
    instead of depending on the decomposition staying in place.
    """
    logger.debug("GEMS LINALG_EIGVALS")
    return _linalg_eigvals(A)


def linalg_eigvals_out(A, *, out):
    """Out overload for eigenvalues of a square matrix.

    ``.out`` overloads are not covered by the decomposition above, so without
    this entry ``linalg_eigvals.out`` never reaches FlagGems at all.
    """
    logger.debug("GEMS LINALG_EIGVALS_OUT")
    result = _linalg_eigvals(A)
    out.resize_(result.shape)
    out.copy_(result)
    return out
