# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.ops.bmm import bmm
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@triton.jit
def _axpy_kernel(
    OUT,  # accumulator, updated in place: OUT += coeff * TERM
    TERM,
    coeff,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = ext.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < n_elements
    acc = tl.load(OUT + offs, mask=mask)
    term = tl.load(TERM + offs, mask=mask)
    acc = acc + coeff * term
    tl.store(OUT + offs, acc, mask=mask)


@triton.jit
def _scale_kernel(
    OUT,
    INP,
    scale,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = ext.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < n_elements
    x = tl.load(INP + offs, mask=mask)
    tl.store(OUT + offs, x * scale, mask=mask)


@triton.jit
def _assemble_kernel(
    OUT,  # (B, 2n, 2n)
    AT,  # (B, n, n): transpose of self, upcast
    G,  # (B, n, n): grad, upcast
    B,
    n,
    n2,
    BLOCK_SIZE: tl.constexpr,
):
    # Build block matrix M = [[A^T, G], [0, A^T]] for each batch.
    pid = ext.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    total = B * n2 * n2
    mask = offs < total

    idx = offs
    col = idx % n2
    tmp = idx // n2
    row = tmp % n2
    b = tmp // n2

    top = row < n
    left = col < n
    r_in = tl.where(top, row, row - n)
    c_in = tl.where(left, col, col - n)
    src = b * n * n + r_in * n + c_in

    at_val = tl.load(AT + src, mask=mask, other=0.0)
    g_val = tl.load(G + src, mask=mask, other=0.0)

    # top-left: A^T ; top-right: G ; bottom-left: 0 ; bottom-right: A^T
    val = tl.where(
        top & left,
        at_val,
        tl.where(top & (~left), g_val, tl.where((~top) & (~left), at_val, 0.0)),
    )
    tl.store(OUT + offs, val, mask=mask)


@triton.jit
def _extract_kernel(
    OUT,  # (B, n, n): destination grad
    INP,  # (B, 2n, 2n): matrix exponential of block matrix
    B,
    n,
    n2,
    BLOCK_SIZE: tl.constexpr,
):
    # Extract the top-right (0:n, n:2n) block of each batch.
    pid = ext.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    total = B * n * n
    mask = offs < total

    idx = offs
    col = idx % n
    tmp = idx // n
    row = tmp % n
    b = tmp // n

    src = b * n2 * n2 + row * n2 + (col + n)
    val = tl.load(INP + src, mask=mask, other=0.0)
    tl.store(OUT + offs, val, mask=mask)


def _launch_axpy(out, term, coeff):
    n_elements = out.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(out.device):
        _axpy_kernel[grid](out, term, coeff, n_elements, BLOCK_SIZE=1024)


def _launch_scale(inp, scale):
    out = torch.empty_like(inp)
    n_elements = inp.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(inp.device):
        _scale_kernel[grid](out, inp, scale, n_elements, BLOCK_SIZE=1024)
    return out


def _matrix_exp(X, num_terms=None):
    """Compute the matrix exponential of a batch of square matrices ``X``
    (shape ``(B, m, m)``, floating point) using scaling and squaring with a
    truncated Taylor series. All heavy matrix products go through the Triton
    ``bmm`` kernel; the elementwise combine/scale steps use Triton kernels.
    """
    B, m, _ = X.shape

    if num_terms is None:
        # After scaling the spectral radius below 1, the Taylor series
        # converges quickly. float64 needs a longer series than 32-bit types.
        num_terms = 18 if X.dtype == torch.float64 else 13

    # Choose a scaling factor s such that ||X / 2^s|| is small, based on the
    # matrix infinity norm (max absolute row sum). Use a single scale for the
    # whole batch to keep the squaring loop uniform.
    norm = X.abs().sum(dim=-1).amax(dim=-1).amax()
    norm_val = float(norm.item())
    if norm_val > 0.0 and math.isfinite(norm_val):
        s = max(0, int(math.ceil(math.log2(norm_val))))
    else:
        s = 0
    scale = float(2.0**s)

    Xs = _launch_scale(X, 1.0 / scale) if s > 0 else X.clone()

    eye = torch.eye(m, dtype=X.dtype, device=X.device)
    result = eye.unsqueeze(0).expand(B, m, m).contiguous()
    term = result.clone()

    # result = I + Xs + Xs^2/2! + ... + Xs^k/k!
    for k in range(1, num_terms + 1):
        term = bmm(term, Xs)
        if k > 1:
            term = _launch_scale(term, 1.0 / k)
        _launch_axpy(result, term, 1.0)

    # Square s times to undo the scaling: exp(X) = (exp(X/2^s))^(2^s)
    for _ in range(s):
        result = bmm(result, result)

    return result


def matrix_exp_backward(self, grad):
    logger.debug("GEMS MATRIX_EXP_BACKWARD")
    assert self.shape == grad.shape, "self and grad must have the same shape"
    assert (
        self.ndim >= 2 and self.shape[-1] == self.shape[-2]
    ), "matrix_exp_backward expects square matrices"

    orig_shape = self.shape
    orig_dtype = self.dtype
    n = orig_shape[-1]
    n2 = 2 * n

    # Compute in float32 for half-precision inputs (float32/float64 kept as-is).
    if orig_dtype in (torch.float16, torch.bfloat16):
        compute_dtype = torch.float32
    else:
        compute_dtype = orig_dtype

    self_c = self.reshape(-1, n, n).to(compute_dtype)
    grad_c = grad.reshape(-1, n, n).to(compute_dtype).contiguous()
    B = self_c.shape[0]

    at = self_c.transpose(-1, -2).contiguous()

    # Assemble the block matrix M = [[A^T, G], [0, A^T]].
    block = torch.empty((B, n2, n2), dtype=compute_dtype, device=self.device)
    total = block.numel()
    grid = lambda meta: (triton.cdiv(total, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(self.device):
        _assemble_kernel[grid](block, at, grad_c, B, n, n2, BLOCK_SIZE=1024)

    expm = _matrix_exp(block)

    out = torch.empty((B, n, n), dtype=compute_dtype, device=self.device)
    total_out = out.numel()
    grid_out = lambda meta: (triton.cdiv(total_out, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(self.device):
        _extract_kernel[grid_out](out, expm, B, n, n2, BLOCK_SIZE=1024)

    return out.reshape(orig_shape).to(orig_dtype)
