# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

from flag_gems.ops.svd import svd

logger = logging.getLogger(__name__)


def nuclear_norm(A: torch.Tensor, keepdim: bool = False) -> torch.Tensor:
    """Computes the nuclear norm of a matrix.

    The nuclear norm is the sum of singular values over the last two dimensions.
    Mathematically: nuclear_norm(A) = sum(svdvals(A)).

    Args:
        A: Input tensor of shape (*, m, n) where * is zero or more batch dimensions.
        keepdim: If True, the reduced dimensions are retained with size 1.

    Returns:
        Nuclear norm. If keepdim=False, shape is (*,); if keepdim=True, shape is (*, 1, 1).
    """
    logger.debug("GEMS NUCLEAR_NORM")
    # Only float32 is supported for SVD on CUDA
    assert A.dtype == torch.float32, f"Expected float32, got {A.dtype}"
    if not A.is_contiguous():
        A = A.contiguous()

    try:
        # Use Triton-based SVD to compute singular values only.
        # nuclear_norm = sum of singular values
        result = svd(A, some=True, compute_uv=False)
        norm = result.S.sum(dim=-1)

        if keepdim:
            # Restore the last two dimensions with size 1
            norm = norm.unsqueeze(-1).unsqueeze(-1)

        return norm
    except NotImplementedError:
        # Fall back to native torch. Use torch.ops.aten to bypass flag_gems dispatch.
        _default_fn = getattr(getattr(torch.ops, "aten"), "nuclear_norm").default
        return _default_fn(A, keepdim=keepdim)
