# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""Triton implementation of dynamically quantized GRU inference.

The public aten operators carry CPU-side ``CellParamsBase`` objects.  The host
adapter below unpacks those objects once, copies their immutable packed weights
to the accelerator, and caches the device representation.  All forward-pass
numerical work (activation quantization, projections, recurrent updates and
copies) is performed by Triton kernels.

Unlike FBGEMM, the int8 path quantizes activations symmetrically per row.  This
is intentional: it lets a persistent program own one sequence without a global
reduction/barrier at every recurrent step.
"""

import logging
import threading
from collections import OrderedDict
from dataclasses import dataclass
from typing import Optional

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)
exp2 = tl_extra_shim.exp2
tanh = tl_extra_shim.tanh

_PERSISTENT_HIDDEN_LIMIT = 256
_PARAM_CACHE_LIMIT = 64
_PARAM_CACHE = OrderedDict()
_PARAM_CACHE_LOCK = threading.Lock()


@dataclass(frozen=True)
class _PreparedLinear:
    weight: torch.Tensor
    bias: torch.Tensor
    scales: Optional[torch.Tensor]
    zero_points: Optional[torch.Tensor]
    quantized: bool


@dataclass(frozen=True)
class _PreparedCell:
    ih: _PreparedLinear
    hh: _PreparedLinear


@triton.jit
def _sigmoid(x):
    log2e: tl.constexpr = 1.4426950408889634
    return 1.0 / (1.0 + exp2(-x * log2e))


@triton.jit
def _round_to_int8(x):
    rounded = tl.where(x >= 0.0, tl.floor(x + 0.5), tl.ceil(x - 0.5))
    return tl.maximum(tl.minimum(rounded, 127.0), -127.0).to(tl.int8)


@libentry()
@triton.jit
def rowwise_quantize_kernel(
    x_ptr,
    q_ptr,
    scale_ptr,
    sum_ptr,
    rows,
    cols: tl.constexpr,
    logical_batch,
    stride_xt,
    stride_xb,
    stride_xk,
    PACKED: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    row = tl.program_id(0)
    offs_k = tl.arange(0, BLOCK_K)
    mask = (row < rows) & (offs_k < cols)
    if PACKED:
        x_offsets = row * stride_xt + offs_k * stride_xk
    else:
        t = row // logical_batch
        b = row - t * logical_batch
        x_offsets = t * stride_xt + b * stride_xb + offs_k * stride_xk
    values = tl.load(x_ptr + x_offsets, mask=mask, other=0.0).to(tl.float32)
    max_abs = tl.max(tl.abs(values), axis=0)
    scale = tl.where(max_abs > 0.0, max_abs / 127.0, 1.0)
    quantized = _round_to_int8(values / scale)
    tl.store(q_ptr + row * cols + offs_k, quantized, mask=mask)
    tl.store(scale_ptr + row, scale, mask=row < rows)
    row_sum = tl.sum(tl.where(offs_k < cols, quantized.to(tl.int32), 0), axis=0)
    tl.store(sum_ptr + row, row_sum, mask=row < rows)


@libentry()
@triton.jit
def quantized_projection_kernel(
    q_ptr,
    x_scale_ptr,
    x_sum_ptr,
    weight_ptr,
    weight_scale_ptr,
    weight_zp_ptr,
    bias_ptr,
    out_ptr,
    rows,
    out_cols: tl.constexpr,
    in_cols: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.int32)
    for start_k in range(0, in_cols, BLOCK_K):
        k = start_k + offs_k
        qx = tl.load(
            q_ptr + offs_m[:, None] * in_cols + k[None, :],
            mask=(offs_m[:, None] < rows) & (k[None, :] < in_cols),
            other=0,
        )
        qw = tl.load(
            weight_ptr + offs_n[None, :] * in_cols + k[:, None],
            mask=(offs_n[None, :] < out_cols) & (k[:, None] < in_cols),
            other=0,
        )
        acc += tl.dot(qx, qw, out_dtype=tl.int32)

    x_sum = tl.load(x_sum_ptr + offs_m, mask=offs_m < rows, other=0)
    weight_zp = tl.load(weight_zp_ptr + offs_n, mask=offs_n < out_cols, other=0).to(
        tl.int32
    )
    acc -= x_sum[:, None] * weight_zp[None, :]
    x_scale = tl.load(x_scale_ptr + offs_m, mask=offs_m < rows, other=0.0).to(
        tl.float32
    )
    weight_scale = tl.load(
        weight_scale_ptr + offs_n, mask=offs_n < out_cols, other=0.0
    ).to(tl.float32)
    bias = tl.load(bias_ptr + offs_n, mask=offs_n < out_cols, other=0.0).to(tl.float32)
    result = acc.to(tl.float32) * x_scale[:, None] * weight_scale[None, :] + bias
    tl.store(
        out_ptr + offs_m[:, None] * out_cols + offs_n[None, :],
        result,
        mask=(offs_m[:, None] < rows) & (offs_n[None, :] < out_cols),
    )


@libentry()
@triton.jit
def fp_projection_kernel(
    x_ptr,
    weight_ptr,
    bias_ptr,
    out_ptr,
    rows,
    out_cols: tl.constexpr,
    in_cols: tl.constexpr,
    logical_batch,
    stride_xt,
    stride_xb,
    stride_xk,
    PACKED: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for start_k in range(0, in_cols, BLOCK_K):
        k = start_k + offs_k
        if PACKED:
            x_offsets = offs_m[:, None] * stride_xt + k[None, :] * stride_xk
        else:
            t = offs_m // logical_batch
            b = offs_m - t * logical_batch
            x_offsets = (
                t[:, None] * stride_xt + b[:, None] * stride_xb + k[None, :] * stride_xk
            )
        x = tl.load(
            x_ptr + x_offsets,
            mask=(offs_m[:, None] < rows) & (k[None, :] < in_cols),
            other=0.0,
        ).to(tl.float16)
        weight = tl.load(
            weight_ptr + offs_n[None, :] * in_cols + k[:, None],
            mask=(offs_n[None, :] < out_cols) & (k[:, None] < in_cols),
            other=0.0,
        ).to(tl.float16)
        acc += tl.dot(x, weight, out_dtype=tl.float32)
    bias = tl.load(bias_ptr + offs_n, mask=offs_n < out_cols, other=0.0).to(tl.float32)
    result = acc + bias[None, :]
    tl.store(
        out_ptr + offs_m[:, None] * out_cols + offs_n[None, :],
        result,
        mask=(offs_m[:, None] < rows) & (offs_n[None, :] < out_cols),
    )


@libentry()
@triton.jit
def persistent_quantized_gru_kernel(
    input_gates_ptr,
    hx_ptr,
    weight_ptr,
    weight_scale_ptr,
    weight_zp_ptr,
    bias_ptr,
    output_ptr,
    final_h_ptr,
    work_h_ptr,
    time_offsets_ptr,
    lengths_ptr,
    seq_len,
    batch_size,
    output_features,
    direction_offset,
    hidden_size: tl.constexpr,
    PACKED: tl.constexpr,
    REVERSE: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    b = tl.program_id(0)
    offs_h = tl.arange(0, BLOCK_H)
    h_mask = (b < batch_size) & (offs_h < hidden_size)
    initial_h = tl.load(hx_ptr + b * hidden_size + offs_h, mask=h_mask, other=0.0).to(
        tl.float32
    )
    tl.store(work_h_ptr + b * hidden_size + offs_h, initial_h, mask=h_mask)
    tl.debug_barrier()

    if PACKED:
        length = tl.load(lengths_ptr + b, mask=b < batch_size, other=0)
    else:
        length = seq_len

    for step in range(0, seq_len):
        active = (b < batch_size) & (step < length)
        if REVERSE:
            logical_t = length - 1 - step
        else:
            logical_t = step
        safe_t = tl.where(active, logical_t, 0)
        if PACKED:
            row = tl.load(time_offsets_ptr + safe_t, mask=active, other=0) + b
        else:
            row = safe_t * batch_size + b

        h_old = tl.load(
            work_h_ptr + b * hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        max_abs = tl.max(tl.abs(h_old), axis=0)
        h_scale = tl.where(max_abs > 0.0, max_abs / 127.0, 1.0)

        acc_r = tl.zeros((BLOCK_H,), dtype=tl.int32)
        acc_z = tl.zeros((BLOCK_H,), dtype=tl.int32)
        acc_n = tl.zeros((BLOCK_H,), dtype=tl.int32)
        h_sum = 0
        k_offsets = tl.arange(0, BLOCK_K)
        for start_k in range(0, hidden_size, BLOCK_K):
            k = start_k + k_offsets
            h_chunk = tl.load(
                work_h_ptr + b * hidden_size + k,
                mask=active & (k < hidden_size),
                other=0.0,
            ).to(tl.float32)
            qh = _round_to_int8(h_chunk / h_scale)
            h_sum += tl.sum(tl.where(k < hidden_size, qh.to(tl.int32), 0), axis=0)
            w_r = tl.load(
                weight_ptr + offs_h[None, :] * hidden_size + k[:, None],
                mask=active
                & (offs_h[None, :] < hidden_size)
                & (k[:, None] < hidden_size),
                other=0,
            ).to(tl.int32)
            w_z = tl.load(
                weight_ptr + (hidden_size + offs_h[None, :]) * hidden_size + k[:, None],
                mask=active
                & (offs_h[None, :] < hidden_size)
                & (k[:, None] < hidden_size),
                other=0,
            ).to(tl.int32)
            w_n = tl.load(
                weight_ptr
                + (2 * hidden_size + offs_h[None, :]) * hidden_size
                + k[:, None],
                mask=active
                & (offs_h[None, :] < hidden_size)
                & (k[:, None] < hidden_size),
                other=0,
            ).to(tl.int32)
            qh_i32 = qh.to(tl.int32)
            acc_r += tl.sum(qh_i32[:, None] * w_r, axis=0)
            acc_z += tl.sum(qh_i32[:, None] * w_z, axis=0)
            acc_n += tl.sum(qh_i32[:, None] * w_n, axis=0)

        scale_r = tl.load(
            weight_scale_ptr + offs_h, mask=offs_h < hidden_size, other=0.0
        ).to(tl.float32)
        scale_z = tl.load(
            weight_scale_ptr + hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0.0,
        ).to(tl.float32)
        scale_n = tl.load(
            weight_scale_ptr + 2 * hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0.0,
        ).to(tl.float32)
        zp_r = tl.load(weight_zp_ptr + offs_h, mask=offs_h < hidden_size, other=0).to(
            tl.int32
        )
        zp_z = tl.load(
            weight_zp_ptr + hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0,
        ).to(tl.int32)
        zp_n = tl.load(
            weight_zp_ptr + 2 * hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0,
        ).to(tl.int32)
        recurrent_r = (acc_r - h_sum * zp_r).to(tl.float32) * h_scale * scale_r
        recurrent_z = (acc_z - h_sum * zp_z).to(tl.float32) * h_scale * scale_z
        recurrent_n = (acc_n - h_sum * zp_n).to(tl.float32) * h_scale * scale_n

        recurrent_r += tl.load(
            bias_ptr + offs_h, mask=offs_h < hidden_size, other=0.0
        ).to(tl.float32)
        recurrent_z += tl.load(
            bias_ptr + hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0.0,
        ).to(tl.float32)
        recurrent_n += tl.load(
            bias_ptr + 2 * hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0.0,
        ).to(tl.float32)
        input_r = tl.load(
            input_gates_ptr + row * 3 * hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        input_z = tl.load(
            input_gates_ptr + row * 3 * hidden_size + hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        input_n = tl.load(
            input_gates_ptr + row * 3 * hidden_size + 2 * hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        reset = _sigmoid(input_r + recurrent_r)
        update = _sigmoid(input_z + recurrent_z)
        new = tanh(input_n + reset * recurrent_n)
        h_new = (h_old - new) * update + new
        tl.store(
            output_ptr + row * output_features + direction_offset + offs_h,
            h_new,
            mask=active & (offs_h < hidden_size),
        )
        tl.store(
            work_h_ptr + b * hidden_size + offs_h,
            h_new,
            mask=active & (offs_h < hidden_size),
        )
        tl.debug_barrier()

    final_h = tl.load(work_h_ptr + b * hidden_size + offs_h, mask=h_mask, other=0.0)
    tl.store(final_h_ptr + b * hidden_size + offs_h, final_h, mask=h_mask)


@libentry()
@triton.jit
def persistent_fp_gru_kernel(
    input_gates_ptr,
    hx_ptr,
    weight_ptr,
    bias_ptr,
    output_ptr,
    final_h_ptr,
    work_h_ptr,
    time_offsets_ptr,
    lengths_ptr,
    seq_len,
    batch_size,
    output_features,
    direction_offset,
    hidden_size: tl.constexpr,
    PACKED: tl.constexpr,
    REVERSE: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    b = tl.program_id(0)
    offs_h = tl.arange(0, BLOCK_H)
    h_mask = (b < batch_size) & (offs_h < hidden_size)
    initial_h = tl.load(hx_ptr + b * hidden_size + offs_h, mask=h_mask, other=0.0).to(
        tl.float32
    )
    tl.store(work_h_ptr + b * hidden_size + offs_h, initial_h, mask=h_mask)
    tl.debug_barrier()
    if PACKED:
        length = tl.load(lengths_ptr + b, mask=b < batch_size, other=0)
    else:
        length = seq_len

    for step in range(0, seq_len):
        active = (b < batch_size) & (step < length)
        if REVERSE:
            logical_t = length - 1 - step
        else:
            logical_t = step
        safe_t = tl.where(active, logical_t, 0)
        if PACKED:
            row = tl.load(time_offsets_ptr + safe_t, mask=active, other=0) + b
        else:
            row = safe_t * batch_size + b
        h_old = tl.load(
            work_h_ptr + b * hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        acc_r = tl.zeros((BLOCK_H,), dtype=tl.float32)
        acc_z = tl.zeros((BLOCK_H,), dtype=tl.float32)
        acc_n = tl.zeros((BLOCK_H,), dtype=tl.float32)
        k_offsets = tl.arange(0, BLOCK_K)
        for start_k in range(0, hidden_size, BLOCK_K):
            k = start_k + k_offsets
            h_chunk = tl.load(
                work_h_ptr + b * hidden_size + k,
                mask=active & (k < hidden_size),
                other=0.0,
            ).to(tl.float32)
            w_r = tl.load(
                weight_ptr + offs_h[None, :] * hidden_size + k[:, None],
                mask=active
                & (offs_h[None, :] < hidden_size)
                & (k[:, None] < hidden_size),
                other=0.0,
            ).to(tl.float32)
            w_z = tl.load(
                weight_ptr + (hidden_size + offs_h[None, :]) * hidden_size + k[:, None],
                mask=active
                & (offs_h[None, :] < hidden_size)
                & (k[:, None] < hidden_size),
                other=0.0,
            ).to(tl.float32)
            w_n = tl.load(
                weight_ptr
                + (2 * hidden_size + offs_h[None, :]) * hidden_size
                + k[:, None],
                mask=active
                & (offs_h[None, :] < hidden_size)
                & (k[:, None] < hidden_size),
                other=0.0,
            ).to(tl.float32)
            acc_r += tl.sum(h_chunk[:, None] * w_r, axis=0)
            acc_z += tl.sum(h_chunk[:, None] * w_z, axis=0)
            acc_n += tl.sum(h_chunk[:, None] * w_n, axis=0)

        recurrent_r = acc_r + tl.load(
            bias_ptr + offs_h, mask=offs_h < hidden_size, other=0.0
        ).to(tl.float32)
        recurrent_z = acc_z + tl.load(
            bias_ptr + hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0.0,
        ).to(tl.float32)
        recurrent_n = acc_n + tl.load(
            bias_ptr + 2 * hidden_size + offs_h,
            mask=offs_h < hidden_size,
            other=0.0,
        ).to(tl.float32)
        input_r = tl.load(
            input_gates_ptr + row * 3 * hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        input_z = tl.load(
            input_gates_ptr + row * 3 * hidden_size + hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        input_n = tl.load(
            input_gates_ptr + row * 3 * hidden_size + 2 * hidden_size + offs_h,
            mask=active & (offs_h < hidden_size),
            other=0.0,
        ).to(tl.float32)
        reset = _sigmoid(input_r + recurrent_r)
        update = _sigmoid(input_z + recurrent_z)
        new = tanh(input_n + reset * recurrent_n)
        h_new = (h_old - new) * update + new
        tl.store(
            output_ptr + row * output_features + direction_offset + offs_h,
            h_new,
            mask=active & (offs_h < hidden_size),
        )
        tl.store(
            work_h_ptr + b * hidden_size + offs_h,
            h_new,
            mask=active & (offs_h < hidden_size),
        )
        tl.debug_barrier()
    final_h = tl.load(work_h_ptr + b * hidden_size + offs_h, mask=h_mask, other=0.0)
    tl.store(final_h_ptr + b * hidden_size + offs_h, final_h, mask=h_mask)


@libentry()
@triton.jit
def copy_2d_kernel(
    src_ptr,
    dst_ptr,
    rows,
    cols,
    src_row_stride,
    dst_row_stride,
    BLOCK: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    total = rows * cols
    mask = offsets < total
    row = offsets // cols
    col = offsets - row * cols
    values = tl.load(src_ptr + row * src_row_stride + col, mask=mask, other=0.0)
    tl.store(dst_ptr + row * dst_row_stride + col, values, mask=mask)


@libentry()
@triton.jit
def recurrent_quantized_gate_kernel(
    qh_ptr,
    h_scale_ptr,
    h_sum_ptr,
    h_old_ptr,
    input_gates_ptr,
    weight_ptr,
    weight_scale_ptr,
    weight_zp_ptr,
    bias_ptr,
    next_h_ptr,
    output_ptr,
    active_batch,
    batch_size,
    hidden_size: tl.constexpr,
    input_row_offset,
    output_features,
    direction_offset,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    b = tl.program_id(0)
    pid_n = tl.program_id(1)
    n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    k_offsets = tl.arange(0, BLOCK_K)
    active = (b < active_batch) & (n < hidden_size)
    acc_r = tl.zeros((BLOCK_N,), dtype=tl.int32)
    acc_z = tl.zeros((BLOCK_N,), dtype=tl.int32)
    acc_n = tl.zeros((BLOCK_N,), dtype=tl.int32)
    for start_k in range(0, hidden_size, BLOCK_K):
        k = start_k + k_offsets
        qh = tl.load(
            qh_ptr + b * hidden_size + k,
            mask=(b < active_batch) & (k < hidden_size),
            other=0,
        ).to(tl.int32)
        wr = tl.load(
            weight_ptr + n[None, :] * hidden_size + k[:, None],
            mask=active[None, :] & (k[:, None] < hidden_size),
            other=0,
        ).to(tl.int32)
        wz = tl.load(
            weight_ptr + (hidden_size + n[None, :]) * hidden_size + k[:, None],
            mask=active[None, :] & (k[:, None] < hidden_size),
            other=0,
        ).to(tl.int32)
        wn = tl.load(
            weight_ptr + (2 * hidden_size + n[None, :]) * hidden_size + k[:, None],
            mask=active[None, :] & (k[:, None] < hidden_size),
            other=0,
        ).to(tl.int32)
        acc_r += tl.sum(qh[:, None] * wr, axis=0)
        acc_z += tl.sum(qh[:, None] * wz, axis=0)
        acc_n += tl.sum(qh[:, None] * wn, axis=0)
    hs = tl.load(h_scale_ptr + b, mask=b < active_batch, other=1.0).to(tl.float32)
    hsum = tl.load(h_sum_ptr + b, mask=b < active_batch, other=0).to(tl.int32)
    sr = tl.load(weight_scale_ptr + n, mask=n < hidden_size, other=0.0)
    sz = tl.load(weight_scale_ptr + hidden_size + n, mask=n < hidden_size, other=0.0)
    sn = tl.load(
        weight_scale_ptr + 2 * hidden_size + n, mask=n < hidden_size, other=0.0
    )
    zpr = tl.load(weight_zp_ptr + n, mask=n < hidden_size, other=0).to(tl.int32)
    zpz = tl.load(weight_zp_ptr + hidden_size + n, mask=n < hidden_size, other=0).to(
        tl.int32
    )
    zpn = tl.load(
        weight_zp_ptr + 2 * hidden_size + n, mask=n < hidden_size, other=0
    ).to(tl.int32)
    rr = (acc_r - hsum * zpr).to(tl.float32) * hs * sr
    rz = (acc_z - hsum * zpz).to(tl.float32) * hs * sz
    rn = (acc_n - hsum * zpn).to(tl.float32) * hs * sn
    rr += tl.load(bias_ptr + n, mask=n < hidden_size, other=0.0)
    rz += tl.load(bias_ptr + hidden_size + n, mask=n < hidden_size, other=0.0)
    rn += tl.load(bias_ptr + 2 * hidden_size + n, mask=n < hidden_size, other=0.0)
    ir = tl.load(
        input_gates_ptr + input_row_offset * 3 * hidden_size + b * 3 * hidden_size + n,
        mask=active,
        other=0.0,
    )
    iz = tl.load(
        input_gates_ptr
        + input_row_offset * 3 * hidden_size
        + b * 3 * hidden_size
        + hidden_size
        + n,
        mask=active,
        other=0.0,
    )
    inn = tl.load(
        input_gates_ptr
        + input_row_offset * 3 * hidden_size
        + b * 3 * hidden_size
        + 2 * hidden_size
        + n,
        mask=active,
        other=0.0,
    )
    old = tl.load(
        h_old_ptr + b * hidden_size + n,
        mask=(b < batch_size) & (n < hidden_size),
        other=0.0,
    ).to(tl.float32)
    reset = _sigmoid(ir + rr)
    update = _sigmoid(iz + rz)
    new = tanh(inn + reset * rn)
    updated = (old - new) * update + new
    next_value = tl.where(b < active_batch, updated, old)
    tl.store(
        next_h_ptr + b * hidden_size + n,
        next_value,
        mask=(b < batch_size) & (n < hidden_size),
    )
    tl.store(
        output_ptr + (input_row_offset + b) * output_features + direction_offset + n,
        updated,
        mask=active,
    )


@libentry()
@triton.jit
def recurrent_fp_gate_kernel(
    h_old_ptr,
    input_gates_ptr,
    weight_ptr,
    bias_ptr,
    next_h_ptr,
    output_ptr,
    active_batch,
    batch_size,
    hidden_size: tl.constexpr,
    input_row_offset,
    output_features,
    direction_offset,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    b = tl.program_id(0)
    pid_n = tl.program_id(1)
    n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    k_offsets = tl.arange(0, BLOCK_K)
    active = (b < active_batch) & (n < hidden_size)
    rr = tl.zeros((BLOCK_N,), dtype=tl.float32)
    rz = tl.zeros((BLOCK_N,), dtype=tl.float32)
    rn = tl.zeros((BLOCK_N,), dtype=tl.float32)
    for start_k in range(0, hidden_size, BLOCK_K):
        k = start_k + k_offsets
        h = tl.load(
            h_old_ptr + b * hidden_size + k,
            mask=(b < active_batch) & (k < hidden_size),
            other=0.0,
        ).to(tl.float32)
        wr = tl.load(
            weight_ptr + n[None, :] * hidden_size + k[:, None],
            mask=active[None, :] & (k[:, None] < hidden_size),
            other=0.0,
        ).to(tl.float32)
        wz = tl.load(
            weight_ptr + (hidden_size + n[None, :]) * hidden_size + k[:, None],
            mask=active[None, :] & (k[:, None] < hidden_size),
            other=0.0,
        ).to(tl.float32)
        wn = tl.load(
            weight_ptr + (2 * hidden_size + n[None, :]) * hidden_size + k[:, None],
            mask=active[None, :] & (k[:, None] < hidden_size),
            other=0.0,
        ).to(tl.float32)
        rr += tl.sum(h[:, None] * wr, axis=0)
        rz += tl.sum(h[:, None] * wz, axis=0)
        rn += tl.sum(h[:, None] * wn, axis=0)
    rr += tl.load(bias_ptr + n, mask=n < hidden_size, other=0.0)
    rz += tl.load(bias_ptr + hidden_size + n, mask=n < hidden_size, other=0.0)
    rn += tl.load(bias_ptr + 2 * hidden_size + n, mask=n < hidden_size, other=0.0)
    gate_base = input_row_offset * 3 * hidden_size + b * 3 * hidden_size
    ir = tl.load(input_gates_ptr + gate_base + n, mask=active, other=0.0)
    iz = tl.load(input_gates_ptr + gate_base + hidden_size + n, mask=active, other=0.0)
    inn = tl.load(
        input_gates_ptr + gate_base + 2 * hidden_size + n, mask=active, other=0.0
    )
    old = tl.load(
        h_old_ptr + b * hidden_size + n,
        mask=(b < batch_size) & (n < hidden_size),
        other=0.0,
    ).to(tl.float32)
    reset = _sigmoid(ir + rr)
    update = _sigmoid(iz + rz)
    new = tanh(inn + reset * rn)
    updated = (old - new) * update + new
    next_value = tl.where(b < active_batch, updated, old)
    tl.store(
        next_h_ptr + b * hidden_size + n,
        next_value,
        mask=(b < batch_size) & (n < hidden_size),
    )
    tl.store(
        output_ptr + (input_row_offset + b) * output_features + direction_offset + n,
        updated,
        mask=active,
    )


def _unwrap_state(obj):
    state = obj.__getstate__()
    if (
        isinstance(state, tuple)
        and len(state) == 2
        and isinstance(state[0], (tuple, list))
    ):
        return state[0]
    return state


def _unpack_linear(packed, fp16):
    op = (
        torch.ops.quantized.linear_unpack_fp16
        if fp16
        else torch.ops.quantized.linear_unpack
    )
    try:
        return op(packed)
    except (RuntimeError, TypeError, AttributeError):
        state = _unwrap_state(packed)
        if isinstance(state, (tuple, list)) and len(state) >= 2:
            payload = state[0]
            if isinstance(payload, (tuple, list)) and len(payload) >= 2:
                return payload[0], payload[1]
            return state[0], state[1]
        raise


def _expand_qparams(qweight, output_rows):
    per_channel_schemes = {
        torch.per_channel_affine,
        torch.per_channel_symmetric,
        torch.per_channel_affine_float_qparams,
    }
    if qweight.qscheme() in per_channel_schemes:
        if qweight.q_per_channel_axis() != 0:
            raise NotImplementedError(
                "GRU packed weights require output-channel qparams"
            )
        scales = qweight.q_per_channel_scales().to(torch.float32)
        zero_points = qweight.q_per_channel_zero_points().to(torch.int32)
    else:
        scales = torch.full(
            (output_rows,), float(qweight.q_scale()), dtype=torch.float32
        )
        zero_points = torch.full(
            (output_rows,), int(qweight.q_zero_point()), dtype=torch.int32
        )
    return scales, zero_points


def _prepare_linear(weight, bias, device):
    if weight.dtype in (torch.qint8, torch.quint8):
        if weight.dtype is not torch.qint8:
            raise NotImplementedError(
                "Only signed qint8 packed GRU weights are supported"
            )
        output_rows = weight.shape[0]
        scales, zero_points = _expand_qparams(weight, output_rows)
        raw_weight = weight.int_repr().to(device=device, dtype=torch.int8).contiguous()
        scales = scales.to(device=device).contiguous()
        zero_points = zero_points.to(device=device).contiguous()
        if bias is None:
            bias = torch.zeros(output_rows, dtype=torch.float32)
        bias = bias.to(device=device, dtype=torch.float32).contiguous()
        return _PreparedLinear(raw_weight, bias, scales, zero_points, True)

    output_rows = weight.shape[0]
    weight = weight.to(device=device, dtype=torch.float16).contiguous()
    if bias is None:
        bias = torch.zeros(output_rows, dtype=torch.float32)
    bias = bias.to(device=device, dtype=torch.float32).contiguous()
    return _PreparedLinear(weight, bias, None, None, False)


def _prepare_cell_uncached(param, device):
    state = _unwrap_state(param)
    if not isinstance(state, (tuple, list)) or not state:
        raise TypeError("Invalid quantized GRU CellParamsBase state")
    kind = state[0]
    if kind == "quantized_dynamic":
        packed = state[4]
        if len(packed) != 2:
            raise ValueError("Expected packed input-hidden and hidden-hidden weights")
        weight_ih, packed_bias_ih = _unpack_linear(packed[0], False)
        weight_hh, packed_bias_hh = _unpack_linear(packed[1], False)
        biases = state[1]
        bias_ih = packed_bias_ih if packed_bias_ih is not None else biases[0]
        bias_hh = packed_bias_hh if packed_bias_hh is not None else biases[1]
    elif kind == "quantized_fp16":
        packed = state[4]
        if len(packed) != 2:
            raise ValueError("Expected two fp16 packed GRU weights")
        weight_ih, bias_ih = _unpack_linear(packed[0], True)
        weight_hh, bias_hh = _unpack_linear(packed[1], True)
    elif kind == "quantized":
        tensors = state[1]
        weight_ih, weight_hh, bias_ih, bias_hh = tensors[:4]
    else:
        raise NotImplementedError(f"Unsupported quantized GRU parameter kind: {kind}")
    ih = _prepare_linear(weight_ih, bias_ih, device)
    hh = _prepare_linear(weight_hh, bias_hh, device)
    if ih.quantized != hh.quantized:
        raise ValueError(
            "GRU input and recurrent weights must use the same packing type"
        )
    return _PreparedCell(ih, hh)


def _prepare_cell(param, device):
    device_key = (device.type, device.index)
    key = (id(param), device_key)
    with _PARAM_CACHE_LOCK:
        cached = _PARAM_CACHE.get(key)
        if cached is not None and cached[0] is param:
            _PARAM_CACHE.move_to_end(key)
            return cached[1]
    prepared = _prepare_cell_uncached(param, device)
    with _PARAM_CACHE_LOCK:
        _PARAM_CACHE[key] = (param, prepared)
        _PARAM_CACHE.move_to_end(key)
        while len(_PARAM_CACHE) > _PARAM_CACHE_LIMIT:
            _PARAM_CACHE.popitem(last=False)
    return prepared


def _validate_common(
    input, hx, params, has_biases, num_layers, dropout, train, bidirectional
):
    if not has_biases:
        raise NotImplementedError("quantized GRU without biases is not supported")
    if train or dropout != 0.0:
        raise NotImplementedError(
            "quantized GRU supports inference with dropout=0 only"
        )
    if input.dtype not in (torch.float16, torch.bfloat16, torch.float32):
        raise TypeError(f"Unsupported quantized GRU activation dtype: {input.dtype}")
    if hx.dtype != input.dtype or hx.device != input.device:
        raise ValueError("input and hx must have the same dtype and device")
    directions = 2 if bidirectional else 1
    if hx.ndim != 3 or hx.shape[0] != num_layers * directions:
        raise ValueError("hx has an invalid layer/direction dimension")
    if len(params) != num_layers * directions:
        raise ValueError("params must contain one CellParamsBase per layer/direction")


def _quantize_rows(x, rows, cols, logical_batch, strides, packed):
    q = torch.empty((rows, cols), device=x.device, dtype=torch.int8)
    scales = torch.empty(rows, device=x.device, dtype=torch.float32)
    sums = torch.empty(rows, device=x.device, dtype=torch.int32)
    block_k = triton.next_power_of_2(cols)
    rowwise_quantize_kernel[(rows,)](
        x,
        q,
        scales,
        sums,
        rows,
        cols,
        logical_batch,
        strides[0],
        strides[1],
        strides[2],
        PACKED=packed,
        BLOCK_K=block_k,
        num_warps=4 if block_k >= 1024 else 2,
    )
    return q, scales, sums


def _project_input(
    x, prepared, rows, in_cols, logical_batch, strides, packed, quantized_input=None
):
    out_cols = prepared.weight.shape[0]
    gates = torch.empty((rows, out_cols), device=x.device, dtype=x.dtype)
    block_m = 16 if rows < 64 else 32
    block_n = 32 if out_cols < 128 else 64
    block_k = 32
    grid = (triton.cdiv(rows, block_m), triton.cdiv(out_cols, block_n))
    if prepared.quantized:
        q, scales, sums = quantized_input
        quantized_projection_kernel[grid](
            q,
            scales,
            sums,
            prepared.weight,
            prepared.scales,
            prepared.zero_points,
            prepared.bias,
            gates,
            rows,
            out_cols,
            in_cols,
            BLOCK_M=block_m,
            BLOCK_N=block_n,
            BLOCK_K=block_k,
            num_warps=4,
        )
    else:
        fp_projection_kernel[grid](
            x,
            prepared.weight,
            prepared.bias,
            gates,
            rows,
            out_cols,
            in_cols,
            logical_batch,
            strides[0],
            strides[1],
            strides[2],
            PACKED=packed,
            BLOCK_M=block_m,
            BLOCK_N=block_n,
            BLOCK_K=block_k,
            num_warps=4,
        )
    return gates


def _copy_2d(src, dst, rows, cols, src_row_stride=None, dst_row_stride=None):
    src_stride = src.stride(0) if src_row_stride is None else src_row_stride
    dst_stride = dst.stride(0) if dst_row_stride is None else dst_row_stride
    block = 256
    copy_2d_kernel[(triton.cdiv(rows * cols, block),)](
        src, dst, rows, cols, src_stride, dst_stride, BLOCK=block, num_warps=4
    )


def _run_persistent_direction(
    gates,
    hx,
    prepared_hh,
    output,
    final_h,
    seq_len,
    batch_size,
    hidden_size,
    direction_offset,
    reverse,
    packed,
    time_offsets,
    lengths,
):
    work_h = torch.empty((batch_size, hidden_size), device=hx.device, dtype=hx.dtype)
    block_h = triton.next_power_of_2(hidden_size)
    common = (
        gates,
        hx,
        prepared_hh.weight,
    )
    if prepared_hh.quantized:
        persistent_quantized_gru_kernel[(batch_size,)](
            *common,
            prepared_hh.scales,
            prepared_hh.zero_points,
            prepared_hh.bias,
            output,
            final_h,
            work_h,
            time_offsets,
            lengths,
            seq_len,
            batch_size,
            output.shape[-1],
            direction_offset,
            hidden_size,
            PACKED=packed,
            REVERSE=reverse,
            BLOCK_H=block_h,
            BLOCK_K=32,
            num_warps=4,
        )
    else:
        persistent_fp_gru_kernel[(batch_size,)](
            *common,
            prepared_hh.bias,
            output,
            final_h,
            work_h,
            time_offsets,
            lengths,
            seq_len,
            batch_size,
            output.shape[-1],
            direction_offset,
            hidden_size,
            PACKED=packed,
            REVERSE=reverse,
            BLOCK_H=block_h,
            BLOCK_K=32,
            num_warps=4,
        )


def _run_fallback_direction(
    gates,
    hx,
    prepared_hh,
    output,
    final_h,
    seq_len,
    batch_size,
    hidden_size,
    direction_offset,
    reverse,
    packed,
    offsets_host,
    batch_sizes_host,
):
    h_a = torch.empty_like(hx)
    h_b = torch.empty_like(hx)
    _copy_2d(hx, h_a, batch_size, hidden_size)
    block_n = 64
    grid = (batch_size, triton.cdiv(hidden_size, block_n))
    time_order = range(seq_len - 1, -1, -1) if reverse else range(seq_len)
    for t in time_order:
        active_batch = batch_sizes_host[t] if packed else batch_size
        row_offset = offsets_host[t] if packed else t * batch_size
        if prepared_hh.quantized:
            qh, hs, hsum = _quantize_rows(
                h_a,
                batch_size,
                hidden_size,
                batch_size,
                (h_a.stride(0), 0, h_a.stride(1)),
                True,
            )
            recurrent_quantized_gate_kernel[grid](
                qh,
                hs,
                hsum,
                h_a,
                gates,
                prepared_hh.weight,
                prepared_hh.scales,
                prepared_hh.zero_points,
                prepared_hh.bias,
                h_b,
                output,
                active_batch,
                batch_size,
                hidden_size,
                row_offset,
                output.shape[-1],
                direction_offset,
                BLOCK_N=block_n,
                BLOCK_K=32,
                num_warps=4,
            )
        else:
            recurrent_fp_gate_kernel[grid](
                h_a,
                gates,
                prepared_hh.weight,
                prepared_hh.bias,
                h_b,
                output,
                active_batch,
                batch_size,
                hidden_size,
                row_offset,
                output.shape[-1],
                direction_offset,
                BLOCK_N=block_n,
                BLOCK_K=32,
                num_warps=4,
            )
        h_a, h_b = h_b, h_a
    _copy_2d(h_a, final_h, batch_size, hidden_size)


def _packed_metadata(batch_sizes, device):
    sizes = [int(value) for value in batch_sizes.tolist()]
    if not sizes or sizes[0] <= 0:
        raise ValueError("batch_sizes must describe a non-empty packed sequence")
    if any(curr > prev or curr <= 0 for prev, curr in zip(sizes, sizes[1:])):
        raise ValueError("batch_sizes must be positive and non-increasing")
    offsets = []
    running = 0
    for size in sizes:
        offsets.append(running)
        running += size
    lengths = [0] * sizes[0]
    for size in sizes:
        for b in range(size):
            lengths[b] += 1
    offsets_dev = torch.tensor(offsets, device=device, dtype=torch.int64)
    lengths_dev = torch.tensor(lengths, device=device, dtype=torch.int64)
    return sizes, offsets, lengths, offsets_dev, lengths_dev, running


def _run_quantized_gru(
    layer_input,
    hx,
    params,
    num_layers,
    bidirectional,
    packed,
    seq_len,
    batch_size,
    rows,
    logical_strides,
    batch_sizes_host=None,
    offsets_host=None,
    time_offsets=None,
    lengths=None,
):
    directions = 2 if bidirectional else 1
    hidden_size = hx.shape[2]
    all_hidden = torch.empty_like(hx)
    dummy_metadata = hx.new_empty((1,), dtype=torch.int64)
    if time_offsets is None:
        time_offsets = dummy_metadata
    if lengths is None:
        lengths = dummy_metadata

    with torch_device_fn.device(layer_input.device):
        for layer in range(num_layers):
            in_cols = layer_input.shape[-1]
            prepared_cells = [
                _prepare_cell(params[layer * directions + d], layer_input.device)
                for d in range(directions)
            ]
            if any(
                cell.ih.weight.shape != (3 * hidden_size, in_cols)
                for cell in prepared_cells
            ):
                raise ValueError("packed input-hidden weight has an invalid shape")
            if any(
                cell.hh.weight.shape != (3 * hidden_size, hidden_size)
                for cell in prepared_cells
            ):
                raise ValueError("packed hidden-hidden weight has an invalid shape")
            if len({cell.ih.quantized for cell in prepared_cells}) != 1:
                raise ValueError(
                    "all directions in a layer must use the same weight dtype"
                )

            quantized_input = None
            if prepared_cells[0].ih.quantized:
                quantized_input = _quantize_rows(
                    layer_input,
                    rows,
                    in_cols,
                    batch_size,
                    logical_strides,
                    packed,
                )
            output_shape = (
                (rows, directions * hidden_size)
                if packed
                else (seq_len, batch_size, directions * hidden_size)
            )
            layer_output = torch.empty(
                output_shape, device=layer_input.device, dtype=layer_input.dtype
            )
            output_2d = layer_output.view(rows, directions * hidden_size)

            for direction, cell in enumerate(prepared_cells):
                gates = _project_input(
                    layer_input,
                    cell.ih,
                    rows,
                    in_cols,
                    batch_size,
                    logical_strides,
                    packed,
                    quantized_input,
                )
                hx_index = layer * directions + direction
                final_h = all_hidden[hx_index]
                reverse = direction == 1
                if hidden_size <= _PERSISTENT_HIDDEN_LIMIT:
                    _run_persistent_direction(
                        gates,
                        hx[hx_index],
                        cell.hh,
                        output_2d,
                        final_h,
                        seq_len,
                        batch_size,
                        hidden_size,
                        direction * hidden_size,
                        reverse,
                        packed,
                        time_offsets,
                        lengths,
                    )
                else:
                    _run_fallback_direction(
                        gates,
                        hx[hx_index],
                        cell.hh,
                        output_2d,
                        final_h,
                        seq_len,
                        batch_size,
                        hidden_size,
                        direction * hidden_size,
                        reverse,
                        packed,
                        offsets_host,
                        batch_sizes_host,
                    )
            layer_input = layer_output
            logical_strides = (
                (layer_output.stride(0), 0, layer_output.stride(1))
                if packed
                else layer_output.stride()
            )
    return layer_input, all_hidden


def quantized_gru_input(
    input,
    hx,
    params,
    has_biases,
    num_layers,
    dropout,
    train,
    bidirectional,
    batch_first,
):
    logger.debug("GEMS QUANTIZED_GRU.INPUT")
    _validate_common(
        input, hx, params, has_biases, num_layers, dropout, train, bidirectional
    )
    if input.ndim != 3:
        raise ValueError("quantized_gru.input expects a 3-D input")
    if batch_first:
        batch_size, seq_len, _ = input.shape
        logical_strides = (input.stride(1), input.stride(0), input.stride(2))
    else:
        seq_len, batch_size, _ = input.shape
        logical_strides = input.stride()
    if seq_len <= 0 or batch_size != hx.shape[1]:
        raise ValueError("invalid sequence length or batch size")
    output, hidden = _run_quantized_gru(
        input,
        hx,
        params,
        num_layers,
        bidirectional,
        False,
        seq_len,
        batch_size,
        seq_len * batch_size,
        logical_strides,
        batch_sizes_host=[batch_size] * seq_len,
        offsets_host=[t * batch_size for t in range(seq_len)],
    )
    if batch_first:
        output = output.transpose(0, 1)
    return output, hidden


def quantized_gru_data(
    data,
    batch_sizes,
    hx,
    params,
    has_biases,
    num_layers,
    dropout,
    train,
    bidirectional,
):
    logger.debug("GEMS QUANTIZED_GRU.DATA")
    _validate_common(
        data, hx, params, has_biases, num_layers, dropout, train, bidirectional
    )
    if data.ndim != 2 or batch_sizes.ndim != 1:
        raise ValueError("quantized_gru.data expects packed 2-D data and batch_sizes")
    sizes, offsets, _, offsets_dev, lengths_dev, rows = _packed_metadata(
        batch_sizes, data.device
    )
    if rows != data.shape[0] or sizes[0] != hx.shape[1]:
        raise ValueError("packed data, batch_sizes and hx are inconsistent")
    return _run_quantized_gru(
        data,
        hx,
        params,
        num_layers,
        bidirectional,
        True,
        len(sizes),
        sizes[0],
        rows,
        (data.stride(0), 0, data.stride(1)),
        batch_sizes_host=sizes,
        offsets_host=offsets,
        time_offsets=offsets_dev,
        lengths=lengths_dev,
    )


# Backwards-compatible Python import name.  Aten registration uses the two
# overload-specific wrappers above.
quantized_gru_impl = quantized_gru_input
