# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)

# Maximum supported polynomial degree (arbitrary but safe bound)
_MAX_POLY_DEGREE = tl.constexpr(101)


@pointwise_dynamic(promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def chebyshev_polynomial_t_func(x, n):
    """Chebyshev polynomial of the first kind T_n(x).

    Uses the 3-term recurrence that is valid for ALL real x:
        T_0(x) = 1
        T_1(x) = x
        T_n(x) = 2*x*T_{n-1}(x) - T_{n-2}(x)   for n >= 2
    """
    x_f32 = x.to(tl.float32)
    n_i32 = n.to(tl.int32)

    # T_0(x) = 1
    t0 = 1.0 + 0.0 * x_f32  # broadcast 1.0 to shape
    # T_1(x) = x
    t1 = x_f32

    result = t0
    result = tl.where(n_i32 == 1, t1, result)

    # Compute T_k for k >= 2 using recurrence
    t_km2 = t0
    t_km1 = t1
    for k in tl.static_range(2, _MAX_POLY_DEGREE):
        t_k = 2.0 * x_f32 * t_km1 - t_km2
        result = tl.where(n_i32 == k, t_k, result)
        t_km2 = t_km1
        t_km1 = t_k

    return result


def special_chebyshev_polynomial_t(x, n):
    logger.debug("GEMS SPECIAL_CHEBYSHEV_POLYNOMIAL_T")
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(
            f"special_chebyshev_polynomial_t only supports float32/float64, got {x.dtype}"
        )
    # Convert scalar n to tensor if needed
    if not isinstance(n, torch.Tensor):
        n = torch.tensor(n, dtype=torch.int64, device=x.device)
    return chebyshev_polynomial_t_func(x, n)


def special_chebyshev_polynomial_t_out(x, n, out):
    """Out-of-place variant for special_chebyshev_polynomial_t.

    ATen wrapper: special_chebyshev_polynomial_t.out(Tensor x, Scalar n, *, Tensor(a!) out) -> Tensor(a!)
    """
    logger.debug("GEMS SPECIAL_CHEBYSHEV_POLYNOMIAL_T_OUT")
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(
            f"special_chebyshev_polynomial_t only supports float32/float64, got {x.dtype}"
        )
    if not isinstance(n, torch.Tensor):
        n = torch.tensor(n, dtype=torch.int64, device=x.device)
    return chebyshev_polynomial_t_func(x, n, out0=out)
