# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Union

import torch

logger = logging.getLogger(__name__)


def _normalize_split_sizes(split_sizes):
    if isinstance(split_sizes, torch.Tensor):
        split_sizes = split_sizes.tolist()

    if hasattr(split_sizes, "__iter__"):
        split_sizes = list(split_sizes)

    return [int(size) for size in split_sizes]


def _normalize_dim(inp, dim):
    ndim = inp.ndim
    # Normalize negative dims using the same convention as aten.
    if dim < 0:
        dim += ndim
    # Match aten's IndexError message for out-of-range dimensions.
    if not (0 <= dim < ndim):
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[-{ndim}, {ndim - 1}], but got {dim - ndim if dim < 0 else dim})"
        )
    return dim


def split_with_sizes(
    inp: torch.Tensor,
    split_sizes: Union[List[int], torch.Tensor],
    dim: int = 0,
) -> List[torch.Tensor]:
    """Split a tensor into multiple sub-tensors along a given dimension.

    Unlike :func:`split_with_sizes_copy`, this returns views into the input
    tensor (matching the semantics of ``aten::split_with_sizes`` whose schema
    is ``Tensor(a -> *) self``).
    """
    logger.debug("GEMS SPLIT_WITH_SIZES")

    dim = _normalize_dim(inp, dim)
    split_sizes = _normalize_split_sizes(split_sizes)

    split_sum = sum(split_sizes)
    assert split_sum == inp.shape[dim], "Invalid split_sizes"

    result = []
    start = 0
    for size in split_sizes:
        result.append(inp.narrow(dim, start, size))
        start += size

    return result
