# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.ops.sum import sum_dim
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def sum_to_size_flat_kernel_1(
    inp,
    mid,
    M,
    BLOCK_SIZE: tl.constexpr,
):
    if tl.constexpr(inp.dtype.element_ty == tl.float16) or tl.constexpr(
        inp.dtype.element_ty == tl.bfloat16
    ):
        cdtype = tl.float32
    else:
        cdtype = inp.dtype.element_ty

    pid = ext.program_id(0)
    offset = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    inp_ptrs = inp + offset
    mask = offset < M
    inp_val = tl.load(inp_ptrs, mask=mask, other=0).to(cdtype)
    sum_val = tl.sum(inp_val)
    tl.store(mid + pid, sum_val)


@libentry()
@triton.jit
def sum_to_size_flat_kernel_2(mid, out, mid_size, BLOCK_MID: tl.constexpr):
    if tl.constexpr(mid.dtype.element_ty == tl.float16) or tl.constexpr(
        mid.dtype.element_ty == tl.bfloat16
    ):
        cdtype = tl.float32
    else:
        cdtype = mid.dtype.element_ty

    offset = tl.arange(0, BLOCK_MID)
    mid_ptrs = mid + offset
    mask = offset < mid_size
    mid_val = tl.load(mid_ptrs, mask=mask, other=0).to(cdtype)
    sum_val = tl.sum(mid_val)
    tl.store(out, sum_val)


def _full_reduce(inp, dtype):
    # Two-stage flat reduction over the whole tensor, matching ops/sum.py.
    inp = inp.contiguous()
    M = inp.numel()
    block_size = triton.next_power_of_2(math.ceil(math.sqrt(M)))
    mid_size = triton.cdiv(M, block_size)
    block_mid = triton.next_power_of_2(mid_size)

    mid = torch.empty((mid_size,), dtype=dtype, device=inp.device)
    out = torch.empty([], dtype=dtype, device=inp.device)
    with torch_device_fn.device(inp.device):
        sum_to_size_flat_kernel_1[(mid_size, 1, 1)](inp, mid, M, block_size)
        sum_to_size_flat_kernel_2[(1, 1, 1)](mid, out, mid_size, block_mid)
    return out


def sum_to_size(inp, *size):
    logger.debug("GEMS SUM_TO_SIZE")
    # ``size`` may arrive as a single sequence (the aten schema passes a
    # SymInt[] list) or as a variadic list of ints (Tensor.sum_to_size(*size)).
    if len(size) == 1 and isinstance(size[0], (list, tuple)):
        size = tuple(size[0])
    else:
        size = tuple(size)

    target_shape = list(size)
    inp_shape = list(inp.shape)

    # ``size`` must be broadcastable to the input shape. Reversing the broadcast
    # means summing over the leading dimensions that ``size`` does not cover and
    # over the trailing dimensions where the target size is 1 but the input is
    # not, keeping those dims so the result can be reshaped back to ``size``.
    leading_dims = inp.ndim - len(target_shape)
    reduce_dims = list(range(leading_dims))
    for i in range(leading_dims, inp.ndim):
        if target_shape[i - leading_dims] == 1 and inp_shape[i] != 1:
            reduce_dims.append(i)

    if len(reduce_dims) == 0:
        # Already the requested shape; only a (possibly trivial) reshape remains.
        return inp.reshape(target_shape)

    dtype = inp.dtype
    if dtype is torch.bool:
        inp = inp.to(torch.int64)
        dtype = torch.int64

    result_numel = 1
    for s in target_shape:
        result_numel *= s

    if result_numel <= 1:
        # Every dimension collapses to a single element: a full reduction is the
        # fastest layout (no transpose), so use the flat two-stage kernel.
        out = _full_reduce(inp, dtype)
        return out.reshape(target_shape)

    # Partial reduction: delegate to the tuned sum reduction kernels, which pick
    # coalesced inner / non-inner layouts and avoid a transpose for single dims.
    out = sum_dim(inp, reduce_dims, keepdim=True)
    return out.reshape(target_shape)
