# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

logger = logging.getLogger(__name__)


def t_(inp: torch.Tensor) -> torch.Tensor:
    """In-place transpose of a tensor with at most 2 dimensions.

    ``t_`` is a pure view operation: it only swaps the shape and stride
    metadata of ``inp`` without moving any data, matching the semantics of
    ``torch.Tensor.t_``. For 0D/1D tensors it is a no-op; for 2D tensors it
    swaps the two dimensions (and their strides) in place, so the result is a
    transposed view over the original storage.
    """
    logger.debug("GEMS T_")
    dim = inp.dim()
    if dim < 2:
        # 0D scalar / 1D tensor - no-op, same as torch.Tensor.t_
        return inp
    if dim > 2:
        raise RuntimeError("t_ expects a tensor with <= 2 dimensions")

    # 2D tensor - transpose in place by swapping shape and stride only.
    # This works for both square and non-square matrices and preserves the
    # underlying storage, producing a (generally non-contiguous) view exactly
    # like the native aten::t_ operator.
    M, N = inp.shape
    s0, s1 = inp.stride()
    inp.as_strided_([N, M], [s1, s0])
    return inp
