# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Union

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def vsplit_copy_kernel(
    input_ptr,
    output_ptr,
    num_elements,
    start: tl.constexpr,  # chunk start offset along dim=0
    prod_post: tl.constexpr,  # product of dims after dim=0
    BLOCK_SIZE: tl.constexpr,
):
    """Copy one row-wise chunk from ``input`` into a contiguous ``output``.

    The input is viewed as (dim_size_input, prod_post). This chunk owns
    ``input[start:start + dim_size_output, ...]``. Because the split is along
    dim=0 there is nothing preceding it, so the source index is just the
    destination index shifted by ``start * prod_post``.
    """
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < num_elements

    input_idx = offsets + start * prod_post

    data = tl.load(input_ptr + input_idx, mask=mask)
    tl.store(output_ptr + offsets, data, mask=mask)


def vsplit(input: torch.Tensor, indices_or_sections: Union[int, List[int]]):
    """Split a tensor along the first axis (row-wise).

    ``torch.vsplit`` splits along ``dim=0`` and requires a tensor with two or
    more dimensions. Each chunk is produced by a Triton kernel that copies the
    corresponding row slice into a freshly allocated output, so no PyTorch
    computation operator is called (only ``torch.empty`` for allocation, per
    the host-function conventions).

    Note that the integer form is stricter than ``torch.tensor_split``: it
    requires the dimension to divide evenly and raises otherwise, matching
    ``torch.vsplit``.
    """
    logger.debug("GEMS VSPLIT")

    if input.ndim < 2:
        raise RuntimeError(
            f"vsplit requires a tensor with 2 or more dimensions, got {input.ndim}"
        )

    dim = 0
    dim_size = input.shape[dim]

    # Resolve the chunk sizes along the row dimension.
    if isinstance(indices_or_sections, int):
        n = indices_or_sections
        if n <= 0:
            raise ValueError(f"indices_or_sections must be positive, got {n}")
        # torch.vsplit requires an even division, unlike torch.tensor_split.
        if dim_size % n != 0:
            raise RuntimeError(
                f"torch.vsplit attempted to split along dimension {dim}, but the "
                f"size of the dimension {dim_size} is not divisible by the "
                f"split_size {n}!"
            )
        chunk_sizes = [dim_size // n] * n
    else:
        chunk_sizes = []
        prev = 0
        for idx in indices_or_sections:
            idx = max(0, min(idx, dim_size))
            chunk_sizes.append(idx - prev)
            prev = idx
        chunk_sizes.append(dim_size - prev)

    # prod of dims after the row dimension.
    prod_post = 1
    for s in input.shape[dim + 1 :]:
        prod_post *= s

    input_contiguous = input.contiguous()

    # BLOCK_SIZE=1024: standard 1D copy tile, memory-bound so any power-of-two
    # in the 256-2048 range performs equivalently.
    BLOCK_SIZE = 1024

    outputs = []
    start = 0
    for chunk_size in chunk_sizes:
        out_shape = list(input.shape)
        out_shape[dim] = chunk_size
        output = torch.empty(out_shape, dtype=input.dtype, device=input.device)

        num_elements = chunk_size * prod_post
        if num_elements > 0:
            grid = (triton.cdiv(num_elements, BLOCK_SIZE),)
            vsplit_copy_kernel[grid](
                input_contiguous,
                output,
                num_elements,
                start,
                prod_post,
                BLOCK_SIZE=BLOCK_SIZE,
            )
        outputs.append(output)
        start += chunk_size

    return tuple(outputs)
